#!/usr/bin/env node
// scripts/voice/build-data.mjs — turns the linguists' source files (<lang>.mjs, plain data) into lib/voice/data/<lang>.ts.
// Usage: node scripts/voice/build-data.mjs <dir-with-lang.mjs-files>
// The engine never imports the .mjs files: the generated .ts files are the shipped data, reviewed and committed like code.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const dir = resolve(process.argv[2] || '.');
const out = resolve(new URL('../../lib/voice/data/', import.meta.url).pathname);
const LANGS = ['en', 'el', 'ro', 'ar', 'de', 'pl', 'ru'];
const DESKS = ['news', 'business', 'property_legal', 'relocation_guide', 'economy', 'culture', 'food', 'fashion_lifestyle', 'travel', 'events', 'interview', 'review', 'people'];
let failed = 0;

for (const lang of LANGS) {
  const file = join(dir, `${lang}.mjs`);
  if (!existsSync(file)) { console.log(`- ${lang}: no source file, skipped`); continue; }
  const d = (await import(pathToFileURL(file).href)).default;
  const errs = [];
  if (d.lang !== lang) errs.push(`lang is "${d.lang}"`);
  const keys = new Set();
  for (const t of d.tells || []) {
    if (!t.key || keys.has(t.key)) errs.push(`duplicate or missing key ${t.key}`); keys.add(t.key);
    if (!['high', 'medium', 'low'].includes(t.severity)) errs.push(`${t.key}: bad severity`);
    if (!['word', 'start', 'raw'].includes(t.kind)) errs.push(`${t.key}: bad kind`);
    if (!Array.isArray(t.alts) || !t.alts.length) errs.push(`${t.key}: no alts`);
    try { new RegExp((t.alts || []).join('|'), 'giu'); } catch (e) { errs.push(`${t.key}: ${e.message}`); }
  }
  for (const k of ['banned', 'closers', 'openers', 'sheet']) if (!Array.isArray(d[k]) || !d[k].length) errs.push(`${k} is empty`);
  if (!Array.isArray(d.pairs) || d.pairs.length < 6) errs.push('fewer than 6 pairs');
  for (const k of DESKS) if (!d.desks?.[k]) errs.push(`desk note missing: ${k}`);
  if (errs.length) { failed++; console.log(`✗ ${lang}: ${errs.slice(0, 8).join('; ')}`); continue; }
  const data = { lang, tells: d.tells.map(({ key, label, severity, kind, alts, min }) => (min && min > 1 ? { key, label, severity, kind, alts, min } : { key, label, severity, kind, alts })), banned: d.banned, closers: d.closers, openers: d.openers, sheet: d.sheet, pairs: d.pairs, desks: d.desks };
  const ts = `// GENERATED by scripts/voice/build-data.mjs from the ${lang.toUpperCase()} linguist source. Edit the source data and regenerate; do not hand-edit.\nimport type { LangVoiceData } from '@/lib/voice/types';\n\nconst data: LangVoiceData = ${JSON.stringify(data, null, 1)};\n\nexport default data;\n`;
  writeFileSync(join(out, `${lang}.ts`), ts);
  console.log(`✓ ${lang}: ${data.tells.length} tells, ${data.banned.length} banned, ${data.closers.length} closers, ${data.openers.length} openers, ${data.sheet.length} sheet rules, ${data.pairs.length} pairs`);
}
process.exit(failed ? 1 : 0);
