// lib/journalism/embeddings.ts — one small client for OpenAI embeddings, used by the article desk to compare texts by MEANING.
// Pure apart from the injected fetch: no Node- or Deno-only calls, so the Next app and the Supabase edge functions run the same code
// (the edge copy is generated by scripts/build-edge-journalism.mjs). Any failure answers null; the desk then goes on without the
// comparison (and says so in its log) instead of stopping.
//
// The model reads many languages and places a sentence and its translation close together, which is what makes it possible to compare a
// Greek source with a German edition at all. It is NOT a plagiarism detector by itself: close in meaning is normal when two texts report
// the same facts; the desk looks for closeness in meaning AND in order (see semantic.ts).

export const EMBED_MODEL_DEFAULT = 'text-embedding-3-small';
/** USD per 1,000,000 input tokens (OpenAI pricing page, text-embedding-3-small). Overridable: OPENAI_EMBED_USD_PER_MTOK. */
export const EMBED_USD_PER_MTOK = 0.02;
/** The longest text sent as one input, in characters (a sentence is far shorter; a runaway paragraph is cut). */
export const EMBED_MAX_CHARS = 700;
/** The most inputs in one request (the API allows 2,048). */
export const EMBED_MAX_INPUTS = 1_000;

export interface EmbedDeps {
  apiKey: string;
  fetch?: typeof fetch;
  model?: string;
  baseUrl?: string;
  timeoutMs?: number;
  /** Called once per answered request with the tokens billed and the cost in USD. */
  onUsage?: (e: { tokens: number; usd: number; inputs: number; ms: number }) => void | Promise<void>;
  usdPerMtok?: number;
  now?: () => number;
}

/** One vector per input, in the order of the inputs; null when the key is missing, the request fails or the answer is not usable. */
export async function embedTexts(texts: readonly string[], d: EmbedDeps): Promise<number[][] | null> {
  const inputs = texts.map((t) => String(t || '').replace(/\s+/g, ' ').trim().slice(0, EMBED_MAX_CHARS) || ' ');
  if (!d.apiKey || !inputs.length || inputs.length > EMBED_MAX_INPUTS) return null;
  const f = d.fetch ?? fetch;
  const now = d.now ?? Date.now;
  const t0 = now();
  try {
    const res = await f(`${(d.baseUrl || 'https://api.openai.com/v1').replace(/\/+$/, '')}/embeddings`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${d.apiKey}` },
      body: JSON.stringify({ model: d.model || EMBED_MODEL_DEFAULT, input: inputs }),
      signal: AbortSignal.timeout(d.timeoutMs ?? 30_000),
    });
    if (!res.ok) return null;
    const body = await res.json() as { data?: Array<{ index?: number; embedding?: unknown }>; usage?: { total_tokens?: number; prompt_tokens?: number } };
    const out: number[][] = new Array(inputs.length);
    for (const item of Array.isArray(body.data) ? body.data : []) {
      const i = Number(item.index);
      if (Number.isInteger(i) && i >= 0 && i < inputs.length && Array.isArray(item.embedding) && item.embedding.length > 8) out[i] = item.embedding as number[];
    }
    for (let i = 0; i < inputs.length; i++) if (!out[i]) return null;
    const tokens = Number(body.usage?.total_tokens ?? body.usage?.prompt_tokens) || inputs.reduce((n, s) => n + Math.ceil(s.length / 3), 0);
    if (d.onUsage) { try { await d.onUsage({ tokens, usd: +(tokens * (d.usdPerMtok ?? EMBED_USD_PER_MTOK) / 1_000_000).toFixed(8), inputs: inputs.length, ms: now() - t0 }); } catch { /* telemetry never breaks a call */ } }
    return out;
  } catch { return null; }
}

export function cosine(a: readonly number[], b: readonly number[]): number {
  let dot = 0; let na = 0; let nb = 0;
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) { dot += a[i] * b[i]; na += a[i] * a[i]; nb += b[i] * b[i]; }
  return na && nb ? dot / Math.sqrt(na * nb) : 0;
}
