// lib/journalism/openai.ts — one OpenAI client for the whole text desk (Responses API). Pure: no imports except ./models, no
// Node- or Deno-only calls (fetch, setTimeout and AbortSignal.timeout exist in both), so the Next app and the Supabase edge
// functions run the SAME code (the edge copy is generated by scripts/build-edge-journalism.mjs).
//
// What it does that a bare fetch does not:
//   • reasoning models bill their hidden thinking as OUTPUT tokens and count it against max_output_tokens. A cap sized for the
//     visible text alone can be eaten up by the thinking, leaving an empty reply that was still paid for. The cap therefore
//     always includes a reserve for the chosen effort, and a reply cut off by the cap is retried once with a larger one;
//   • strict structured outputs (json_schema) with an automatic fall-back to plain JSON mode if the schema is refused;
//   • an effort the model refuses is stepped down one level at a time instead of being dropped;
//   • Flex processing (half price, slower, may be unavailable) for background jobs, with an immediate fall-back to standard;
//   • the built-in web search tool, with the calls counted and priced;
//   • 429s are told apart: "slow down" (wait, retry) versus "out of credit / spend limit" (stop, a retry cannot help);
//   • every billed response, complete or not, is reported once through deps.onUsage (spend log), with reasoning, cached and
//     cache-write tokens, the processing tier and the search fee priced correctly.
import { costUsd, outputCap, isBlockedModel, MAX_OUTPUT_CAP, EFFORT_ORDER, type Effort, type EnvLike, type Usage } from './models';

export type JsonSpec = 'object' | { name: string; schema: Record<string, unknown> };

export interface LlmRequest {
  model: string;
  system: string;
  user: string;
  effort?: Effort | null;
  maxOutputTokens?: number;
  /** About how many visible tokens the answer will have; sizes max_output_tokens together with the reasoning reserve. */
  expectTokens?: number;
  json?: JsonSpec;
  timeoutMs?: number;
  /** Label for the spend log, e.g. "compose-ro". */
  fn?: string;
  /** Same key on calls that share a long prefix (the seven editions) lets OpenAI reuse the cached prefix. */
  cacheKey?: string;
  /** "flex": half price, slower, may be refused for lack of capacity (then the call is repeated at standard speed). Background jobs only. */
  serviceTier?: 'flex';
  /** How long a Flex attempt may take before the call falls back to standard processing. */
  flexTimeoutMs?: number;
  /** Give the model OpenAI's built-in web search. Structured output formats are not combined with it (the prompt asks for JSON instead). */
  webSearch?: boolean;
}

export type ErrorKind = 'auth' | 'billing' | 'rate' | 'overloaded' | 'bad_request' | 'schema' | 'not_found' | 'timeout' | 'network' | 'refusal' | 'incomplete' | 'empty' | 'unknown';

export interface UsageEvent { fn: string; model: string; usage: Usage; usd: number; ms: number; status: string; effort?: Effort | null; webSearchCalls?: number }
export interface LlmDeps {
  apiKey: string;
  fetch?: typeof fetch;
  sleep?: (ms: number) => Promise<void>;
  now?: () => number;
  baseUrl?: string;
  env?: EnvLike;
  maxAttempts?: number;
  /** Absolute time (ms, same clock as now) after which no new attempt is started. */
  deadlineAt?: number;
  onUsage?: (e: UsageEvent) => void | Promise<void>;
}

export interface LlmResult {
  ok: boolean;
  text: string;
  error?: string;
  kind?: ErrorKind;
  status: string;
  incompleteReason?: string;
  usage: Usage;
  /** Raw provider cost in USD, all attempts together (no markup). */
  usd: number;
  attempts: number;
  ms: number;
  model: string;
  effort?: Effort | null;
  /** The effort that was finally sent (it may be lower than requested if the model refused the first value). */
  effortUsed?: Effort | null;
  webSearchCalls?: number;
  /** "flex" when the answer came from Flex processing. */
  tierUsed?: string;
}

export const ZERO_USAGE: Usage = { inputTokens: 0, cachedTokens: 0, outputTokens: 0, reasoningTokens: 0, cacheWriteTokens: 0 };
const addUsage = (a: Usage, b: Usage): Usage => ({
  inputTokens: a.inputTokens + b.inputTokens, cachedTokens: a.cachedTokens + b.cachedTokens,
  outputTokens: a.outputTokens + b.outputTokens, reasoningTokens: a.reasoningTokens + b.reasoningTokens,
  cacheWriteTokens: (a.cacheWriteTokens ?? 0) + (b.cacheWriteTokens ?? 0), serviceTier: b.serviceTier || a.serviceTier,
});

/** What one web search call costs (OpenAI bills search actions per call). Overridable: OPENAI_WEB_SEARCH_USD. */
export const DEFAULT_WEB_SEARCH_USD = 0.01;
const searchFee = (env: EnvLike | undefined) => { const v = Number(env?.OPENAI_WEB_SEARCH_USD); return Number.isFinite(v) && v >= 0 && env?.OPENAI_WEB_SEARCH_USD !== undefined && env.OPENAI_WEB_SEARCH_USD !== '' ? v : DEFAULT_WEB_SEARCH_USD; };

// ── request ───────────────────────────────────────────────────────────────────
export function buildRequestBody(req: LlmRequest): Record<string, unknown> {
  const effort = req.effort ?? null;
  const cap = Math.min(MAX_OUTPUT_CAP, req.maxOutputTokens ?? outputCap(req.expectTokens ?? 3_000, effort ?? 'medium'));
  let system = req.system;
  // JSON mode insists the word "JSON" appears in the prompt.
  if (req.json === 'object' && !/json/i.test(`${req.system}\n${req.user}`)) system += '\n\nRespond with a single JSON object and nothing else.';
  const body: Record<string, unknown> = {
    model: req.model,
    instructions: system,
    input: req.user,
    max_output_tokens: cap,
    store: false,
  };
  if (effort) body.reasoning = { effort };
  if (req.webSearch) {
    body.tools = [{ type: 'web_search' }];
    // Web search and a forced output format are not documented together: ask for JSON in words and parse it loosely.
    if (req.json && !/json/i.test(`${req.system}\n${req.user}`)) body.instructions = `${system}\n\nReturn a single JSON object and nothing else.`;
  } else if (req.json === 'object') body.text = { format: { type: 'json_object' } };
  else if (req.json) body.text = { format: { type: 'json_schema', name: req.json.name, strict: true, schema: req.json.schema } };
  if (req.cacheKey) body.prompt_cache_key = req.cacheKey;
  if (req.serviceTier === 'flex') body.service_tier = 'flex';
  return body;
}

// ── response ──────────────────────────────────────────────────────────────────
export interface ParsedResponse { text: string; refusal: string; status: string; incompleteReason: string; usage: Usage; errorMessage: string; webSearchCalls: number }

export function parseResponse(data: unknown): ParsedResponse {
  const d = (data && typeof data === 'object' ? data : {}) as {
    status?: unknown; incomplete_details?: { reason?: unknown } | null; error?: { message?: unknown } | null; output?: unknown; service_tier?: unknown;
    usage?: { input_tokens?: unknown; output_tokens?: unknown; input_tokens_details?: { cached_tokens?: unknown; cache_write_tokens?: unknown }; output_tokens_details?: { reasoning_tokens?: unknown } };
  };
  const out = Array.isArray(d.output) ? (d.output as { type?: string; content?: { type?: string; text?: string; refusal?: string }[] }[]) : [];
  let text = ''; let refusal = ''; let webSearchCalls = 0;
  for (const item of out) {
    if (item?.type === 'web_search_call') { webSearchCalls++; continue; }
    if (item?.type !== 'message' || !Array.isArray(item.content)) continue;
    for (const part of item.content) {
      if (part?.type === 'output_text' && typeof part.text === 'string') text += part.text;
      else if (part?.type === 'refusal' && typeof part.refusal === 'string' && !refusal) refusal = part.refusal;
    }
  }
  const n = (v: unknown) => (Number.isFinite(Number(v)) ? Number(v) : 0);
  return {
    text: text.trim(),
    refusal,
    status: typeof d.status === 'string' ? d.status : 'unknown',
    incompleteReason: typeof d.incomplete_details?.reason === 'string' ? d.incomplete_details.reason : '',
    usage: {
      inputTokens: n(d.usage?.input_tokens), cachedTokens: n(d.usage?.input_tokens_details?.cached_tokens),
      outputTokens: n(d.usage?.output_tokens), reasoningTokens: n(d.usage?.output_tokens_details?.reasoning_tokens),
      cacheWriteTokens: n(d.usage?.input_tokens_details?.cache_write_tokens),
      serviceTier: typeof d.service_tier === 'string' ? d.service_tier : undefined,
    },
    errorMessage: typeof d.error?.message === 'string' ? d.error.message : '',
    webSearchCalls,
  };
}

// ── errors ────────────────────────────────────────────────────────────────────
export interface Classified { kind: ErrorKind; retry: boolean; message: string }

/** Tell the failures apart: only "slow down" and "overloaded" are worth another try. */
export function classifyError(status: number, data: unknown): Classified {
  const e = ((data && typeof data === 'object' ? (data as { error?: unknown }).error : null) ?? {}) as { message?: string; code?: string; type?: string };
  const message = String(e.message || `HTTP ${status}`);
  const code = String(e.code || ''); const type = String(e.type || '');
  if (status === 401 || status === 403) return { kind: 'auth', retry: false, message };
  if (status === 404) return { kind: 'not_found', retry: false, message };
  if (status === 429) {
    const out = code === 'insufficient_quota' || type === 'insufficient_quota' || code === 'billing_hard_limit_reached'
      || (/quota|billing|spend limit|hard limit|credit balance|out of credit|exceeded your current/i.test(message) && !/per min|per minute|rate limit reached|requests per|tokens per/i.test(message));
    return out ? { kind: 'billing', retry: false, message } : { kind: 'rate', retry: true, message };
  }
  if (status === 408 || status === 409 || status >= 500) return { kind: 'overloaded', retry: true, message };
  if (status === 400) {
    if (/json_schema|response_format|text\.format|schema|strict/i.test(message)) return { kind: 'schema', retry: false, message };
    return { kind: 'bad_request', retry: false, message };
  }
  return { kind: 'unknown', retry: false, message };
}

/** "Retry-After: 7" (seconds) or an HTTP date → ms. Also reads OpenAI's reset headers such as "1s", "6m0s", "20ms". */
export function waitFromHeaders(get: (name: string) => string | null, nowMs: number): number | null {
  const ra = get('retry-after');
  if (ra) {
    const s = Number(ra);
    if (Number.isFinite(s)) return Math.max(0, Math.round(s * 1000));
    const t = Date.parse(ra);
    if (Number.isFinite(t)) return Math.max(0, t - nowMs);
  }
  const reset = get('x-ratelimit-reset-tokens') || get('x-ratelimit-reset-requests');
  if (reset) {
    let ms = 0; let any = false;
    for (const m of reset.matchAll(/(\d+(?:\.\d+)?)(ms|s|m|h)/g)) {
      any = true;
      const v = Number(m[1]);
      ms += m[2] === 'ms' ? v : m[2] === 's' ? v * 1000 : m[2] === 'm' ? v * 60_000 : v * 3_600_000;
    }
    if (any) return Math.round(ms);
  }
  return null;
}

const defaultSleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));
const isTimeout = (e: unknown) => { const n = (e as { name?: string })?.name; return n === 'TimeoutError' || n === 'AbortError'; };
const lowerEffort = (e: Effort): Effort | null => { const i = EFFORT_ORDER.indexOf(e); return i > EFFORT_ORDER.indexOf('low') ? EFFORT_ORDER[i - 1] : null; };

// ── the call ──────────────────────────────────────────────────────────────────
export async function callOpenAI(req: LlmRequest, deps: LlmDeps): Promise<LlmResult> {
  const now = deps.now ?? (() => Date.now());
  const sleep = deps.sleep ?? defaultSleep;
  const doFetch = deps.fetch ?? fetch;
  const url = `${(deps.baseUrl || 'https://api.openai.com').replace(/\/+$/, '')}/v1/responses`;
  const maxAttempts = Math.max(1, deps.maxAttempts ?? 3);
  const fn = req.fn || 'llm';
  const t0 = now();
  let usage = ZERO_USAGE; let usd = 0; let attempts = 0; let searches = 0;
  const result = (r: Partial<LlmResult> & { ok: boolean; text: string }): LlmResult => ({
    status: 'unknown', usage, usd: +usd.toFixed(6), attempts, ms: now() - t0, model: req.model, effort: req.effort ?? null,
    effortUsed: (body.reasoning as { effort?: Effort } | undefined)?.effort ?? null, webSearchCalls: searches, tierUsed: usage.serviceTier, ...r,
  });
  const body = buildRequestBody(req);
  if (isBlockedModel(req.model)) return result({ ok: false, text: '', error: `model ${req.model} is blocked by policy and is never called`, kind: 'bad_request' });
  if (!deps.apiKey) return result({ ok: false, text: '', error: 'OPENAI_API_KEY not configured', kind: 'auth' });

  let bumped = false; let schemaDowngraded = false; let flexDropped = false;
  let last: { kind: ErrorKind; message: string } = { kind: 'unknown', message: 'no attempt made' };

  while (attempts < maxAttempts) {
    if (deps.deadlineAt !== undefined && now() >= deps.deadlineAt - 1_500) return result({ ok: false, text: '', error: `out of time before attempt ${attempts + 1}`, kind: 'timeout' });
    attempts++;
    const budget = deps.deadlineAt !== undefined ? Math.max(2_000, deps.deadlineAt - now()) : Infinity;
    const flexing = body.service_tier === 'flex';
    const timeoutMs = Math.min(flexing ? (req.flexTimeoutMs ?? 40_000) : (req.timeoutMs ?? 120_000), budget);
    let res: Response;
    const tStart = now();
    try {
      res = await doFetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${deps.apiKey}` },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(timeoutMs),
      });
    } catch (e) {
      if (isTimeout(e)) {
        // Flex is slow by design: when it does not answer in time, ask again at standard speed (if there is time left).
        if (flexing && !flexDropped && attempts < maxAttempts) { flexDropped = true; delete body.service_tier; continue; }
        // A standard call that timed out was already slow: a second try would only burn another full window.
        return result({ ok: false, text: '', error: `${fn}: no answer after ${Math.round(timeoutMs / 1000)}s`, kind: 'timeout' });
      }
      last = { kind: 'network', message: (e as Error)?.message || 'network error' };
      await sleep(900 * attempts);
      continue;
    }
    const raw = await res.text().catch(() => '');
    let data: unknown = null;
    try { data = raw ? JSON.parse(raw) : null; } catch { data = null; }

    if (!res.ok) {
      const c = classifyError(res.status, data);
      last = { kind: c.kind, message: c.message };
      // Flex: "429 Resource Unavailable" (not billed) or a refusal of the tier means: do it at standard speed, now.
      if (flexing && !flexDropped && (res.status === 429 || res.status === 408 || res.status >= 500 || /service_tier|flex/i.test(c.message)) && c.kind !== 'billing') {
        flexDropped = true; delete body.service_tier; continue;
      }
      if (c.kind === 'schema' && !schemaDowngraded && body.text && (body.text as { format?: { type?: string } }).format?.type === 'json_schema') {
        schemaDowngraded = true; body.text = { format: { type: 'json_object' } };
        if (!/json/i.test(String(body.instructions))) body.instructions = `${body.instructions}\n\nRespond with a single JSON object and nothing else.`;
        continue;
      }
      if (c.kind === 'bad_request' && body.reasoning && /reasoning|effort/i.test(c.message)) {
        // The model refuses this effort: one level lower, and so on; when nothing is left, no effort at all (the model's default).
        const eff = (body.reasoning as { effort: Effort }).effort;
        const lower = lowerEffort(eff);
        if (lower) body.reasoning = { effort: lower }; else delete body.reasoning;
        continue;
      }
      if (c.kind === 'bad_request' && body.prompt_cache_key && /prompt_cache_key/i.test(c.message)) { delete body.prompt_cache_key; continue; }
      if (!c.retry || attempts >= maxAttempts) return result({ ok: false, text: '', error: c.message, kind: c.kind });
      const headerWait = waitFromHeaders((n) => res.headers.get(n), now());
      const wait = Math.min(20_000, headerWait ?? (1_200 * 2 ** (attempts - 1) + Math.floor(Math.random() * 400)));
      if (headerWait !== null && headerWait > 25_000) return result({ ok: false, text: '', error: `${c.message} (asked to wait ${Math.round(headerWait / 1000)}s)`, kind: c.kind });
      await sleep(wait);
      continue;
    }

    const p = parseResponse(data);
    const fee = p.webSearchCalls * searchFee(deps.env);
    const spent = +(costUsd(req.model, p.usage, deps.env ?? {}) + fee).toFixed(6);
    usage = addUsage(usage, p.usage); usd += spent; searches += p.webSearchCalls;
    if (deps.onUsage) { try { await deps.onUsage({ fn, model: req.model, usage: p.usage, usd: spent, ms: now() - tStart, status: p.status, effort: (body.reasoning as { effort?: Effort } | undefined)?.effort ?? req.effort ?? null, webSearchCalls: p.webSearchCalls }); } catch { /* telemetry never breaks a call */ } }

    if (p.status === 'failed') return result({ ok: false, text: '', error: p.errorMessage || 'the model reported a failure', kind: 'unknown', status: p.status });
    if (p.status === 'incomplete') {
      const cap = Number(body.max_output_tokens) || 0;
      if (p.incompleteReason === 'max_output_tokens' && !bumped && cap < MAX_OUTPUT_CAP && attempts < maxAttempts) {
        // The cap was used up (mostly by hidden reasoning). Billed already; try once with room to finish.
        bumped = true; body.max_output_tokens = Math.min(MAX_OUTPUT_CAP, Math.ceil(cap * 1.7));
        last = { kind: 'incomplete', message: `cap ${cap} used up (${p.usage.reasoningTokens} reasoning tokens)` };
        continue;
      }
      return result({ ok: false, text: p.text, error: `incomplete: ${p.incompleteReason || 'unknown reason'} (cap ${cap}, ${p.usage.reasoningTokens} reasoning tokens)`, kind: 'incomplete', status: p.status, incompleteReason: p.incompleteReason });
    }
    if (!p.text) {
      if (p.refusal) return result({ ok: false, text: '', error: `refused: ${p.refusal.slice(0, 160)}`, kind: 'refusal', status: p.status });
      return result({ ok: false, text: '', error: 'empty reply (no visible text)', kind: 'empty', status: p.status });
    }
    return result({ ok: true, text: p.text, status: p.status });
  }
  return result({ ok: false, text: '', error: last.message, kind: last.kind });
}

// ── JSON helpers ──────────────────────────────────────────────────────────────
/** Parse JSON out of a model reply: strict first, then without code fences, then the outermost braces. null when hopeless. */
export function parseJsonLoose<T = Record<string, unknown>>(raw: string): T | null {
  const s = String(raw || '').trim();
  if (!s) return null;
  try { return JSON.parse(s) as T; } catch { /* next */ }
  const cleaned = s.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/i, '').trim();
  try { return JSON.parse(cleaned) as T; } catch { /* next */ }
  const a = cleaned.indexOf('{'); const b = cleaned.lastIndexOf('}');
  if (a !== -1 && b > a) { try { return JSON.parse(cleaned.slice(a, b + 1)) as T; } catch { /* next */ } }
  return null;
}
