// GENERATED by scripts/voice/build-data.mjs from the DE linguist source. Edit the source data and regenerate; do not hand-edit.
import type { LangVoiceData } from '@/lib/voice/types';

const data: LangVoiceData = {
 "lang": "de",
 "tells": [
  {
   "key": "de_sinnbild",
   "label": "Bedeutungsaufladung (steht sinnbildlich für, Spiegelbild, legt Zeugnis ab)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "legt(?:e|en)? (?:\\p{L}+ )?Zeugnis ab",
    "(?:ein|eine) (?:\\p{L}+ )?(?:Sinnbild|Leuchtturm|Spiegelbild|Aushängeschild) (?:für|der|des|von)",
    "steht (?:sinnbildlich|symbolisch|stellvertretend|exemplarisch) für",
    "ein Spiegel (?:der|des|von)"
   ]
  },
  {
   "key": "de_bedeutung_rolle",
   "label": "Leere Gewichtung (gewinnt an Bedeutung, nimmt eine Schlüsselstellung ein, trägt maßgeblich bei)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:gewinnt|gewinnen|gewann) (?:\\p{L}+ )?an Bedeutung",
    "nimmt (?:\\p{L}+ ){0,2}(?:Rolle|Stellung|Schlüsselposition|Schlüsselrolle) ein",
    "kommt (?:\\p{L}+ ){0,2}(?:Bedeutung|Rolle) zu",
    "(?:hohen?|großen?|zentralen?|besonderen?) Stellenwert",
    "Schlüsselrolle",
    "Schlüsselfigur",
    "(?:trägt|tragen|trug) (?:maßgeblich|wesentlich|entscheidend) (?:dazu )?bei",
    "legt(?:e)? den Grundstein",
    "ebnet(?:e)? den Weg"
   ]
  },
  {
   "key": "de_verdeutlicht",
   "label": "Kommentarverben (verdeutlicht, spiegelt wider, zeugt von, einmal mehr)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "verdeutlicht",
    "veranschaulicht",
    "illustriert",
    "spiegelt\\s[^.?!]{0,60}wider",
    "zeugt von",
    "zeugen von",
    "macht (?:\\p{L}+ )?deutlich",
    "eindrucksvoll",
    "eindrücklich",
    "einmal mehr"
   ],
   "min": 3
  },
  {
   "key": "de_pillar_metaphor",
   "label": "Tragwerks-Metaphern (Herzstück, Dreh- und Angelpunkt, Rückgrat, Eckpfeiler)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Herzstück",
    "Dreh- und Angelpunkt",
    "Rückgrat (?:der|des|von)",
    "Eckpfeiler",
    "Grundpfeiler",
    "Katalysator",
    "Wegbereiter",
    "Leuchtturm\\p{L}*",
    "Aushängeschild",
    "Schmelztiegel",
    "Gesamtpaket"
   ],
   "min": 2
  },
  {
   "key": "de_tapestry",
   "label": "Teppich/Mosaik-Metaphern (reicher Teppich, buntes Mosaik, Geflecht)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:reich(?:e|es|er|en)?|bunt(?:e|es|er|en)?|lebendig(?:e|es|er|en)?|vielfältig(?:e|es|er|en)?) (?:Teppich|Wandteppich|Mosaik|Gobelin|Geflecht|Gewebe)",
    "Wandteppich",
    "Mosaik aus"
   ]
  },
  {
   "key": "de_lexicon_more",
   "label": "Weitere KI-Lieblingswörter (maßgeblich, essenziell, umfassend, vielschichtig, Zusammenspiel, Facetten)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "maßgeblich\\p{L}*",
    "essen[zt]iell\\p{L}*",
    "umfassend\\p{L}*",
    "bemerkenswert\\p{L}*",
    "vielschichtig\\p{L}*",
    "Zusammenspiel",
    "Facetten",
    "Wechselspiel",
    "ganzheitlich\\p{L}*",
    "holistisch\\p{L}*",
    "robust\\p{L}*",
    "dynamisch\\p{L}*"
   ],
   "min": 4
  },
  {
   "key": "de_verb_brochure",
   "label": "Prospekt-Verben (besticht durch, punktet mit, hält bereit, entführt)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "besticht (?:durch|mit)",
    "überzeugt (?:durch|mit)",
    "punktet (?:mit|durch)",
    "glänzt (?:mit|durch)",
    "zeichnet sich (?:\\p{L}+ )?durch[^.?!]{0,60}aus",
    "verfügt über",
    "hält [^.?!]{0,40}bereit",
    "wartet (?:\\p{L}+ )?(?:auf|mit)",
    "entführt (?:Sie|Besucher|Gäste|den Leser|uns)",
    "nimmt (?:Sie|Besucher|Gäste|den Leser|uns) mit auf"
   ],
   "min": 2
  },
  {
   "key": "de_beliebtheit",
   "label": "Trend-Floskeln (erfreut sich großer Beliebtheit, wachsendes Interesse)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "erfreut(?:e)? sich (?:\\p{L}+ ){0,2}(?:Beliebtheit|Popularität|Interesses|Nachfrage)",
    "wachsende(?:s|n|m)? (?:Interesse|Beliebtheit|Nachfrage)",
    "ungebrochen\\p{L}* (?:Beliebtheit|Nachfrage|Interesse)",
    "boomt"
   ]
  },
  {
   "key": "de_throat_clear",
   "label": "Räusper-Floskeln (Es sei darauf hingewiesen, Hierbei ist zu beachten, Nicht zu vergessen)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Es (?:sei|ist|bleibt) (?:an dieser Stelle |hier )?(?:darauf )?(?:hinzuweisen|festzuhalten|anzumerken|zu betonen|zu erwähnen|zu berücksichtigen|zu bedenken)",
    "Es (?:gilt|sollte|muss|darf) (?:hier |dabei |an dieser Stelle )?(?:darauf hingewiesen|erwähnt|betont|beachtet|angemerkt|bedacht) (?:zu )?werden",
    "(?:Hierbei|Dabei|Hier) (?:ist|sei|gilt) (?:es )?(?:zu beachten|zu bedenken|wichtig|zu berücksichtigen|hervorzuheben)",
    "An dieser Stelle (?:sei|ist|gilt|muss|sollte)",
    "Nicht unerwähnt (?:bleiben|bleibt)",
    "Nicht zu vergessen",
    "Erwähnenswert ist",
    "Hervorzuheben ist",
    "Zu beachten ist",
    "Zu erwähnen ist",
    "Wichtig zu wissen",
    "Es lohnt sich,? (?:\\p{L}+ )?(?:zu erwähnen|hervorzuheben|anzumerken)"
   ]
  },
  {
   "key": "de_throat_start",
   "label": "Absatzbeginn mit Meta-Ansage (Im Folgenden, Zunächst einmal, Lassen Sie uns, Stellen Sie sich vor)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Vorab (?:sei|ist|gilt)",
    "Zunächst einmal",
    "Bevor wir",
    "Lassen Sie uns",
    "Werfen wir einen",
    "Schauen wir",
    "Beginnen wir",
    "Fangen wir",
    "Man könnte (?:meinen|sagen|annehmen)",
    "Haben Sie sich (?:je|schon|einmal)",
    "Kennen Sie das",
    "Stellen Sie sich vor",
    "Stell dir vor",
    "Willkommen (?:in|auf|im|bei)",
    "Im Folgenden",
    "Nachfolgend",
    "Hier erfahren Sie",
    "Alles,? was Sie",
    "Was Sie (?:über|wissen)"
   ]
  },
  {
   "key": "de_meta_article",
   "label": "Artikel spricht über sich selbst (In diesem Artikel, Dieser Leitfaden beleuchtet, ultimativer Guide)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:In|Auf) (?:den|dem) (?:folgenden|nachfolgenden) (?:Abschnitt\\p{L}*|Absätzen)",
    "Dieser (?:Artikel|Beitrag|Text|Leitfaden|Ratgeber) (?:beleuchtet|zeigt|gibt|stellt|erklärt|erläutert|richtet|bietet|fasst|informiert)",
    "In diesem (?:Artikel|Beitrag|Leitfaden|Ratgeber|Text) (?:erfahren|zeigen|erklären|beleuchten|werfen|stellen|gehen|geben)",
    "Erfahren Sie (?:mehr|alles|wie|was|warum|hier)",
    "Alles,? was Sie (?:über|zu|wissen)",
    "ultimativ\\p{L}*",
    "(?:kompletter|umfassender|vollständiger) (?:Leitfaden|Guide|Ratgeber)",
    "Lesen Sie (?:weiter|hier|mehr)"
   ]
  },
  {
   "key": "de_imperative_cta",
   "label": "Werbe-Imperativ am Absatzbeginn (Erleben Sie, Genießen Sie, Gönnen Sie sich, Sichern Sie sich)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Erleben Sie",
    "Genießen Sie",
    "Tauchen Sie",
    "Freuen Sie sich",
    "Erkunden Sie",
    "Begeben Sie sich",
    "Begleiten Sie uns",
    "Gönnen Sie sich",
    "Verpassen Sie nicht",
    "Sichern Sie sich",
    "Machen Sie sich bereit",
    "Lassen Sie sich (?:verzaubern|entführen|überraschen|inspirieren|verführen)"
   ]
  },
  {
   "key": "de_rhetorical_start",
   "label": "Rhetorische Frage als Absatzauftakt (Was macht …, Warum lohnt …, Kennen Sie …)",
   "severity": "low",
   "kind": "start",
   "alts": [
    "Was (?:macht|bedeutet|passiert|ist das)",
    "Warum (?:ist|sollte|lohnt|eigentlich)",
    "Wer (?:hätte|dachte)",
    "Wie (?:sieht|würde)",
    "Kennen Sie",
    "Ist das (?:wirklich|nicht)",
    "Wo (?:sonst|bitte)"
   ],
   "min": 2
  },
  {
   "key": "de_zeitgeist",
   "label": "Zeitgeist-/Binsen-Einstieg (Heutzutage, Seit jeher, Es ist kein Geheimnis, Fakt ist)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "In einer (?:Zeit|Welt|Ära|Epoche),? in der",
    "Heutzutage",
    "Seit jeher",
    "Seit Menschengedenken",
    "Von jeher",
    "Seit (?:Jahrhunderten|Jahrtausenden)",
    "Es ist (?:kein|längst kein|nun kein) Geheimnis",
    "Wie wir alle wissen",
    "Wohl kaum jemand",
    "Niemand kann (?:leugnen|bestreiten)",
    "Fakt ist",
    "Tatsache ist",
    "Unbestritten ist"
   ]
  },
  {
   "key": "de_wenn_es_um",
   "label": "„Wenn es um … geht“ / Zielgruppen-Ansprache",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Wenn es um [^.?!]{3,70} geht",
    "Geht es um [^.?!]{3,60}, (?:ist|hat|kommt|gibt|führt)",
    "Für alle,? die [^.?!]{3,80}, (?:ist|bietet|hat|gibt)"
   ]
  },
  {
   "key": "de_fuer_zielgruppe",
   "label": "Katalog-Zielgruppe („Für Genießer bietet …“)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Für (?:Feinschmecker|Genießer|Gourmets|Kunstliebhaber|Kulturliebhaber|Naturliebhaber|Strandliebhaber|Weinliebhaber|Abenteurer|Entdecker|Sonnenanbeter|Familien|Paare|Wanderer|Anleger|Investoren|Auswanderer|Rentner|Digitalnomaden)[^.?!]{0,40}(?:bietet|hält|ist|gibt|hat|wird|findet|lohnt)"
   ],
   "min": 2
  },
  {
   "key": "de_wer_cond",
   "label": "„Wer … sucht, findet …“-Konditionalsatz",
   "severity": "low",
   "kind": "word",
   "alts": [
    "Wer [^.?!,]{3,70}, (?:findet|kommt (?:an|um|nicht)|wird|sollte|darf|der)"
   ],
   "min": 2
  },
  {
   "key": "de_universal",
   "label": "Allerwelts-Zielgruppe (Jung und Alt, Wir alle, Wer kennt das nicht)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:für |ob )?Jung (?:und|oder) Alt",
    "(?:für |ob )?Groß (?:und|oder) Klein",
    "Wir alle",
    "Jeder von uns",
    "Wer kennt das nicht",
    "Wer wünscht sich nicht",
    "Wer (?:träumt|sehnt sich) nicht"
   ]
  },
  {
   "key": "de_enum_scaffold",
   "label": "Aufzählungs-Gerüst am Absatzbeginn (Erstens, Die wichtigsten Punkte, Auf einen Blick, Dazu zählen)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Erstens",
    "Zweitens",
    "Drittens",
    "Viertens",
    "Zum Ersten",
    "Zum Zweiten",
    "Zum Dritten",
    "Punkt (?:eins|zwei|drei)",
    "Die wichtigsten (?:Punkte|Erkenntnisse|Fakten|Stichpunkte|Aspekte|Tipps|Schritte)",
    "Wichtige (?:Punkte|Erkenntnisse|Aspekte)",
    "Key Takeaways?",
    "Kurz und knapp",
    "Auf einen Blick",
    "Hier (?:sind|finden Sie) (?:die|einige|\\d+)",
    "Dazu (?:gehören|zählen|zählt)",
    "Folgende (?:Punkte|Aspekte|Faktoren|Schritte)",
    "Die folgenden"
   ]
  },
  {
   "key": "de_erstens_zweitens",
   "label": "Erstens … Zweitens … im Fließtext",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Erstens,?[^\\n]{3,400}\\bZweitens"
   ]
  },
  {
   "key": "de_closer_more",
   "label": "Weitere Schluss-Opener (Im Ergebnis, Festzuhalten bleibt, Man kann also sagen, Eines ist klar)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Im Ergebnis",
    "Schlussendlich",
    "Bleibt (?:also )?festzuhalten",
    "Festzuhalten (?:bleibt|ist)",
    "Man kann (?:also |daher |somit )?(?:sagen|festhalten|resümieren)",
    "Kurz (?:und knapp )?gesagt",
    "Kurzum",
    "Letzten Endes",
    "Als Fazit",
    "Zum Abschluss",
    "Abschließend betrachtet",
    "Zusammengefasst",
    "Zusammenfassung",
    "Resümierend",
    "Resümee",
    "Eines (?:ist|steht)",
    "Eins (?:ist|steht)",
    "Am Ende (?:zählt|geht|bleibt)",
    "Letztlich (?:zählt|geht|bleibt)",
    "Fest steht",
    "Unser Fazit",
    "Mein Fazit"
   ]
  },
  {
   "key": "de_future_closer",
   "label": "Floskel-Ausblick (Die Zeit wird zeigen, Es bleibt spannend, Man darf gespannt sein)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:Nur )?die Zeit wird (?:es )?zeigen",
    "Es bleibt (?:abzuwarten|spannend|zu hoffen)",
    "(?:Man|man) darf gespannt sein",
    "gespannt sein,? (?:wie|ob|was)",
    "Die Zukunft (?:wird zeigen|bleibt spannend|sieht rosig aus|verspricht)",
    "Wohin die Reise geht",
    "wird sich zeigen",
    "vielversprechende Zukunft",
    "Zukunft (?:sieht|ist) (?:rosig|vielversprechend|hell)",
    "bleibt spannend"
   ]
  },
  {
   "key": "de_moral",
   "label": "Moral-Schluss (Am Ende zählt, Die Botschaft ist klar, Es geht um mehr als)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Am Ende (?:zählt|geht es|des Tages)",
    "Letztlich geht es (?:\\p{L}+ )?(?:um|darum)",
    "Letztendlich (?:geht|zählt)",
    "Die Botschaft ist klar",
    "Die Moral von der",
    "Eines zeigt sich (?:deutlich|klar)",
    "Es geht (?:letztlich |am Ende )?um mehr als",
    "ein Weckruf",
    "Die Frage ist nicht (?:mehr )?(?:ob|mehr ob)"
   ]
  },
  {
   "key": "de_end_of_day",
   "label": "Anglizismus-Schlussformel (am Ende des Tages)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "am Ende des Tages",
    "Unterm Strich",
    "unter dem Strich"
   ],
   "min": 2
  },
  {
   "key": "de_connector_pile",
   "label": "Satzanfangs-Konnektoren gehäuft (Somit, Folglich, Dadurch, Gleichzeitig, Zusätzlich)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?<=[.!?:]\\s)(?:Somit|Folglich|Dadurch|Demnach|Infolgedessen|Hierdurch|Hierbei|Dabei|Gleichzeitig|Zusätzlich|Ebenfalls|Ebenso|Nichtsdestotrotz|Nichtsdestoweniger|Überdies|Dennoch|Jedoch|Allerdings|Insbesondere|Entsprechend)"
   ],
   "min": 4
  },
  {
   "key": "de_notonly_variants",
   "label": "Kontrastschablonen (nicht allein … sondern, weniger … als vielmehr, Es geht nicht um … sondern um)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "nicht (?:allein|bloß|lediglich|ausschließlich) [^.?!]{3,80}sondern",
    "weniger [^.?!]{3,60} als vielmehr",
    "(?:Es|Hier|Dabei) geht (?:es )?(?:hier |dabei )?(?:nicht|weniger) (?:nur |bloß |allein |einfach |in erster Linie )?um [^.?!]{3,80}[,;] sondern (?:um|vielmehr|auch)",
    "(?:Das|Dies|Es) (?:ist|war|sind) (?:nicht|kein|keine) [^.?!]{3,60}[,;] sondern (?:ein|eine|das|der|die|vielmehr)"
   ]
  },
  {
   "key": "de_abstract_triad",
   "label": "Abstrakte Dreierreihe (Qualität, Authentizität und Nachhaltigkeit)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "\\p{L}{4,}(?:keit|heit|ung|tät|schaft|ismus), \\p{L}{4,}(?:keit|heit|ung|tät|schaft|ismus),? (?:und|sowie) \\p{L}{4,}(?:keit|heit|ung|tät|schaft|ismus)"
   ]
  },
  {
   "key": "de_von_ueber_bis",
   "label": "„von … über … bis (hin) zu“-Spannweite",
   "severity": "low",
   "kind": "word",
   "alts": [
    "von [^.?!]{3,50} über [^.?!]{3,50} bis (?:hin )?(?:zu|zum|zur)"
   ],
   "min": 2
  },
  {
   "key": "de_sei_es_ob",
   "label": "„sei es … sei es …“ / „ob …, ob …“-Reihung",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "sei es [^.?!]{3,70}(?:,|oder) sei es",
    "Ob [^.?!;]{2,50}, ob [^.?!;]{2,50}",
    "(?:Egal|Ganz gleich),? ob [^.?!]{3,80},? oder"
   ]
  },
  {
   "key": "de_participle_closer",
   "label": "Partizip-/Relativ-Schleppe („…, wodurch … unterstrichen wird“, „…, was … zeigt“)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "[\\p{L}\\p{N}]+,\\s(?:wodurch|womit|wobei)\\s[^.?!]{3,100}(?:unterstrichen|verdeutlicht|hervorgehoben|betont|deutlich gemacht|bekräftigt|untermauert)\\s(?:wird|werden|wurde|wurden)",
    "[\\p{L}\\p{N}]+,\\sdie\\s[^.?!]{3,80}(?:unterstreicht|verdeutlicht|untermauert|bekräftigt)",
    "[\\p{L}\\p{N}]+,\\swas\\s(?:\\p{L}+\\s){0,5}(?:unterstreicht|verdeutlicht|untermauert|bekräftigt|zeigt|belegt|beweist|deutlich macht)",
    "[\\p{L}\\p{N}]+\\s(?:damit|somit|dadurch)\\s(?:\\p{L}+\\s){0,6}(?:unterstreicht|verdeutlicht|untermauert|stärkt|festigt)",
    "[\\p{L}\\p{N}]+,\\s(?:ein|eine)\\s(?:\\p{L}+\\s)?(?:Zeichen|Beleg|Beweis|Signal|Hinweis)\\s(?:dafür|für)"
   ]
  },
  {
   "key": "de_kontext_pile",
   "label": "Behörden-Überleitungen (Vor diesem Hintergrund, In diesem Zusammenhang, Im Hinblick auf)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "Vor diesem Hintergrund",
    "In diesem (?:Zusammenhang|Kontext)",
    "Im Hinblick auf",
    "In Bezug auf",
    "Im Zuge (?:der|des|von)",
    "Im Kontext",
    "Hinsichtlich",
    "Bezüglich",
    "Vor dem Hintergrund",
    "In Anbetracht"
   ],
   "min": 3
  },
  {
   "key": "de_handelt_sich",
   "label": "„Es handelt sich um …“-Definitionssatz",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?:Es|Dabei|Hierbei) handelt (?:es )?sich (?:dabei |hierbei )?um",
    "(?:Bei|bei) (?:dem|der|dieser|diesem) [^.?!]{0,40} handelt es sich um"
   ],
   "min": 2
  },
  {
   "key": "de_hedge",
   "label": "Abschwächer-Häufung (durchaus, gewissermaßen, nicht zuletzt, in der Tat)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "durchaus",
    "gewissermaßen",
    "in gewisser Weise",
    "sozusagen",
    "nicht zuletzt",
    "nicht selten",
    "in der Tat",
    "tatsächlich",
    "letztlich",
    "letztendlich",
    "schlicht(?:weg)?",
    "geradezu",
    "regelrecht"
   ],
   "min": 4
  },
  {
   "key": "de_attribution_monotone",
   "label": "Zitatverben in Dauerschleife (betont, hebt hervor, weist darauf hin, macht deutlich)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "betont(?:e|en)?",
    "hebt hervor",
    "hob hervor",
    "weist darauf hin",
    "wies darauf hin",
    "macht deutlich",
    "machte deutlich",
    "stellt klar",
    "stellte klar",
    "unterstrich"
   ],
   "min": 4
  },
  {
   "key": "de_funktionsverb",
   "label": "Funktionsverbgefüge (zur Anwendung bringen, eine Entscheidung treffen, unter Beweis stellen)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "zur Anwendung (?:bringen|gelangen|kommen)",
    "zum Ausdruck (?:bringen|gebracht|bringt)",
    "unter Beweis (?:stellen|gestellt|stellt)",
    "Berücksichtigung (?:finden|fanden)",
    "(?:eine|die) \\p{L}{4,}ung (?:vornehmen|durchführen)",
    "(?:eine|die) Entscheidung (?:zu )?(?:treffen|getroffen|trifft)",
    "in Betracht (?:ziehen|gezogen|kommen)",
    "in Erscheinung (?:treten|getreten|tritt)",
    "Anwendung finden"
   ],
   "min": 2
  },
  {
   "key": "de_nominalstil",
   "label": "Nominalstil (Durchführung von, Bereitstellung der, Sicherstellung des)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?:Durchführung|Vornahme|Bereitstellung|Inanspruchnahme|Zurverfügungstellung|Sicherstellung|Gewährleistung|Realisierung|Implementierung|Umsetzung) (?:von|der|des|einer|eines)"
   ],
   "min": 3
  },
  {
   "key": "de_anglicism_hard",
   "label": "Anglizismen und Kalken (Game Changer, Must-see, Bucket List, Place to be, Vibes)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Game[- ]?Changer",
    "Must[- ]?(?:Haves?|Sees?|Visits?|Tr(?:y|ies)|Dos?)",
    "Bucket[- ]?List",
    "Hidden Gems?",
    "Place to be",
    "Wow-?Effekt",
    "Vibes?",
    "Mindset",
    "Learnings?",
    "Take-?aways?",
    "Insider-?Tipps?",
    "Geheimtipps?",
    "Gourmet-?Tempel",
    "Foodie-?Paradies"
   ]
  },
  {
   "key": "de_anglicism_soft",
   "label": "Weiche Anglizismen gehäuft (Highlights, Destination, Location, Hotspot, Community)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "Highlights?",
    "Destinations?",
    "Destinationen",
    "Locations?",
    "Hotspots?",
    "Community",
    "Spots?",
    "Experiences?",
    "Feeling"
   ],
   "min": 3
  },
  {
   "key": "de_tradition_moderne",
   "label": "Mischung aus Tradition und Moderne / Alt trifft Neu",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:Mischung|Mix|Verbindung|Verschmelzung|Symbiose|Spagat|Balance|Zusammenspiel|Dialog|Wechselspiel|Hochzeit) (?:aus|von|zwischen) (?:Tradition|Alt|Geschichte|Historie|Vergangenheit)\\p{L}* und",
    "Tradition und Moderne",
    "(?:Tradition|Alt|Moderne|Luxus|Natur|Geschichte|Gestern|Orient) trifft (?:auf )?\\p{L}+",
    "Moderne trifft auf"
   ]
  },
  {
   "key": "de_erlebnis",
   "label": "Unvergessliches Erlebnis / Herzen höherschlagen / für jeden Geschmack",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:ein|eine) (?:\\p{L}+ )?(?:Erlebnis|Erfahrung|Eindruck|Moment|Abend|Geschmackserlebnis),?\\sdas\\s[^.?!]{0,50}(?:vergisst|vergessen|nachhallt|im Gedächtnis|in Erinnerung)",
    "Erlebnisse?,? die(?: man)? (?:nicht |so schnell )?vergess\\p{L}*",
    "unvergessliche\\p{L}* (?:Erlebnis\\p{L}*|Momente?|Eindrücke|Tage|Stunden|Abende|Urlaub)",
    "Erlebnis für alle Sinne",
    "(?:für|auf) (?:alle|sämtliche) Sinne",
    "für Körper,? Geist und Seele",
    "(?:Herzen|das Herz) höher",
    "Herz(?:en)? höher ?schlagen",
    "für jeden (?:Geschmack|Geldbeutel|Anspruch)",
    "etwas für jeden",
    "für jeden etwas",
    "(?:kommt|kommen) (?:\\p{L}+ ){0,2}auf (?:seine|ihre) Kosten"
   ]
  },
  {
   "key": "de_invite",
   "label": "Einladungs-Prosa (lädt zum Verweilen ein, lädt zum Entdecken ein)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "lädt (?:\\p{L}+ ){0,3}zum (?:Verweilen|Entdecken|Bummeln|Träumen|Schlemmen|Genießen|Staunen|Flanieren|Entspannen) ein",
    "laden (?:\\p{L}+ ){0,3}zum (?:Verweilen|Entdecken|Bummeln|Träumen|Schlemmen|Genießen|Staunen|Flanieren|Entspannen) ein",
    "zum Verweilen ein"
   ]
  },
  {
   "key": "de_travel_cliche",
   "label": "Reise-Klischees (Gaumenfreuden, Augenweide, Genuss pur, Entdeckungsreise, Streifzug)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Entdeckungsreise",
    "Streifzug durch",
    "kulinarische(?:n|r|s)? (?:Reise|Highlights?|Genüsse|Höhenflüge|Verführung|Entdeckungsreise)",
    "Gaumenfreuden?",
    "Gaumenschmaus",
    "Augenweide",
    "Augenschmaus",
    "Genuss pur",
    "Dolce Vita",
    "Savoir-?vivre",
    "Joie de vivre",
    "Balsam für die Seele",
    "Seelenbalsam",
    "(?:herzliche|legendäre|gelebte|sprichwörtliche) Gastfreundschaft"
   ]
  },
  {
   "key": "de_flair",
   "label": "Lebensgefühl-Vokabular (mediterranes Flair, Hauch von, südländisch, Lebensfreude)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "mediterran\\p{L}* (?:Flair|Lebensgefühl|Lebensart|Charme|Leichtigkeit|Lebensfreude)",
    "Lebensgefühl",
    "Hauch von",
    "ein Hauch",
    "südländisch\\p{L}*",
    "Mittelmeer-?Flair",
    "Lebensfreude",
    "Seele baumeln"
   ],
   "min": 2
  },
  {
   "key": "de_nestled",
   "label": "Lageprosa (eingebettet in, liegt malerisch, schmiegt sich, thront)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "eingebettet in",
    "(?:liegt|liegen|gelegen) (?:malerisch|idyllisch|versteckt|eingebettet|geschützt)",
    "(?:schmiegt|schmiegen) sich",
    "thront (?:über|auf|oberhalb)",
    "inmitten (?:von |der |des |einer |eines )?[^.?!]{0,30}(?:Olivenhain|Zitronenhain|Natur|Pinien|Weinberg|Berg)"
   ]
  },
  {
   "key": "de_superl",
   "label": "Stereotype Superlative (eine der schönsten / gilt als eine der beliebtesten)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?:eine|einer|eines) der (?:schönsten|beliebtesten|besten|angesagtesten|bekanntesten|spannendsten|aufregendsten|exklusivsten|renommiertesten|berühmtesten|begehrtesten|bedeutendsten|wichtigsten|attraktivsten|meistbesuchten)",
    "gilt (?:\\p{L}+ )?als (?:die|der|das|ein|eine|einer) (?:\\p{L}+ )?(?:beliebtesten|schönsten|besten|bekanntesten|angesagtesten|begehrtesten|exklusivsten|spannendsten)"
   ],
   "min": 3
  },
  {
   "key": "de_cy_aphrodite",
   "label": "Zypern-Klischee (Insel der Aphrodite, Perle des Mittelmeers, Sonneninsel)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Insel der Aphrodite",
    "Aphrodites? Insel",
    "(?:Geburtsstätte|Geburtsort|Heimat) der (?:Liebesgöttin|Aphrodite)",
    "Insel der (?:Götter|Liebe|Liebesgöttin|Sonne)",
    "Perle (?:des|im) Mittelmeers?",
    "Juwel (?:im|des|am) Mittelmeer",
    "Mittelmeer-?(?:Perle|Juwel)",
    "Sonneninsel"
   ]
  },
  {
   "key": "de_cy_crossroads",
   "label": "Zypern-Klischee (Schnittstelle Ost/West, Tor zum Nahen Osten, Schmelztiegel der Kulturen)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Schnittstelle (?:zwischen|von) (?:Ost und West|Europa,? Asien|Orient)",
    "Brücke zwischen (?:Ost und West|Europa und (?:Asien|dem Nahen Osten))",
    "Tor zum (?:Nahen )?Osten",
    "Kreuzung(?:spunkt)? (?:der|von) (?:Kulturen|Kontinenten|Zivilisationen)",
    "Schmelztiegel der Kulturen",
    "Drehscheibe zwischen",
    "Wiege der (?:Zivilisation|Aphrodite)"
   ]
  },
  {
   "key": "de_cy_water",
   "label": "Zypern-Klischee (türkisfarbenes Wasser, goldene Strände, 300 Sonnentage)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "türkis\\p{L}*",
    "kristallklar\\p{L}*",
    "azurblau\\p{L}*",
    "smaragdgrün\\p{L}*",
    "glasklar\\p{L}*",
    "goldene[nrms]? Strände?",
    "Strände wie aus dem Bilderbuch",
    "feinsandig\\p{L}*",
    "weißen? Sandstrände?",
    "sonnenverwöhnt\\p{L}*",
    "(?:über |mehr als )?300 Sonnentage"
   ],
   "min": 2
  },
  {
   "key": "de_cy_strategic",
   "label": "Standort-Floskel (strategisch günstige Lage, Drehscheibe, Sprungbrett)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "strategisch (?:günstig\\p{L}*|gelegen\\p{L}*|vorteilhaft\\p{L}*|bedeutsam\\p{L}*|wichtig\\p{L}*)",
    "geostrategisch\\p{L}*",
    "günstig(?:e|er|en)? (?:geografische |geographische )?Lage",
    "Sprungbrett",
    "Drehscheibe"
   ]
  },
  {
   "key": "de_estate_lage",
   "label": "Makler-Register (Lage, Lage, Lage; Immobilie mit Potenzial; Traumimmobilie)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "Lage,? Lage,? Lage",
    "Immobilie mit Potenzial",
    "Objekt mit Potenzial",
    "(?:Haus|Villa|Wohnung|Immobilie) mit (?:viel |enormem |großem )?(?:Potenzial|Charme|Persönlichkeit)",
    "Wohntraum",
    "Traum(?:haus|villa|immobilie|wohnung|grundstück)",
    "Traumlage",
    "Rendite(?:perle|garantie|träume)",
    "krisensicher\\p{L}*",
    "sichere[nr]? Hafen",
    "Anlageobjekt",
    "Kapitalanlage mit Zukunft",
    "Wertsteigerungspotenzial",
    "zum Verlieben"
   ]
  },
  {
   "key": "de_estate_adj",
   "label": "Exposé-Adjektive gehäuft (exklusiv, luxuriös, hochwertig, großzügig, Liebe zum Detail)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "exklusiv\\p{L}*",
    "luxuriös\\p{L}*",
    "hochwertig\\p{L}*",
    "großzügig\\p{L}*",
    "stilvoll\\p{L}*",
    "gehoben\\p{L}*",
    "lukrativ\\p{L}*",
    "repräsentativ\\p{L}*",
    "Liebe zum Detail",
    "mit viel Liebe",
    "Wohlfühl\\p{L}*",
    "Rückzugsort",
    "Refugium"
   ],
   "min": 4
  },
  {
   "key": "de_pr_announce",
   "label": "Pressemitteilungs-Ton (stolz zu verkünden, freut sich bekannt zu geben, voller Freude)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:stolz|erfreut|begeistert) (?:darauf )?(?:zu )?(?:verkünden|präsentieren|ankündigen|bekannt zu geben|mitteilen)",
    "freut sich,? (?:\\p{L}+ )?(?:zu )?(?:verkünden|bekannt zu geben|ankündigen|mitteilen|präsentieren)",
    "(?:mit großer|voller) Freude",
    "(?:wir|man) freue[n]? (?:uns|sich) (?:sehr )?(?:auf|über)"
   ]
  },
  {
   "key": "de_pr_buzz",
   "label": "Marketing-Buzzwords (Meilenstein, Mehrwert, Synergien, innovativ, zukunftsweisend)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "Meilenstein\\p{L}*",
    "wegweisend\\p{L}*",
    "bahnbrechend\\p{L}*",
    "Synergien?",
    "Alleinstellungsmerkmal\\p{L}*",
    "Mehrwert",
    "innovativ\\p{L}*",
    "zukunftsweisend\\p{L}*",
    "maßgeschneidert\\p{L}*",
    "Best-?in-?Class",
    "Weltklasse"
   ],
   "min": 2
  },
  {
   "key": "de_biz_floskel",
   "label": "Standort-/Anlage-Jargon (attraktiver Standort, Wachstumsmotor, Standortvorteile)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "attraktive[nrsm]? (?:Standort|Investitionsstandort|Rendite|Anlageoption|Anlagemöglichkeit|Markt)",
    "Wachstumsmotor",
    "Wachstumsmarkt",
    "Standortvorteile?",
    "Investitionsklima",
    "Investoren aus aller Welt"
   ],
   "min": 2
  },
  {
   "key": "de_legal_disclaimer",
   "label": "Pauschaler Rechtstipp (Konsultieren Sie einen Anwalt, ersetzt keine Rechtsberatung)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?:stellt|ersetzt) keine (?:Rechts|Steuer|Anlage)beratung",
    "(?:sollten|sollte|empfiehlt es sich) (?:Sie )?[^.?!]{0,40}(?:Anwalt|Rechtsanwalt|Steuerberater|Fachmann)[^.?!]{0,30}(?:konsultieren|hinzuziehen|wenden|befragen|beraten)",
    "unbedingt (?:einen )?(?:Anwalt|Fachmann|Steuerberater)",
    "stets (?:einen )?(?:Anwalt|Fachmann|Steuerberater)"
   ]
  },
  {
   "key": "de_vague_expert",
   "label": "Anonyme Gewährsleute (Experten sagen, Studien zeigen, Es heißt, dass)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:Experten|Fachleute|Branchenkenner|Beobachter|Insider|Kenner|Marktbeobachter|Wissenschaftler|Forscher|Ökonomen|Juristen)\\s(?:\\p{L}+\\s){0,2}(?:sagen|sind sich einig|schätzen|warnen|gehen davon aus|betonen|erwarten|raten|meinen|vermuten|glauben)",
    "laut (?:Experten|Fachleuten|Branchenkennern|Beobachtern|Insidern)",
    "(?:Viele|Manche|Einige|Zahlreiche|Etliche) (?:Experten|Fachleute|Beobachter|Kritiker|Anwohner|Bewohner|Einheimische|Kenner)",
    "Studien (?:zeigen|belegen|legen nahe|deuten|haben gezeigt)",
    "(?:Untersuchungen|Umfragen|Analysen|Erhebungen) (?:zeigen|belegen|legen nahe|deuten)",
    "wie (?:Studien|Experten|Untersuchungen) (?:zeigen|belegen|bestätigen)",
    "Es heißt,? dass",
    "Man sagt,? dass",
    "wird (?:oft|häufig|allgemein|gemeinhin) (?:gesagt|angenommen|vermutet|behauptet)"
   ]
  },
  {
   "key": "de_quote_english",
   "label": "Englische Anführungszeichen statt „…“ oder »…«",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\"[\\p{L}\\p{N}][^\"\\n]{2,200}\"",
    "“[^”“„\\n]{2,200}”"
   ]
  },
  {
   "key": "de_dash_hyphen",
   "label": "Bindestrich statt Gedankenstrich ( - statt – )",
   "severity": "low",
   "kind": "word",
   "alts": [
    "-(?=\\s)",
    "--"
   ],
   "min": 2
  },
  {
   "key": "de_num_english",
   "label": "Englisches Zahlenformat (1,200 Euro statt 1.200 Euro; 35000 Euro ohne Punkt)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\d{1,3}(?:,\\d{3})+\\s?(?:€|EUR|Euro|Quadratmeter|m²|Einwohner|Besucher|Gäste|Zimmer|Wohnungen)",
    "\\d{5,}\\s?(?:€|Euro)"
   ]
  },
  {
   "key": "de_num_currency_prefix",
   "label": "Währungszeichen vor der Zahl (€1.200, $5) statt 1.200 €",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "€\\s?\\d[\\d.,]*",
    "\\$\\s?\\d[\\d.,]*",
    "(?:EUR|USD|GBP)\\s\\d[\\d.,]*",
    "£\\s?\\d[\\d.,]*"
   ]
  },
  {
   "key": "de_date_format",
   "label": "Datumsformat nicht deutsch (October 5, 2026 / 5 Oktober / 05.10.2026 / ISO)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember),? \\d{1,2}(?:,|\\s|$)(?!\\d)",
    "\\d{1,2} (?:Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember)",
    "\\d{1,2}/\\d{1,2}/\\d{2,4}",
    "\\d{4}-\\d{2}-\\d{2}",
    "\\d{1,2}(?:st|nd|rd|th)",
    "0\\d\\.\\s?\\d{1,2}\\.\\s?\\d{4}"
   ]
  },
  {
   "key": "de_decimal_point",
   "label": "Dezimalpunkt statt Dezimalkomma (3.5 Prozent)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "\\d{1,2}\\.\\d{1,2}\\s?(?:Prozent|%|Grad|°C|Kilometer|km|Meter|Millionen|Milliarden|Mio|Mrd)"
   ]
  },
  {
   "key": "de_emoji",
   "label": "Emoji im redaktionellen Text",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "[\\p{L}\\p{N}]*[\\u{1F300}-\\u{1FAFF}\\u{2600}-\\u{27BF}\\u{2B50}\\u{2705}\\u{274C}]"
   ]
  },
  {
   "key": "de_markdown",
   "label": "Markdown-Reste (**fett**, # Überschrift, Aufzählung mit fettem Lead-in)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\*\\*[^*\\n]{2,80}\\*\\*",
    "__[^_\\n]{2,80}__"
   ]
  },
  {
   "key": "de_markdown_start",
   "label": "Markdown-Struktur am Zeilenanfang (#, - **, 1. **)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "#{1,6}(?=\\s)",
    "[-*•]\\s+\\*\\*",
    "\\d+\\.\\s+\\*\\*",
    ">(?=\\s)"
   ]
  },
  {
   "key": "de_du_register",
   "label": "du/ihr-Ansprache (Sie/du-Konsistenz brechen)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "du",
    "dich",
    "dir",
    "dein(?:e|en|em|er|es)?",
    "euch",
    "eure[nrms]?"
   ],
   "min": 2
  },
  {
   "key": "de_leak_chat",
   "label": "Chatbot-Einstieg („Natürlich! Hier ist …“, „Gerne überarbeite ich …“)",
   "severity": "high",
   "kind": "start",
   "alts": [
    "Hier (?:ist|sind) (?:der|die|das|ein|eine|einige|Ihr|Ihre|dein|deine|meine|der überarbeitete)",
    "(?:Natürlich|Gerne|Selbstverständlich|Klar|Sicher|Absolut|Kein Problem|Gern geschehen)(?=[!,.:])",
    "Gerne (?:helfe|überarbeite|schreibe|passe)",
    "Ich habe (?:den|die|das) (?:Text|Artikel|Beitrag)",
    "Ich werde (?:den|die|das) (?:Text|Artikel|Beitrag)"
   ]
  },
  {
   "key": "de_leak_offer",
   "label": "Chatbot-Schluss / Wissensgrenze („Soll ich …?“, „Bei Fragen …“, „Stand meines Wissens“)",
   "severity": "high",
   "kind": "word",
   "alts": [
    "Soll ich (?:den|die|das|Ihnen|dir)",
    "Möchten Sie,? dass ich",
    "Lass(?:en Sie)? mich wissen",
    "Wenn Sie (?:möchten|wünschen),? (?:kann|passe|erweitere|schreibe) ich",
    "Falls Sie weitere (?:Fragen|Änderungen|Wünsche)",
    "Ich stehe (?:Ihnen )?(?:gerne )?zur Verfügung",
    "Stand meines (?:Wissens|Trainings)",
    "meine(?:r|n)? Trainingsdaten",
    "Wissensstand",
    "Ich habe keinen Zugriff",
    "Ich kann (?:keine|nicht) [^.?!]{0,40}(?:in Echtzeit|verifizieren|überprüfen)"
   ]
  },
  {
   "key": "de_leak_placeholder",
   "label": "Platzhalter in eckigen Klammern ([Name], [Datum einfügen])",
   "severity": "high",
   "kind": "word",
   "alts": [
    "\\[(?:Name|Datum|Ort|Quelle|Einfügen|Platzhalter|Link|Zitat|Bild|Preis|Zahl)[^\\]]{0,40}\\]",
    "\\[(?:hier|insert|INSERT)[^\\]]{0,40}\\]"
   ]
  },
  {
   "key": "de_leak_translator",
   "label": "Übersetzer-/Metahinweis („Anmerkung des Übersetzers“, „Hinweis: Dieser Text …“)",
   "severity": "high",
   "kind": "word",
   "alts": [
    "Anmerkung des Übersetzers",
    "Übersetzt von",
    "Hinweis:? (?:Dieser|Der) (?:Text|Artikel|Beitrag)",
    "(?:Dieser|Der) (?:Text|Artikel) wurde (?:mit|von|durch) (?:KI|ChatGPT|Claude|einer künstlichen)",
    "als (?:Large )?Language[- ]Model",
    "KI-(?:generiert|Assistent)\\p{L}*"
   ]
  }
 ],
 "banned": [
  "Es ist wichtig zu beachten",
  "Es sei darauf hingewiesen",
  "Es ist erwähnenswert",
  "spielt eine entscheidende Rolle",
  "spielt eine Schlüsselrolle",
  "ein Zeugnis von / für",
  "legt Zeugnis ab",
  "unterstreicht die Bedeutung",
  "wirft ein Licht auf",
  "verdeutlicht eindrucksvoll",
  "zeugt von",
  "steht sinnbildlich für",
  "im Herzen von",
  "eingebettet in",
  "liegt malerisch",
  "Tauchen Sie ein",
  "Entdecken Sie",
  "Erleben Sie",
  "Ob Sie … oder …",
  "Egal ob",
  "Suchen Sie nicht weiter",
  "in der heutigen schnelllebigen Welt",
  "in einer Welt, in der",
  "Heutzutage",
  "Es ist kein Geheimnis, dass",
  "Wer kennt das nicht",
  "für Jung und Alt",
  "für jeden Geschmack",
  "kommt auf seine Kosten",
  "lässt Herzen höherschlagen",
  "ein Fest für die Sinne",
  "verborgene Perle",
  "versteckte Perle",
  "ein Muss",
  "Must-see",
  "Game Changer",
  "Mischung aus Tradition und Moderne",
  "Tradition trifft Moderne",
  "Schmelztiegel der Kulturen",
  "reiche Geschichte",
  "reiches Erbe",
  "facettenreich",
  "vielschichtig",
  "atemberaubend",
  "malerisch",
  "pulsierend",
  "unvergesslich",
  "einzigartig",
  "unvergleichlich",
  "faszinierend",
  "beeindruckend",
  "bemerkenswert",
  "nahtlos",
  "ganzheitlich",
  "maßgeblich",
  "Herzstück",
  "Dreh- und Angelpunkt",
  "Rückgrat",
  "Meilenstein",
  "Mehrwert",
  "Insel der Aphrodite",
  "türkisfarbenes Wasser",
  "goldene Strände",
  "strategisch günstige Lage",
  "Schnittstelle zwischen Ost und West",
  "Perle des Mittelmeers",
  "Immobilie mit Potenzial",
  "Lage, Lage, Lage",
  "Traumimmobilie",
  "krisensichere Kapitalanlage",
  "stolz verkünden",
  "Experten sagen",
  "Fachleute sind sich einig",
  "Studien zeigen",
  "Darüber hinaus (als Satzanfang)",
  "Des Weiteren",
  "Zudem (als Satzanfang)",
  "Außerdem (als Satzanfang)",
  "Fazit",
  "Zusammenfassend lässt sich sagen",
  "Abschließend",
  "Alles in allem",
  "Am Ende des Tages",
  "Unterm Strich",
  "Die Zeit wird zeigen",
  "Es bleibt spannend",
  "„…, wodurch … unterstrichen wird“",
  "zur Anwendung bringen",
  "eine Entscheidung treffen (statt entscheiden)",
  "im Rahmen von",
  "„stellt … dar“ (statt ist)",
  "wird angeboten",
  "nicht nur … sondern auch",
  "mehr als nur",
  "Als KI-Sprachmodell",
  "Ich hoffe, das hilft",
  "Hier ist (als Antwortbeginn)"
 ],
 "closers": [
  "Fazit:",
  "Zusammenfassend",
  "Zusammenfassend lässt sich sagen",
  "Abschließend",
  "Abschließend lässt sich sagen",
  "Alles in allem",
  "Unterm Strich",
  "Letztlich",
  "Letztendlich",
  "Insgesamt",
  "Kurz gesagt",
  "Im Ergebnis",
  "Schlussendlich",
  "Festzuhalten bleibt",
  "Man kann also sagen",
  "Eines ist klar",
  "Am Ende des Tages",
  "Die Zeit wird zeigen",
  "Bleibt abzuwarten",
  "Zum Abschluss",
  "Als Fazit lässt sich festhalten",
  "Insgesamt zeigt sich",
  "Es bleibt spannend",
  "Fest steht",
  "Letzten Endes",
  "Kurzum"
 ],
 "openers": [
  "Es ist wichtig zu beachten, dass",
  "Es sei darauf hingewiesen, dass",
  "Vorab sei gesagt",
  "Zunächst einmal",
  "Tauchen Sie ein in",
  "Entdecken Sie",
  "Erleben Sie",
  "Stellen Sie sich vor:",
  "Willkommen in",
  "In der heutigen schnelllebigen Welt",
  "In einer Welt, in der",
  "Heutzutage",
  "Seit jeher",
  "Ob Sie … oder …",
  "Egal ob",
  "Haben Sie sich schon einmal gefragt",
  "Wer kennt das nicht",
  "Lassen Sie uns einen Blick werfen auf",
  "Werfen wir einen Blick auf",
  "Im Folgenden",
  "In diesem Artikel",
  "Hier erfahren Sie",
  "Alles, was Sie wissen müssen",
  "Das Wichtigste in Kürze",
  "Es ist kein Geheimnis, dass",
  "Wenn es um … geht",
  "Kaum ein Ort verkörpert so sehr",
  "Die Antwort liegt auf der Hand"
 ],
 "sheet": [
  "Open news with the verifiable event: who did what, where and when, in one sentence of at most 25 words, subject and finite verb early. Put the source, the day and the figure in the first two sentences; save background and context for paragraph three or later.",
  "Use the Satzklammer deliberately: finite verb in second position, the rest of the verb group at the end. Do not let the bracket swallow more than about 12 words; when a clause gets heavy, split it or move the load behind the verb as a Nachfeld (“…hat der Rat beschlossen, nachdem…”).",
  "Vary the first position of the sentence. Not every sentence starts with the subject: alternate with a place, a time, an object or a subordinate clause, but never three sentences in a row with the same first word.",
  "Mix Verbzweit main clauses with the occasional Verbletzt subordinate clause, a short elliptical sentence and a question only where the reader would really ask it. A sentence of five words after one of thirty is a feature, not an error.",
  "Choose a verb over a noun construction: “Die Regierung prüft”, not “führt eine Prüfung durch”; “entscheiden” not “eine Entscheidung treffen”; “anwenden” not “zur Anwendung bringen”; “kosten” not “sich auf … belaufen” unless the rhythm needs it.",
  "Avoid Nominalstil, stacked genitives and the passive with “wird … durchgeführt/vorgenommen/angeboten”. Name the actor. Keep Passiv only where the actor is unknown or irrelevant.",
  "Rotate speech verbs by meaning, not by decoration: sagte, erklärte, sagt, betonte, räumte ein, hielt fest, entgegnete, warnte, fügte hinzu, ergänzte, wies zurück, so der Minister. “Sagte” is the default; use “betonte” at most once per article.",
  "Use Konjunktiv I for indirect speech in news (“Er sagte, die Behörde habe die Frist verlängert”); use Konjunktiv II or the indicative when Konjunktiv I would be identical to the indicative. Direct quotes carry opinion and colour; paraphrase carries facts.",
  "Quote only what is worth quoting: a concrete, odd or revealing sentence. Never use a quote to state something dull (“Das ist wichtig für die Insel”). Introduce the speaker with name, role and organisation at first mention.",
  "Attribute every claim that is not common knowledge to a named person, document or institution (“laut Statistikamt”, “heißt es im Bericht der Zentralbank”). No “Experten sagen”, “Studien zeigen”, “es heißt”; if the source cannot be named, say what kind of source it is and why it is anonymous.",
  "Typography: German quotation marks „…“ for quotes, ‚…‘ for a quote inside a quote, »…« only if the house style is French-inward; never straight \"…\" or English “…”. Apostrophes in genitive names only where Duden allows (no “Paphos’ Altstadt” in running text).",
  "Dashes: use the spaced en dash “ – ” as Gedankenstrich, the unspaced en dash for ranges (10–15 Uhr, Seite 5–7), the hyphen only inside compounds. No em dash, no spaced hyphen, and no more than two Gedankenstriche per paragraph.",
  "Numbers: thousands separated with a full stop or thin space (1.200 Euro, 350.000 Euro), decimal comma (3,5 Prozent), currency after the figure (1.200 €, 1,2 Millionen Euro), “Prozent” spelled out in running text, figures from 13 up, numbers up to twelve written out unless a unit follows. Always say “Euro” for Cyprus prices; give a conversion only if the source currency is not euro.",
  "Dates and times: “5. Oktober 2026”, “am Dienstag”, “Mitte Oktober”; times as “18.30 Uhr”; ranges as “von 10 bis 15 Uhr”. Never “5 Oktober”, “October 5”, ISO dates or “5th”. Use relative days only when the publication date makes them unambiguous.",
  "Capitalisation: all nouns and nominalised verbs capitalised (das Essen, beim Wandern); formal “Sie/Ihnen/Ihr” capitalised when the reader is addressed, lower-case sie/ihnen for third person; headings in sentence case (“Wie Zypern seine Wasserkrise bekämpft”), never English Title Case (“Wie Zypern Seine Wasserkrise Bekämpft”).",
  "Register of address: choose Sie or du once and hold it from headline to caption. Default for the luxury edition is no direct address at all; if the reader is addressed (guides, relocation), it is always the formal Sie, never du, never man/Sie hybrids within one paragraph.",
  "German place names and exonyms: Nikosia, Larnaka, Paphos, Limassol (Lemesos only as a second reference), Famagusta, Kyrenia (Girne only in the northern context), Troodos-Gebirge, Akamas-Halbinsel. Keep Cypriot institutions with a short German gloss at first mention: Repräsentantenhaus, Zentralbank von Zypern, Grundbuchamt (Department of Lands and Surveys).",
  "Cut connector stacks. One “außerdem/zudem/darüber hinaus/des Weiteren” per article is enough; usually the logic is carried by order, a colon or a hard “Aber”. Do not open consecutive paragraphs with a connector, and do not start every paragraph with “Jedoch”.",
  "Do not close with a Fazit, a moral or a look into the future. End on the last concrete fact, a quote, an image or an open date (“Die Entscheidung fällt im November.”). A German reader trusts a story that stops when it is finished.",
  "No enumeration scaffolding in prose: no “Erstens … Zweitens … Drittens”, no “Die wichtigsten Punkte”, no “Dazu gehören”. Use a real list or a table only in service pieces (relocation, property, law) and then keep items parallel and concrete.",
  "Break the tricolon habit. Two or four items are as good as three; never three abstract nouns in a row (“Qualität, Authentizität und Nachhaltigkeit”); avoid “nicht nur … sondern auch” and “mehr als nur” altogether in a piece.",
  "Prefer one precise noun to a pile of adjectives. Allow at most one evaluative adjective per sentence and none that a tourist board could print. Replace “malerisch, atemberaubend, einzigartig” by what the eye finds: the street, the colour, the price, the smell.",
  "Replace Anglicisms with the German word wherever one exists and sounds natural: Veranstaltung not Event, Treffpunkt not Hotspot, Geheimtipp only ironically, Rangliste not Ranking, Vorhaben not Projekt (when vague). Keep English only for names and terms of art (Golden Visa, Non-Dom, Hub) and gloss them once.",
  "Avoid calques from English: no “am Ende des Tages”, “einen Unterschied machen” (instead: etwas bewirken), “Sinn machen” (instead: sinnvoll sein), “in 2026” (instead: 2026 or im Jahr 2026), “Sie können erwarten” (instead: Es erwartet Sie / man findet), “eine Reihe von” as filler.",
  "Do not use “stellt … dar”, “fungiert als”, “dient als” where “ist” will do. One plain “ist” beats a decorated copula.",
  "Specificity over significance: instead of saying that something “unterstreicht die Bedeutung”, give the number, the name, the date or the price that makes it important. Every paragraph needs at least one concrete detail a reader could check.",
  "Estate-agent and press-release language is banned in editorial text. Describe the property as a surveyor would (Baujahr, Wohnfläche in Quadratmetern, Grundstück, Zustand, Preis, Gebühren) and name the downsides. Never “Immobilie mit Potenzial”, “Lage, Lage, Lage”, “Traumhaus”.",
  "Legal and tax explainers: state the rule, the source (Gesetz, Verordnung, Datum), who it affects, the deadline and the cost; add the exception in the next sentence. Close with the practical step or the open question, not with “Konsultieren Sie einen Anwalt”. Hedge with “nach derzeitiger Rechtslage”, once, where it matters.",
  "Cyprus clichés are banned unless the piece is about the cliché itself: Insel der Aphrodite, türkisfarbenes Wasser, strategisch günstige Lage, 300 Sonnentage, Schnittstelle zwischen Ost und West. Find the angle the guidebook does not carry: a named person, a street, a price, a season.",
  "Mind the DACH reader: use Euro and metric units, explain Cypriot terms once, and note differences from German, Austrian or Swiss practice where it changes a decision (Grunderwerbsteuer vs. Transfer Fees, Wohnsitz, Krankenversicherung, Doppelbesteuerungsabkommen). Use “Rathaus”, “Finanzamt”, “Notar” analogies sparingly and accurately.",
  "Never write meta-talk or chatbot residue: no “Hier ist der Artikel”, “Ich hoffe, das hilft”, “Als KI”, no emoji, no Markdown asterisks or hash marks, no square-bracket placeholders. The text must read as printed copy.",
  "Rhythm check before filing: read aloud; if three consecutive sentences have similar length, rebuild one into a fragment and merge two others; if two paragraphs have the same length, cut or extend one; if the piece ends on a sentence that could end any other piece, delete it."
 ],
 "pairs": [
  {
   "bad": "Zypern ist ein Land, das Tradition und Moderne auf einzigartige Weise vereint und Besuchern ein unvergessliches Erlebnis bietet.",
   "good": "In Lakatamia, einem Vorort von Nikosia, steht zwischen zwei Autowerkstätten eine Weberei, die seit 1962 Leinen für Kirchen und Kreuzfahrtschiffe liefert.",
   "why": "Brochure sentence with no checkable fact replaced by a named place, a date and a product."
  },
  {
   "bad": "Es ist wichtig zu beachten, dass beim Kauf einer Neubauimmobilie Mehrwertsteuer anfällt.",
   "good": "Auf Neubauten fallen 19 Prozent Mehrwertsteuer an; für die erste selbst genutzte Wohnung gilt unter Auflagen ein ermäßigter Satz von 5 Prozent.",
   "why": "Throat-clearing opener removed; the sentence delivers the rule, the number and the exception."
  },
  {
   "bad": "Die Regierung kündigte neue Abgaben an, wodurch die Bedeutung der Haushaltskonsolidierung unterstrichen wird.",
   "good": "Die Regierung will Tabak und Alkohol höher besteuern. Der Finanzminister begründete das mit dem Ziel, im kommenden Jahr kein Defizit auszuweisen.",
   "why": "Participle tail that only comments is replaced by a second fact and a named speaker."
  },
  {
   "bad": "Experten sagen, dass der Immobilienmarkt weiter wachsen wird.",
   "good": "Die Maklervereinigung erwartet für 2027 ein Plus von vier bis sechs Prozent, sagte ihr Vorsitzender am Montag in Limassol.",
   "why": "Vague attribution replaced by a named source, a figure, a day and a place."
  },
  {
   "bad": "Zusammenfassend lässt sich sagen, dass Paphos eine Vielzahl an Möglichkeiten bietet, die für jeden etwas bereithalten.",
   "good": "Wer im Februar kommt, hat Paphos fast für sich; ab Ostern gehört die Promenade den Reisegruppen.",
   "why": "Summary closer and “für jeden etwas” cut; the ending is a concrete, slightly wry observation."
  },
  {
   "bad": "Die Wohnung kostet \"nur\" €350,000, sagt der Makler, und ist \"ein wahrer Traum\".",
   "good": "Die Wohnung kostet 350.000 Euro. „Ein Traum“, sagt der Makler – aber die Tiefgarage kostet 18.000 Euro extra.",
   "why": "Fixes quotes („…“), currency after the figure, thousands with a full stop, spaced en dash; adds the downside."
  },
  {
   "bad": "Die Durchführung der Überprüfung der eingereichten Unterlagen erfolgt durch das Grundbuchamt.",
   "good": "Das Grundbuchamt prüft die eingereichten Unterlagen.",
   "why": "Nominalstil and stacked genitives collapsed into subject and verb."
  },
  {
   "bad": "Diese Immobilie mit Potenzial überzeugt durch ihre exklusive Lage und hochwertige Ausstattung und lässt keine Wünsche offen.",
   "good": "Das Haus in Kato Paphos hat drei Schlafzimmer, ein undichtes Dach und Meerblick über den Hafen. Der Preis: 410.000 Euro, Sanierung nicht eingerechnet.",
   "why": "Estate-agent formula replaced by survey facts, a flaw and a price."
  },
  {
   "bad": "Tauchen Sie ein in die verborgene Perle der Altstadt von Limassol und entdecken Sie ein Fest für die Sinne!",
   "good": "Die Altstadt von Limassol beginnt hinter dem Hafen und ist nach zehn Minuten durchquert. Interessant wird sie erst in den Seitengassen rund um die Agiou-Andreou-Straße.",
   "why": "Imperative and hidden-gem cliché replaced by a measured, observational description in the third person."
  },
  {
   "bad": "Darüber hinaus betonte der Minister die Wichtigkeit der Reform. Zudem betonte er die Rolle der Banken. Außerdem betonte er, dass die Zeit dränge.",
   "good": "Die Reform sei überfällig, sagte der Minister. Die Banken müssten mitziehen, ergänzte er, und warnte: „Wir haben keine zwei Jahre mehr.“",
   "why": "Connector stack and one speech verb repeated; replaced by varied verbs, Konjunktiv I and one real quote."
  }
 ],
 "desks": {
  "news": "Verifiable event first, in the second-position verb, with the source and the day in the lead; Konjunktiv I for what officials say; “sagte” as default verb; background only after the second paragraph; no adjectives that judge. End on the next date or open question, never a moral.",
  "business": "FAZ/Handelsblatt tone: figure, company, comparison (Vorjahr, Branche) in the lead, then the reason, then the risk. Name the executive or analyst with institution; use Konjunktiv I for forecasts attributed to others; keep numbers in German format and avoid “Wachstumsmotor”, “Mehrwert”, “Synergien”.",
  "property_legal": "NZZ-style explainer: rule, legal source (Gesetz, Verordnung, Datum), who is affected, cost and deadline, exception. Describe properties like a surveyor (Baujahr, Fläche, Zustand, Grundbuchstatus, Gebühren) and name the downsides; no estate-agent adjectives and no blanket “Fragen Sie einen Anwalt”.",
  "relocation_guide": "Service journalism in the formal Sie or, better, impersonal constructions; order by what the reader must do first (Aufenthaltstitel, Steuer, Krankenversicherung, Konto). Give costs in Euro, offices by name, processing times in weeks, and compare briefly with German/Austrian/Swiss practice where a decision depends on it.",
  "economy": "Lead with the data point and its source (Statistikamt, Zentralbank, Eurostat), compare with the previous period and the euro-zone average, then explain the cause in plain verbs. Avoid jargon stacks (“Rahmenbedingungen”, “Investitionsklima”); one chart-worthy number per paragraph is enough.",
  "culture": "Zeit/FAZ feuilleton register: a concrete scene, object or sentence first; argue with the work, name the artist, date, venue, medium and size. Allow one considered judgement per piece and support it; avoid “unterstreicht”, “facettenreich”, “eindrucksvoll” and festival-speak.",
  "food": "Write like a Süddeutsche Magazin food column: the dish, its ingredients and where they come from, the cook by name, the price. Use sensory verbs sparingly and exactly; ban “Gaumenfreuden”, “kulinarische Reise”, “Genuss pur”. Give the address, opening day and cost of a main course.",
  "fashion_lifestyle": "Vogue Germany voice: precise materials, cuts, designers, price and where to buy; one dry remark rather than superlatives. Avoid English fashion jargon where German exists, no emoji, no “Must-have”; keep “Sie” out of the text and let the observation do the persuading.",
  "travel": "Architectural Digest/NZZ-Reisen: a person, a street, a season and a price rather than “malerisch” and “türkisfarben”. Give practical details (Anreise, Dauer, Preis, beste Monate) in a short service block; acknowledge crowds, heat and downsides. Cut every Cyprus cliché from the brief.",
  "events": "Service first: what, when (5. Oktober 2026, 18.30 Uhr), where (street and town), cost, how to book. Then one paragraph of context with a named organiser or performer. Short, factual, no exclamation marks, no “Erleben Sie”, “Verpassen Sie nicht”.",
  "interview": "Open with a scene or the sharpest statement, then who and why now. Keep the questions short and real; render answers in the person’s own cadence; use „…“ for quotes and Konjunktiv I only in the narrative parts. Introduce with name, role, age only if relevant; end on an answer, not a summary.",
  "review": "Say what it is, what it costs and whether it is worth it in the first paragraph; justify the verdict with three concrete observations and one reservation. Compare with a named alternative. No “ein Muss”, no star-inflation language, no recap of the press release.",
  "people": "Portrait in the manner of SZ Magazin: one revealing scene or habit first, then the biography in order of significance, not chronology. Include a detail the subject would not choose to publish (a doubt, a failure); use attribution verbs with variety and avoid hagiographic adjectives."
 }
};

export default data;
