// GENERATED by scripts/voice/build-data.mjs from the EN linguist source. Edit the source data and regenerate; do not hand-edit.
import type { LangVoiceData } from '@/lib/voice/types';

const data: LangVoiceData = {
 "lang": "en",
 "tells": [
  {
   "key": "en_leak_fence",
   "label": "Markdown code fence left in the text",
   "severity": "high",
   "kind": "word",
   "alts": [
    "\\x60{3}",
    "~{3}\\p{L}*"
   ]
  },
  {
   "key": "en_leak_offer",
   "label": "Chatbot sign-off (I hope this helps, feel free to, let me know)",
   "severity": "high",
   "kind": "word",
   "alts": [
    "i hope (?:this|that|it) (?:helps|is helpful|works|meets|gives)",
    "hope (?:this|that) helps",
    "feel free to (?:ask|reach out|let me know|adjust|modify|request|contact me)",
    "let me know if (?:you|there)",
    "would you like me to",
    "shall i (?:expand|revise|rewrite|add|adjust|continue)",
    "happy to (?:help|assist|revise|expand|adjust)",
    "if you(?:'|’)d like,? i can",
    "do you want me to"
   ]
  },
  {
   "key": "en_leak_cheer",
   "label": "Chatbot cheerful opener (Certainly! / Great question!)",
   "severity": "high",
   "kind": "start",
   "alts": [
    "(?:certainly|absolutely|sure thing|great question|good question|of course|sure|understood|got it|no problem)(?=[!])",
    "(?:sure|certainly|absolutely),? (?:here|i(?:'|’)ll|i can|let me)"
   ]
  },
  {
   "key": "en_leak_knowledge",
   "label": "Model limitation statement (knowledge cutoff, cannot browse)",
   "severity": "high",
   "kind": "word",
   "alts": [
    "as of my (?:last|latest|knowledge|training)",
    "my (?:knowledge|training) (?:cutoff|cut-off|data)",
    "i (?:cannot|can(?:'|’)t|am unable to|do not|don(?:'|’)t) (?:browse|access (?:real-time|the internet|live)|verify (?:this|that|these)|have (?:access|real-time|personal))",
    "i (?:don(?:'|’)t|do not) have (?:personal )?(?:opinions|experiences|feelings)",
    "my training data",
    "up to my knowledge"
   ]
  },
  {
   "key": "en_leak_placeholder",
   "label": "Unfilled placeholder or template field",
   "severity": "high",
   "kind": "word",
   "alts": [
    "\\[(?:insert|your|name|date|link|source|url|image|photo|city|company|quote|add|todo|tbc|tbd|citation needed|placeholder)[^\\]\\n]{0,50}\\]",
    "lorem ipsum",
    "\\{\\{[^}\\n]{1,40}\\}\\}",
    "<(?:insert|your|name|date|link)[^>\\n]{0,40}>",
    "xx{2,}",
    "\\[\\.\\.\\.\\]"
   ]
  },
  {
   "key": "en_leak_citation",
   "label": "Chat-interface citation artefact (oaicite, contentReference, utm_source=chatgpt)",
   "severity": "high",
   "kind": "word",
   "alts": [
    "oaicite",
    "contentreference",
    "citeturn\\d*\\p{L}*",
    "turn\\d+(?:search|view|news)\\d+",
    "utm_source=(?:chatgpt|openai|copilot|claude|perplexity)\\S*",
    "\\[\\^?\\d{1,2}\\]\\(https?:"
   ]
  },
  {
   "key": "en_leak_meta",
   "label": "Editor-note leakage (Here is the updated…, Below is…, I have rewritten…)",
   "severity": "high",
   "kind": "word",
   "alts": [
    "here(?:'|’)s (?:an? |the |your )?(?:updated|final|improved|expanded|shortened|condensed|rewritten|more|revised|new|clean|full|complete) \\p{L}+",
    "here is (?:an? |the |your )?(?:updated|final|improved|expanded|shortened|condensed|rewritten|more|new|clean|full|complete) \\p{L}+",
    "below (?:is|are) (?:the|a|an|your|some)",
    "i(?:'|’)?ve (?:rewritten|revised|updated|kept|removed|adjusted|tightened|reworked|edited|shortened|expanded)",
    "i have (?:rewritten|revised|updated|kept|removed|adjusted|tightened|reworked|edited|shortened|expanded)",
    "(?:word|character) count\\s*:\\s*\\d+",
    "(?:changes|edits|notes) made\\s*:",
    "as requested,? (?:here|below)",
    "per your (?:request|instructions)"
   ]
  },
  {
   "key": "en_leak_fields",
   "label": "Output-template field at paragraph start (Title:, Meta description:, Slug:)",
   "severity": "high",
   "kind": "start",
   "alts": [
    "(?:title|headline|seo title|meta title|meta description|slug|focus keyword|primary keyword|keywords|word count|alt text|article|output|draft|revised draft|final version|tl;dr|tldr)\\s*:",
    "\\*\\*(?:title|headline|meta description|slug|keywords?|conclusion|introduction|body)\\*\\*\\s*:?"
   ]
  },
  {
   "key": "en_leak_disclosure",
   "label": "AI authorship disclosure or disclaimer in the copy",
   "severity": "high",
   "kind": "word",
   "alts": [
    "(?:this|the) (?:article|text|piece|content|post|copy) (?:was|has been|is) (?:generated|written|created|produced|drafted|composed) (?:by|with|using) (?:an? )?(?:ai|artificial|chatgpt|gpt|language model|llm|claude|gemini|copilot)",
    "(?:ai|machine)-generated (?:content|text|article|copy)",
    "generated (?:by|with|using) (?:ai|chatgpt|gpt|claude|gemini)",
    "translator(?:'|’)s note",
    "as a (?:helpful )?(?:assistant|chatbot|virtual assistant)",
    "(?:disclaimer|note)\\s*:\\s*(?:this|the) (?:article|content|text)"
   ]
  },
  {
   "key": "en_leak_html",
   "label": "Raw HTML entity or tag artefact in prose",
   "severity": "high",
   "kind": "word",
   "alts": [
    "&(?:nbsp|rsquo|lsquo|ldquo|rdquo|mdash|ndash|quot|hellip|#\\d{2,4});",
    "<br\\s*/?>",
    "</?(?:p|div|span|strong|em)\\s*>",
    "\\\\n\\\\n",
    "\\\\u[0-9a-f]{4}"
   ]
  },
  {
   "key": "en_md_bold_lead",
   "label": "Bold-lead bullet or paragraph (**Label:** explanation)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "(?:[-*•]\\s+|\\d{1,2}[.)]\\s+)?\\*\\*[^*\\n]{2,60}(?:[.:]\\*\\*|\\*\\*\\s*[:–—-])"
   ],
   "min": 2
  },
  {
   "key": "en_md_numbered_bold",
   "label": "Numbered list with bold item names (1. **Name**)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "\\d{1,2}[.)]\\s+\\*\\*[^*\\n]{2,60}\\*\\*"
   ],
   "min": 2
  },
  {
   "key": "en_md_table_rule",
   "label": "Markdown table or horizontal rule in prose",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\|\\s*:?-{3,}:?\\s*\\|",
    "\\|[^|\\n]{1,40}\\|[^|\\n]{1,40}\\|[^|\\n]{1,40}\\|"
   ]
  },
  {
   "key": "en_quote_mix_apos",
   "label": "Straight and curly apostrophes mixed in one text",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\p{L}+'\\p{L}+[^\\n]{0,800}?\\p{L}+’\\p{L}+",
    "\\p{L}+’\\p{L}+[^\\n]{0,800}?\\p{L}+'\\p{L}+"
   ]
  },
  {
   "key": "en_quote_mix_dq",
   "label": "Straight and curly double quotes mixed in one text",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\"[^\"\\n]{2,300}\"[^\\n]{0,800}?“[^”\\n]{2,200}”",
    "“[^”\\n]{2,300}”[^\\n]{0,800}?\"[^\"\\n]{2,200}\""
   ]
  },
  {
   "key": "en_spaced_hyphen",
   "label": "Spaced hyphen used as a dash (word - word)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\p{L}+ - \\p{L}+"
   ],
   "min": 2
  },
  {
   "key": "en_hashtag",
   "label": "Hashtags inside article text",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "#\\p{L}{3,}"
   ],
   "min": 2
  },
  {
   "key": "en_colon_heavy",
   "label": "Colon-heavy sentence (three or more colons)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "[^.!?\\n:\\d]{4,}:[^.!?\\n:\\d]{4,}:[^.!?\\n:\\d]{4,}:"
   ]
  },
  {
   "key": "en_label_colon",
   "label": "Paragraphs opening with a short label and colon (Best for:, Where to stay:)",
   "severity": "low",
   "kind": "start",
   "alts": [
    "\\p{L}[\\p{L} '’&/-]{2,30}:"
   ],
   "min": 3
  },
  {
   "key": "en_arrow_bullet",
   "label": "Decorative bullet or arrow glyph at paragraph start",
   "severity": "low",
   "kind": "start",
   "alts": [
    "[►▶▸◆◇■□→✦❖➤]"
   ],
   "min": 2
  },
  {
   "key": "en_ellipsis",
   "label": "Ellipsis used for effect",
   "severity": "low",
   "kind": "word",
   "alts": [
    "\\p{L}*(?:…|\\.{3})"
   ],
   "min": 3
  },
  {
   "key": "en_head_template",
   "label": "Stock listicle heading (What it costs, Who can join, How to apply…)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "(?:#{1,4}\\s*)?(?:what it costs|who can join|who (?:is it|it(?:'|’)s) for|who should (?:apply|go|consider)|how (?:to apply|it works|much (?:does it|it) cost)|what you (?:need|should) (?:to )?know|what to expect|what to know|why it matters|why (?:it|this) matters|where to (?:stay|eat|go|start|find)|when to (?:go|visit|apply)|how to get there|getting there|getting around|best time to (?:visit|go)|pros and cons|at a glance|quick facts|the details|the process|the catch|the numbers|the cost|the benefits|the requirements|key (?:facts|points|dates|details)|(?:step|stage) \\d)[ \\t:?!.]*(?=\\n|$)"
   ],
   "min": 2
  },
  {
   "key": "en_head_summary",
   "label": "Summary-style closing heading (Conclusion, Final thoughts, The bottom line)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "(?:#{1,4}\\s*)?(?:conclusion|final thoughts|the bottom line|bottom line|key takeaways?|takeaways?|in summary|summary|wrapping up|looking ahead|the road ahead|what(?:'|’)s next|the verdict|our verdict|final verdict|in closing|closing thoughts|the way forward|faqs?|frequently asked questions)[ \\t:?!.]*(?=\\n|$)"
   ]
  },
  {
   "key": "en_title_guide",
   "label": "Guide-template phrasing (ultimate guide, everything you need to know)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:complete|ultimate|essential|definitive|comprehensive|insider(?:'|’)s|beginner(?:'|’)s|step-by-step|practical) guide to",
    "everything you (?:need|should|ought|have) to know",
    "all you need to know",
    "a (?:deep|closer|comprehensive|detailed) (?:dive|look) (?:into|at)",
    "top \\d{1,2} (?:things|reasons|ways|tips|places|spots|must)",
    "\\d{1,2} (?:things|reasons|ways|tips) (?:to|you|why)"
   ]
  },
  {
   "key": "en_enum_scaffold",
   "label": "Enumeration scaffolding (Firstly, Secondly, Lastly)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "firstly",
    "secondly",
    "thirdly",
    "fourthly",
    "lastly",
    "last but not least",
    "first and foremost",
    "to begin with,",
    "for starters,"
   ],
   "min": 2
  },
  {
   "key": "en_enum_takeaways",
   "label": "Takeaway and checklist scaffolding (key points, things to consider)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "key takeaways?",
    "(?:main|key|top|essential|important) (?:points|considerations|factors|things to (?:know|consider|remember|keep in mind)|elements|aspects|highlights)",
    "things to (?:know|consider|keep in mind|remember|look out for|watch out for)",
    "(?:the )?following (?:\\p{L}+ ){0,2}(?:points|factors|steps|reasons|tips|options|considerations|areas|aspects)",
    "(?:here are|below are|these are) (?:\\d+|\\p{L}+) (?:key |top |essential |important |simple |easy )?(?:things|tips|reasons|ways|points|factors|steps)",
    "(?:challenges|risks|drawbacks) (?:and|but) (?:opportunities|rewards|benefits)",
    "(?:opportunities|benefits|advantages) and (?:challenges|risks|drawbacks|disadvantages)",
    "(?:pros|advantages|benefits) and (?:cons|disadvantages|drawbacks)"
   ]
  },
  {
   "key": "en_signpost",
   "label": "Signposting the article itself (in this guide, as we will see, let’s get started)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "in this (?:article|guide|piece|feature|section|post)",
    "(?:this|the) (?:guide|article|piece|feature) (?:will|explores|examines|looks|takes|covers|delves|walks|outlines|provides|offers|aims|breaks)",
    "(?:read on|keep reading|continue reading|scroll down|stay with us)",
    "as (?:we(?:'|’)ll|we will|you(?:'|’)ll|you will) see",
    "as (?:mentioned|discussed|noted|outlined|highlighted|stated) (?:earlier|above|previously|before|below)",
    "without further ado",
    "(?:let(?:'|’)s|let us) (?:get started|begin|start|jump in|find out|unpack|break (?:it|this) down|take a (?:closer )?look|walk through|dive)",
    "(?:we|i) (?:will|shall) (?:now )?(?:turn|look|discuss|explore|examine|cover)",
    "moving on to"
   ]
  },
  {
   "key": "en_throat_clear",
   "label": "Throat-clearing opener (Here’s what you need to know, Welcome to…)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "here(?:'|’)s (?:what|everything|why|how|the (?:short|quick|lowdown|deal|story|thing)|a (?:quick|brief|closer)|your)",
    "here is (?:what|everything|why|how)",
    "(?:let(?:'|’)s|let us) (?:take a (?:closer )?look|dive|explore|break|unpack|talk|get)",
    "welcome to",
    "(?:are|were) you (?:looking|planning|thinking|dreaming|considering|wondering|tired)",
    "have you ever (?:wondered|dreamed|thought|wanted|considered|stopped)",
    "ever (?:wondered|dreamed|wanted|thought)",
    "if you(?:'|’)re (?:looking|planning|thinking|considering|wondering|dreaming|new|moving|searching)",
    "(?:imagine|picture) (?:this|a|an|yourself|waking|strolling|walking|sipping|stepping|sitting|the|that)",
    "what if (?:i|you|we) (?:told|said|could)",
    "when it comes to",
    "in the world of",
    "from [^.,;]{3,40} to [^.,;]{3,40},",
    "few (?:places|destinations|islands|cities|countries) (?:capture|embody|combine|offer|can)",
    "there(?:'|’)s (?:something|a reason|no place|nowhere) (?:about|why|like)",
    "it(?:'|’)s no secret that",
    "it goes without saying"
   ]
  },
  {
   "key": "en_participial_open",
   "label": "Participial paragraph opener (Nestled…, Boasting…, Perched…, Offering…)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "(?:nestled|perched|tucked|situated|located|set|boasting|offering|featuring|combining|blending|stretching|spanning|overlooking|sitting|steeped|rooted|renowned|known|famed|home)(?: away)? (?:in|on|at|between|along|amid|amidst|against|beside|above|within|with|for|to|its|a|an|the|by|just|high|deep|inland)"
   ]
  },
  {
   "key": "en_closing_alt",
   "label": "Wrap-up paragraph opener beyond the basics (In the end, Overall, Looking ahead…)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "in (?:the end|short|essence|a nutshell|closing|brief|sum|the final analysis|the grand scheme of things|many ways)",
    "to (?:summari[sz]e|conclude|wrap up|recap|put it simply)",
    "overall",
    "on balance",
    "taken together",
    "looking (?:ahead|forward|back)",
    "(?:the )?(?:bottom line|key takeaway|takeaway|upshot|big picture)(?: is|:|,)",
    "what(?:'|’)s clear|what is clear",
    "one thing is (?:certain|clear|for sure)",
    "when all is said and done",
    "at the end of the day",
    "final thoughts",
    "wrapping up",
    "so,? (?:whether|if|there you have it|what)",
    "there you have it",
    "as (?:the|cyprus|the island|the market) (?:continues|moves|looks|navigates|evolves|grows)",
    "(?:whether|whatever) you(?:'|’)?(?:re| are|r)? (?:a|an|looking|planning|seeking|after|an)",
    "for (?:those|anyone|investors|travell?ers|visitors|buyers|families|readers) (?:who|looking|seeking|considering|wanting|wishing|planning)",
    "in (?:conclusion|summary)"
   ]
  },
  {
   "key": "en_moral",
   "label": "Moral or lesson conclusion (a reminder that…, true luxury lies in…)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:reminds?|reminded) us (?:that|of|how|why)",
    "(?:a|the|this) (?:powerful|timely|stark|sobering|gentle|welcome|valuable|important|clear|simple|salutary|useful|poignant) (?:reminder|lesson|message|signal|illustration)",
    "(?:serves?|served) as a (?:reminder|beacon|blueprint|model|catalyst|case study|lesson|cautionary)",
    "the (?:lesson|moral|message|takeaway) (?:is|here|from)",
    "(?:true|real|ultimate) (?:luxury|wealth|success|beauty|hospitality|magic|value|richness|freedom) (?:lies|is|comes|means|isn(?:'|’)t|lives)",
    "(?:life|success|travel|luxury|home|beauty|art|food)(?: is| isn(?:'|’)t) (?:not )?(?:just |simply )?(?:about|a journey|a destination|measured)",
    "(?:it(?:'|’)s|it is|this is|that(?:'|’)s) (?:all )?about (?:the )?(?:journey|moments|connection|community|experiences|memories|finding|savouring|savoring|slowing)",
    "the journey (?:is|isn(?:'|’)t)(?: just| not)?(?: about)? the destination",
    "(?:proof|proves|shows|demonstrates) that [^.]{0,60}(?:can|always|never|every|everyone|anyone|nothing|anything|everything)"
   ]
  },
  {
   "key": "en_forward_closer",
   "label": "Forward-looking cliché closer (the future looks bright, watch this space)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:the|a) (?:future|road ahead|path ahead|path forward|road forward) (?:looks|is|holds|remains)",
    "(?:what|whatever) (?:the )?(?:future holds|lies ahead|comes next)",
    "watch this space",
    "stay tuned",
    "(?:one|ones) to watch",
    "(?:a|the) (?:space|story|name|brand|destination|island|market|trend|chef|label|venue) to watch",
    "(?:bright|exciting|promising) (?:future|times|chapter|days)",
    "(?:best|brightest|good) (?:is|days|things|times) (?:yet to come|ahead|still to come)",
    "only (?:getting|just) (?:started|begun|better|bigger)",
    "(?:just )?the (?:beginning|start) of",
    "tip of the iceberg",
    "(?:a )?new (?:chapter|era|dawn)",
    "(?:here to stay|just getting started)",
    "promises? to (?:be|remain|continue)"
   ]
  },
  {
   "key": "en_connector_anywhere",
   "label": "Stock connectors in running prose (moreover, furthermore, additionally)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "moreover",
    "furthermore",
    "additionally",
    "in addition(?:,| to)",
    "what(?:'|’)s more",
    "not to mention",
    "on top of that",
    "by the same token",
    "that said,",
    "having said that",
    "that being said",
    "with that (?:said|in mind)"
   ],
   "min": 3
  },
  {
   "key": "en_connector_start",
   "label": "Paragraphs opening with a sentence adverb (Notably, Importantly, Indeed, Overall)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "(?:notably|importantly|interestingly|significantly|crucially|indeed|consequently|thus|hence|essentially|ultimately|undoubtedly|certainly|clearly|naturally|of course|simply put|put simply|in particular|in fact|as such|accordingly|subsequently|likewise|similarly)(?=,)",
    "(?:it|this) is (?:worth|important|crucial|essential|vital|key|also worth)"
   ],
   "min": 2
  },
  {
   "key": "en_contrast_more",
   "label": "“It’s not just X, it’s Y” and its variants (not merely, no longer just, less about X than Y)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "it(?:'|’)s not (?:just|merely|simply|only|about)[^.?!]{0,70}[,;:] (?:it(?:'|’)s|but)",
    "(?:this|that) is not (?:just|merely|simply|only)[^.?!]{0,70}[,;:] (?:it(?:'|’)s|it is|but)",
    "(?:it(?:'|’)s|this is|that(?:'|’)s) (?:not|less) (?:about|a matter of)[^.?!]{0,60}(?:it(?:'|’)s|but|more) (?:about|a|an)",
    "(?:no longer|not) (?:just|merely|simply) (?:a|an|the)",
    "beyond (?:just|mere|merely|simply)",
    "(?:more|less) (?:about|than)[^.?!]{0,40} than (?:about|a)",
    "not so much [^.?!]{0,60} as",
    "not (?:only|just) [^.?!]{0,70} but (?:also )?(?:a|an|the|as)"
   ]
  },
  {
   "key": "en_tricolon_abstract",
   "label": "Tricolon of abstract nouns (innovation, creativity and tradition)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\p{L}+(?:ity|ion|ness|ment|ance|ence|ism|ship|th)s?, \\p{L}+(?:ity|ion|ness|ment|ance|ence|ism|ship|th)s?,? (?:and|or|&) \\p{L}+(?:ity|ion|ness|ment|ance|ence|ism|ship|th)s?"
   ],
   "min": 2
  },
  {
   "key": "en_tricolon_hype",
   "label": "Stacked hype adjectives (charming and authentic, rich, vibrant and diverse)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:exquisite|captivating|enchanting|mesmeri[sz]ing|spellbinding|magnificent|majestic|idyllic|serene|tranquil|opulent|sumptuous|awe-inspiring|jaw-dropping|spectacular|iconic|timeless|authentic|charming|picturesque|diverse|dynamic|innovative|elegant|sophisticated|refined|lively|warm|welcoming|cosy|cozy|rustic|stylish|unique|exceptional|exciting)(?:, | and | & )(?:exquisite|captivating|enchanting|mesmeri[sz]ing|spellbinding|magnificent|majestic|idyllic|serene|tranquil|opulent|sumptuous|awe-inspiring|spectacular|iconic|timeless|authentic|charming|picturesque|diverse|dynamic|innovative|elegant|sophisticated|refined|lively|welcoming|cosy|cozy|rustic|stylish|unique|exceptional|exciting|unforgettable|vibrant)"
   ]
  },
  {
   "key": "en_participial_close",
   "label": "Participial tail clause (…, highlighting / ensuring / reflecting …)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\p{L}+,\\s+(?:highlighting|underscoring|reflecting|ensuring|showcasing|demonstrating|emphasi[sz]ing|reinforcing|cementing|solidifying|signalling|signaling|illustrating|positioning|fostering|contributing to|paving the way|setting the stage|adding to|making (?:it|this|them) (?:an? |the )?\\p{L}+|allowing (?:for|visitors|guests|residents|buyers|investors)|offering (?:visitors|guests|residents|buyers|investors|a (?:glimpse|taste|window|rare|unique))|providing (?:visitors|guests|residents|buyers|investors|a (?:glimpse|taste|window|platform|backdrop|stunning|unique))|creating (?:a|an|the)|enabling|empowering|elevating|enhancing|transforming|bringing|inviting|promising|cementing)"
   ],
   "min": 2
  },
  {
   "key": "en_signif_importance",
   "label": "Empty significance (highlights the importance of, reflects the growing…)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:highlight|reflect|reinforce|signal|demonstrate|illustrate|emphasi[sz]e|speak|point|attest|bear witness)(?:s|ed|ing)? (?:to |of )?(?:the )?(?:importance|significance|value|need|necessity|role|growing|broader|wider|enduring|ongoing|continued|continuing|increasing(?:ly)?|resilience|appeal|power|depth|richness|strength)",
    "(?:a|the) (?:reminder|symbol|hallmark|embodiment|epitome|reflection|manifestation|cornerstone|linchpin|pillar|beacon) (?:of|that|to|for)",
    "(?:key|vital|crucial|critical|essential|integral|central|pivotal) (?:part|piece|element|component|aspect|factor|driver|pillar)(?: of| in)",
    "(?:deeply|firmly|inextricably) (?:rooted|embedded|woven|intertwined|linked|tied) (?:in|into|with|to)"
   ]
  },
  {
   "key": "en_signif_legacy",
   "label": "Legacy and milestone padding (lasting impact, paves the way, marks a new chapter)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:leaves?|left|leaving) (?:a|an) (?:lasting|indelible|enduring|lasting and)\\s*(?:impact|impression|mark|legacy)",
    "(?:lasting|indelible|enduring) (?:impact|impression|legacy|mark|appeal)",
    "(?:shape|shaping|shaped|shapes) the future of",
    "(?:paves?|paving|paved) the way (?:for|to)",
    "sets? the (?:stage|tone|bar|standard|benchmark) for",
    "(?:turning point|watershed moment|game[- ]chang(?:er|ing)|paradigm shift|sea change|tipping point)",
    "marks? (?:a|an|the) (?:significant|major|new|important|pivotal|turning|historic|milestone|notable|watershed)",
    "(?:cements?|solidif(?:y|ies|ying)|reinforces?|strengthens?) (?:its|his|her|their) (?:position|place|status|reputation|credentials|standing)",
    "(?:significant|major|important) milestone",
    "(?:a )?(?:significant|important|major|pivotal) (?:step|leap|stride) (?:forward|towards|toward)"
   ]
  },
  {
   "key": "en_news_cliche",
   "label": "News-copy filler (amid growing concerns, against a backdrop of, landmark decision)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:amid|amidst) (?:growing|rising|mounting|increasing|ongoing|continued|heightened|widespread|renewed) (?:concerns|tensions|fears|uncertainty|scrutiny|speculation|pressure|calls|criticism|debate)",
    "against (?:a|the) (?:backdrop|background|context) of",
    "(?:sparked|sparks|sparking|ignited|ignites|triggered) (?:a )?(?:debate|controversy|outrage|conversation|discussion|firestorm|wave)",
    "(?:sent|sends|sending) (?:shock ?waves|ripples)",
    "(?:taken|taking|took) the (?:island|country|world|industry|market|city) by storm",
    "(?:landmark|unprecedented|groundbreaking|watershed|seismic|sweeping|historic|bold) (?:decision|ruling|move|step|announcement|agreement|deal|reform|shift|development|moment|milestone|legislation|initiative)",
    "(?:sends?|sent) a (?:clear|strong|powerful|stark|loud|unmistakable) (?:message|signal)",
    "(?:as|while) the (?:situation|story|saga|dust) (?:unfolds|settles|continues)",
    "raised? (?:eyebrows|concerns|questions)",
    "(?:the )?(?:ripple|domino) effect"
   ]
  },
  {
   "key": "en_lex_verbs",
   "label": "AI verb family (leverage, foster, garner, bolster, spearhead, encompass…)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "leverag(?:e|es|ed|ing)",
    "foster(?:s|ed|ing)?",
    "garner(?:s|ed|ing)?",
    "bolster(?:s|ed|ing)?",
    "spearhead(?:s|ed|ing)?",
    "underpin(?:s|ned|ning)?",
    "encompass(?:es|ed|ing)?",
    "embod(?:y|ies|ied|ying)",
    "encapsulat(?:e|es|ed|ing)",
    "resonat(?:e|es|ed|ing) with",
    "cater(?:s|ed|ing)? to",
    "harness(?:es|ed|ing)?",
    "streamlin(?:e|es|ed|ing)",
    "revolutioni[sz](?:e|es|ed|ing)",
    "transcend(?:s|ed|ing)?",
    "empower(?:s|ed|ing)?",
    "navigat(?:e|es|ed|ing) (?:the|a|an|its|their|these|this)",
    "unlock(?:s|ed|ing)?",
    "elevat(?:e|es|ed|ing)",
    "curat(?:e|es|ed|ing)",
    "delv(?:e|es|ed)",
    "immers(?:e|es|ed|ing) (?:yourself|themselves|visitors|guests)",
    "celebrat(?:e|es|ed|ing) (?:the|its|their|a) (?:rich|vibrant|diverse|unique|spirit)"
   ],
   "min": 2
  },
  {
   "key": "en_lex_adj",
   "label": "AI adjective family (pivotal, paramount, multifaceted, holistic, robust…)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "pivotal",
    "paramount",
    "indispensable",
    "multifaceted",
    "multi-faceted",
    "holistic",
    "intricate",
    "intricacies",
    "invaluable",
    "quintessential",
    "emblematic",
    "monumental",
    "transformative",
    "groundbreaking",
    "innovative",
    "dynamic",
    "robust",
    "comprehensive",
    "bespoke",
    "vibrant",
    "unwavering",
    "steadfast",
    "meticulously crafted",
    "impeccabl[ey]",
    "exquisite(?:ly)?",
    "nuanced",
    "compelling",
    "profound(?:ly)?"
   ],
   "min": 2
  },
  {
   "key": "en_lex_nouns",
   "label": "AI noun family (realm, landscape, ecosystem, beacon, cornerstone, hub, gateway)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "realm",
    "landscape",
    "ecosystem",
    "beacon",
    "cornerstone",
    "linchpin",
    "backbone",
    "crossroads",
    "gateway",
    "haven",
    "hub",
    "synerg(?:y|ies)",
    "paradigm",
    "trajectory",
    "narrative",
    "endeavou?rs?",
    "offerings?",
    "stakeholders?",
    "journey",
    "experiences?",
    "allure",
    "essence",
    "ethos"
   ],
   "min": 3
  },
  {
   "key": "en_hype_more",
   "label": "Hype adjectives beyond the basics (exquisite, captivating, majestic, idyllic, serene…)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "exquisite",
    "captivating",
    "enchanting",
    "mesmeri[sz]ing",
    "spellbinding",
    "magnificent",
    "majestic",
    "idyllic",
    "serene",
    "tranquil",
    "opulent",
    "sumptuous",
    "awe-inspiring",
    "jaw-dropping",
    "spectacular",
    "iconic",
    "immaculate",
    "resplendent",
    "delightful",
    "charming",
    "gorgeous",
    "magical",
    "pristine",
    "unspoilt",
    "unspoiled",
    "idyllic",
    "quintessential",
    "legendary",
    "timeless",
    "authentic",
    "exclusive"
   ],
   "min": 3
  },
  {
   "key": "en_filler_note",
   "label": "Importance-flagging filler (it is important to note, it bears mentioning)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "it(?:'|’)?s (?:important|crucial|essential|vital|key|worth (?:mentioning|remembering|highlighting|emphasi[sz]ing|pointing out)) to (?:note|remember|understand|recogni[sz]e|keep in mind|consider|highlight|mention|emphasi[sz]e|bear in mind)",
    "it is (?:important|crucial|essential|vital|key|worth (?:mentioning|remembering|highlighting|emphasi[sz]ing|pointing out)) to (?:note|remember|understand|recogni[sz]e|keep in mind|consider|highlight|mention|emphasi[sz]e|bear in mind)",
    "it bears (?:mentioning|repeating|noting|emphasi[sz]ing)",
    "(?:one|it) (?:cannot|can(?:'|’)t) (?:help but|be (?:denied|overstated|ignored))",
    "there(?:'|’)?s no denying",
    "there is no denying",
    "needless to say",
    "it should be (?:noted|emphasi[sz]ed|stressed|mentioned)",
    "(?:keep|bear) in mind that",
    "(?:remember|note) that",
    "worth (?:mentioning|highlighting|remembering|emphasi[sz]ing|pointing out)"
   ]
  },
  {
   "key": "en_filler_phrases",
   "label": "Padding phrases (in terms of, at its core, a wide range of, in the realm of)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "in terms of",
    "at its core",
    "at the heart of",
    "in essence",
    "a wide (?:range|variety|array|selection) of",
    "a (?:diverse|broad|rich|vast) (?:range|array|selection|variety) of",
    "in the realm of",
    "without a doubt",
    "undoubtedly",
    "(?:the )?(?:vast|overwhelming) majority of",
    "a (?:great|good) deal of",
    "in (?:many|various|numerous|several) ways",
    "a variety of",
    "a range of",
    "a number of",
    "countless",
    "numerous",
    "various"
   ],
   "min": 2
  },
  {
   "key": "en_bureaucratic",
   "label": "Bureaucratic padding (in order to, due to the fact that, with regard to, prior to)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "in order to",
    "due to the fact that",
    "in the event that",
    "at this point in time",
    "for the purpose of",
    "with (?:regard|respect) to",
    "in light of the fact",
    "the fact that",
    "has the ability to",
    "is able to",
    "is capable of",
    "in the process of",
    "on a (?:daily|regular|weekly|monthly) basis",
    "at the present time",
    "prior to",
    "subsequent to",
    "in close proximity",
    "the majority of",
    "utili[sz](?:e|es|ed|ing)",
    "commence[sd]?",
    "endeavou?r",
    "facilitat(?:e|es|ed|ing)",
    "in conjunction with"
   ],
   "min": 3
  },
  {
   "key": "en_copula_more",
   "label": "Copula avoidance (acts as, represents, constitutes, prides itself on, is home to)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?:acts?|acted) as (?:a|an|the)",
    "(?:represents|constitutes|embodies|comprises|encompasses) (?:a|an|the)",
    "(?:prides|pride) itself on",
    "is home to",
    "holds the distinction",
    "(?:remains|remained) (?:a|an|the) (?:popular|favourite|favorite|beloved|enduring|vibrant|key|top)",
    "(?:offers|offering|offer) (?:visitors|guests|residents|buyers|investors|diners|readers) (?:a|an|the)",
    "(?:is|are) (?:renowned|celebrated|famed|revered|lauded) for",
    "(?:is|are) (?:also )?(?:home|host) to",
    "(?:play|plays|played) host to"
   ],
   "min": 2
  },
  {
   "key": "en_features_estate",
   "label": "“The property features / offers / comprises” listing register",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?:property|villa|apartment|residence|home|development|hotel|resort|restaurant|suite|room|complex|building|house|menu|space|venue|bar|gallery|collection)(?: also)? (?:features|boasts|comprises|includes|provides|benefits from|enjoys|presents|showcases|houses)"
   ],
   "min": 2
  },
  {
   "key": "en_estate_ideal",
   "label": "Estate-agent suitability line (ideal for investors, perfect base)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:ideal|perfect) (?:for (?:investors|families|buyers|expats|retirees|those|anyone|everyone|couples|holidaymakers|nomads|digital nomads|first-time|relocators|professionals|entrepreneurs)|(?:base|choice|destination|location|spot|retreat|getaway|setting|place|option|investment|backdrop|home|launchpad))",
    "(?:an )?ideal (?:blend|mix|balance|combination|opportunity|solution)",
    "the (?:perfect|ideal) (?:blend|mix|balance|combination|marriage) of",
    "best of both worlds"
   ]
  },
  {
   "key": "en_estate_location",
   "label": "Location puffery (strategic location, prime position, a stone’s throw)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:strategic(?:ally)?|prime|enviable|coveted|sought-after|highly sought-after|unrivalled|unrivaled|privileged|central yet|tranquil yet|peaceful yet|exclusive) (?:location|position|located|situated|address|area|setting|neighbourhood|neighborhood|spot|situation|positioned)",
    "a stone(?:'|’)s throw",
    "(?:everything|all) (?:you|one) (?:could|might|will|needs?) (?:need|want|desire|wish)",
    "(?:amenities|attractions|facilities|restaurants|shops|cafes|cafés) (?:galore|aplenty)",
    "within easy reach of",
    "well[- ]connected",
    "just minutes (?:away|from)"
   ]
  },
  {
   "key": "en_estate_invest",
   "label": "Investment puffery (lucrative opportunity, savvy investors, rental yield potential)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:attractive|lucrative|compelling|excellent|strong|solid|promising|sound|smart|savvy|rewarding|profitable) (?:investment|returns?|yields?|opportunit(?:y|ies)|prospects|proposition)",
    "(?:golden|unmissable|once-in-a-lifetime|rare|unique) (?:opportunity|chance)",
    "(?:capital appreciation|rental yield|rental income|growth) potential",
    "(?:savvy|discerning|smart|astute|seasoned) (?:investors?|buyers?|travell?ers?|diners?|collectors?)",
    "(?:investors?|buyers?|expats?)(?:'|’)? (?:paradise|haven|magnet|favourite|favorite|darling)",
    "(?:poised|set|primed|well-positioned|well positioned|ready) (?:to|for) (?:grow|growth|thrive|flourish|benefit|capitali[sz]e|become|remain|continue|take off|boom)",
    "(?:going|moving) forward",
    "turn-?key",
    "(?:dream|forever) home",
    "(?:live|living) the (?:dream|island life)",
    "luxury living",
    "second to none",
    "peace of mind",
    "lifestyle (?:opportunity|choice|destination)"
   ]
  },
  {
   "key": "en_press_release",
   "label": "Press-release register (delighted to announce, committed to excellence, leading provider)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:is|are|was|were) (?:pleased|delighted|proud|thrilled|excited|honou?red) to (?:announce|unveil|introduce|welcome|present|share|partner)",
    "(?:committed|dedicated|dedication|commitment) to (?:excellence|sustainability|innovation|delivering|providing|quality|providing)",
    "(?:world-class|best-in-class|industry-leading|market-leading|award-winning|first-class|top-tier|premier|leading provider|one-stop|end-to-end|full-service)",
    "(?:innovative|tailored|bespoke|tailor-made|customi[sz]ed|bespoke) solutions",
    "(?:key|major|leading|prominent) players? in",
    "value proposition",
    "(?:strategic )?partnerships? (?:with|between)",
    "(?:poised|positioned) (?:to|as) ",
    "passionate (?:about|team|professionals|experts)",
    "(?:team of )?(?:dedicated|passionate|experienced|seasoned) (?:professionals|experts|team)",
    "trusted (?:partner|name|advisor|adviser)",
    "robust (?:framework|infrastructure|platform|ecosystem|pipeline)"
   ]
  },
  {
   "key": "en_thriving",
   "label": "Boom words (thriving, flourishing, burgeoning, booming, buzzing)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "thriv(?:ing|es|e|ed)",
    "flourish(?:ing|es|ed)?",
    "burgeoning",
    "booming",
    "buzzing",
    "up-and-coming",
    "on the rise",
    "go-to",
    "trendy",
    "hotspot",
    "hot ?spots?",
    "bursting with",
    "teeming with",
    "brimming with",
    "alive with",
    "pulsat(?:es|ing|e) with",
    "abound(?:s|ing)?"
   ],
   "min": 2
  },
  {
   "key": "en_hedge_stack",
   "label": "Hedge stacking (may potentially, could arguably, can often be considered)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:may|might|could|can|would) (?:potentially|possibly|perhaps|arguably|conceivably|theoretically)",
    "(?:generally|typically|usually|often|sometimes|arguably|potentially|essentially|largely|broadly) (?:be )?(?:considered|regarded|seen|viewed|deemed|thought of)",
    "(?:may|might|could|can) (?:often |generally |typically |usually |sometimes )?(?:be )?(?:considered|seen as|viewed as|regarded as)",
    "(?:seems|appears|tends) to (?:suggest|indicate|imply)",
    "(?:it|this) (?:may|might|could) (?:well|also|be (?:argued|said|suggested))",
    "(?:somewhat|relatively|fairly|rather|slightly|arguably) (?:more |less )?(?:challenging|complex|difficult|competitive|limited|nuanced|involved)",
    "to (?:some|a certain|a (?:large|great)) (?:extent|degree)",
    "(?:may|might|can) vary (?:depending|significantly|widely|considerably)",
    "results may vary"
   ]
  },
  {
   "key": "en_hedge_depends",
   "label": "“It depends on a number of factors” non-answer",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "depends? (?:largely |heavily |entirely |very much )?on (?:a (?:number|variety|range|host|combination) of|several|various|many|multiple|numerous|your|individual|a (?:range|mix))\\s*(?:\\p{L}+ )?(?:factors|variables|considerations|circumstances|needs|elements)",
    "(?:your|individual|personal|specific|particular|each|unique) (?:circumstances|situation|needs|preferences|requirements|case)(?: and| will| may| can)?",
    "(?:varies|vary) (?:from|by|depending) (?:case to case|person to person|property to property|individual|on)",
    "(?:every|each) (?:case|situation|buyer|traveller|traveler|investor|property) is (?:different|unique)",
    "(?:no|there is no) one-size-fits-all",
    "one-size-fits-all"
   ]
  },
  {
   "key": "en_disclaimer",
   "label": "Professional-advice disclaimer (consult a qualified professional, informational purposes only)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "consult(?:ing)? (?:with )?(?:a|an|your) (?:qualified|professional|licen[cs]ed|certified|reputable|trusted|experienced)",
    "(?:seek|seeking) (?:professional|independent|expert|qualified|specialist|proper) (?:legal |financial |tax |medical )?(?:advice|guidance|counsel|help|assistance)",
    "does not constitute (?:legal|financial|tax|professional|investment|medical)",
    "for (?:informational|information|general|educational) purposes only",
    "(?:general|informational) (?:information|guidance) only",
    "it is (?:advisable|recommended|wise|prudent|best) to (?:seek|consult|obtain|speak|engage|check|verify)",
    "always (?:consult|check|verify|seek|speak|confirm|do your own)",
    "(?:do|conduct) your own (?:research|due diligence)",
    "not (?:legal|financial|tax|investment) advice",
    "(?:before|prior to) making (?:any|a|an) (?:decision|investment|commitment|purchase)"
   ]
  },
  {
   "key": "en_attrib_experts",
   "label": "Vague expert attribution (experts say, analysts believe, observers note)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:experts|analysts|observers|critics|commentators|insiders|specialists|economists|historians|researchers|industry (?:experts|insiders|observers|watchers|sources|leaders)|market (?:watchers|observers|experts)|local (?:experts|observers|sources)|sources close to) (?:say|suggest|believe|note|argue|agree|point out|warn|claim|caution|widely|generally|often|have long|have noted|have warned|have suggested|have pointed)",
    "(?:some|many|several|numerous|a number of|a growing number of) (?:experts|analysts|observers|critics|commentators|insiders|specialists|economists|locals|residents|investors|people|voices) (?:say|suggest|believe|feel|argue|agree|point|warn|see|consider|think|worry|fear)",
    "according to (?:some|many|various|several|numerous|industry|local|market|most|recent|experts|observers)(?: \\p{L}+)? ?(?:experts|sources|observers|estimates|reports|studies|analysts|insiders|locals|accounts|figures|surveys|research)?"
   ]
  },
  {
   "key": "en_attrib_many",
   "label": "Anonymous consensus (many believe, it is widely known, some say)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:many|some|most|few|numerous) (?:people |locals |residents |visitors |travell?ers |investors |observers )?(?:believe|feel|argue|consider|say|think|regard|view|agree|see|claim|swear|insist|would argue|might say)(?: that)?",
    "it is (?:widely|generally|commonly|often|popularly|universally|broadly|increasingly) (?:believed|thought|said|known|regarded|considered|accepted|acknowledged|recogni[sz]ed|seen|agreed|reported|understood|assumed|perceived)",
    "(?:it has been|it(?:'|’)s been|it is) (?:said|argued|suggested|noted|claimed|reported|rumou?red|speculated)",
    "(?:is|are) (?:often|widely|generally|commonly|popularly) (?:regarded|considered|seen|described|hailed|called|dubbed|touted|cited|viewed|thought)(?: as)?",
    "(?:the )?(?:consensus|general (?:view|feeling|sentiment|opinion)) (?:is|seems|among)",
    "(?:what )?(?:many|some) (?:call|consider|describe|see as|regard as)",
    "(?:what )?(?:locals|residents|visitors|travell?ers|expats|critics|fans|foodies|connoisseurs) (?:call|consider|describe|swear by|love|rave about|agree|say)"
   ]
  },
  {
   "key": "en_attrib_studies",
   "label": "Unsourced research claim (studies show, research suggests, data indicates)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:studies|research|surveys|reports|data|evidence|statistics|figures|analysis|analyses|trends|findings) (?:show|shows|suggest|suggests|indicate|indicates|have shown|has shown|reveal|reveals|point to|points to|consistently show|demonstrate|demonstrates|confirm|confirms|highlight|highlights|imply|implies)(?! (?:that )?(?:\\d|€|£|\\$|in (?:the )?\\d))",
    "(?:recent|latest|new|various|several|numerous|growing|available|emerging|independent|international) (?:studies|research|surveys|reports|data|evidence|analyses|findings)",
    "(?:a )?(?:growing|increasing|rising) (?:body of )?(?:evidence|research|data|number of (?:studies|reports|surveys))",
    "(?:statistics|figures|numbers|data) (?:speak|tell)"
   ]
  },
  {
   "key": "en_vague_growth",
   "label": "Vague growth and demand claims (significant growth, rising demand, growing interest)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:significant|substantial|considerable|notable|sizeable|sizable|remarkable|dramatic|marked|steady|sharp|robust|strong|healthy|impressive|continued|sustained|exponential)(?:ly)? (?:growth|increase|rise|surge|uptick|interest|demand|boost|improvement|expansion|momentum|upswing|jump|spike)",
    "(?:growing|increasing|rising|surging|mounting|renewed|heightened|enduring|strong) (?:interest|demand|popularity|appetite|trend|number|awareness|attention|momentum|focus|pressure|appeal|concern)",
    "(?:more and more|increasing(?:ly)?|ever more|ever-more|ever greater) (?:people|residents|investors|expats|travell?ers|visitors|buyers|tourists|locals|families|couples|businesses|companies|popular|important|sought|attractive)",
    "(?:in|over|during) (?:recent|the (?:past|last)(?: few| several)?) (?:years|months|decades|times)"
   ],
   "min": 2
  },
  {
   "key": "en_superlative_one_of",
   "label": "“One of the most / best / finest …” superlative filler",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "one of the (?:most|best|finest|top|world(?:'|’)s|island(?:'|’)s|region(?:'|’)s|oldest|largest|biggest|leading|few|greatest|loveliest|prettiest)",
    "(?:the )?(?:finest|premier|ultimate|foremost|most (?:sought-after|beautiful|stunning|iconic|renowned|prestigious|exclusive|exquisite|celebrated|coveted|admired|picturesque|enchanting))",
    "(?:second to none|unrivalled|unrivaled|unmatched|unsurpassed|peerless|without equal|like no other|unlike any other)"
   ],
   "min": 2
  },
  {
   "key": "en_drama",
   "label": "Dramatic-pivot phrases (no accident, here’s the catch, the real story is)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "no (?:accident|coincidence)",
    "no (?:small|mean) (?:feat|wonder|matter)",
    "here(?:'|’)s the (?:thing|catch|kicker|twist|rub|problem|question)",
    "(?:and )?that(?:'|’)s (?:exactly|precisely) (?:the point|what|where|why|how)",
    "the (?:real|true|actual) (?:story|magic|secret|test|challenge|question|draw|star|prize) (?:is|lies|here|isn(?:'|’)t)",
    "(?:but|and) that(?:'|’)s not all",
    "(?:the )?plot thickens",
    "fast[- ]forward to",
    "(?:and )?(?:here(?:'|’)s|this is) (?:where|why) (?:it|things|that) (?:gets|get|becomes|matters|really)",
    "(?:but )?(?:why|how) (?:does|did|is|do|are|can|could) (?:this|that|it|all this) matter"
   ]
  },
  {
   "key": "en_pivot_colon",
   "label": "Pivot with colon or question (The result? / The verdict: / The catch:)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "the (?:result|verdict|answer|truth|reality|catch|upshot|takeaway|bottom line|point|key|lesson|problem|solution|upside|downside|good news|bad news|secret|trick|twist|difference|outcome|reason|payoff|surprise)(?: is| was)?[:?]",
    "the (?:result|verdict|answer|catch|outcome|reason|surprise)\\?",
    "(?:why|how|what|where|who)\\? (?:because|simple|it|the|by)",
    "simple(?:\\.|:| as that)"
   ],
   "min": 2
  },
  {
   "key": "en_cy_jewel",
   "label": "Cyprus travel cliché (jewel of the Mediterranean, island of love, gateway to…)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:jewel|pearl|gem|crown jewel|crown|treasure) (?:of|in) the (?:mediterranean|east|eastern mediterranean|aegean|levant)",
    "island of (?:love|aphrodite|venus|eternal|legends|gods|sun|contrasts|saints and sages)",
    "gateway to (?:europe|the (?:middle )?east|three continents|the mediterranean|asia|africa|the levant)",
    "(?:cradle|birthplace|crucible) of (?:civili[sz]ation|western|culture|myth)",
    "crossroads of (?:three continents|europe,? asia|east and west|civili[sz]ations|cultures|empires|trade)",
    "where east meets west",
    "(?:east|west) (?:meets|meet|and west meet)",
    "(?:meeting|melting) (?:point|pot) of (?:cultures|civili[sz]ations|east and west|peoples|traditions)",
    "melting pot",
    "(?:steeped|rooted|ingrained|immersed|enshrined|swathed|wrapped|drenched|awash) in (?:history|myth|legend|tradition|culture|heritage|centuries|ancient|mythology)",
    "(?:storied|illustrious|fabled|legendary|mythical|mythic) (?:past|history|heritage|island|shores|coastline|land)",
    "(?:land|island|isle) of (?:sun|myth|legend|contrasts|eternal summer|aphrodite)",
    "(?:birthplace|home) of aphrodite"
   ]
  },
  {
   "key": "en_cy_sun",
   "label": "Sun-and-sea cliché (sun-kissed, golden sands, azure waters)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "sun-?(?:kissed|drenched|soaked|baked|splashed|bathed|lit|filled|washed|dappled)",
    "sunkissed",
    "golden (?:sands?|beaches|shores?|sunsets?|sunshine|hues?|light|glow|rays|stretches|coves?)",
    "(?:azure|turquoise|crystal[- ]clear|cobalt|emerald|sapphire|glittering|sparkling|shimmering|pristine|translucent|aquamarine|cerulean|limpid|jewel-toned) (?:waters?|seas?|blue|bays?|coves?|shores?|beaches|coastline|lagoons?|depths)",
    "(?:endless|year-round|abundant|glorious|unrelenting|radiant|blazing|brilliant|generous|warm) (?:sunshine|summer|sunlight|sun)",
    "(?:over |more than |nearly |almost |around )?3\\d\\d days of (?:sunshine|sun)",
    "(?:white|powdery|soft|silky|fine) (?:sands?|sandy beaches)",
    "lapping (?:at|against|on) the shore",
    "(?:sun|sea) and (?:sand|sea|surf)",
    "(?:soak|bask) (?:up|in) the (?:sun|rays|sunshine|atmosphere|views|beauty|culture)",
    "mediterranean (?:sun|breeze|charm|magic|light|paradise|lifestyle|way of life|dream|glow|escape)"
   ]
  },
  {
   "key": "en_cy_tapestry",
   "label": "Cultural-fabric metaphor (rich tapestry, mosaic of cultures, kaleidoscope)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:rich|vibrant|colou?rful|intricate|cultural|diverse|woven|vivid|living|dazzling|fascinating)(?:ly woven)? (?:tapestry|mosaic|kaleidoscope|patchwork|palette|fabric|weave|canvas|blend)",
    "(?:tapestry|mosaic|kaleidoscope|patchwork|palette|fabric|weave|melting pot|cocktail) of (?:cultures|traditions|influences|flavou?rs|colou?rs|histories|peoples|experiences|communities|styles|sounds|aromas|civili[sz]ations|nationalities)",
    "(?:tapestry|fabric) of (?:life|society|history|the island|cypriot)",
    "cultural (?:mosaic|crossroads|melting pot|fusion|richness|diversity|heritage|tapestry|identity)",
    "(?:woven|interwoven|intertwined) (?:into|through|with) the (?:fabric|tapestry|story|history)"
   ]
  },
  {
   "key": "en_cy_blend",
   "label": "Tradition-meets-modernity formula (blend of old and new)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:blend|blending|fusion|marriage|harmony|juxtaposition|interplay|meeting|mix|mingling|melding|combination|union|dialogue|balance|synthesis|dance|conversation|tension) (?:of|between) (?:\\p{L}+ ){0,2}(?:tradition|traditional|old|ancient|history|heritage|past|east|classic|timeless|old-world|time-honou?red)(?: and | & |, )(?:\\p{L}+ ){0,2}(?:modern|modernity|contemporary|innovation|new|future|west|present|cutting|fresh|today)",
    "(?:tradition|history|heritage|the old|the ancient|old-world|the past)(?: and |meets | meets | meet | embraces | blends with | collides with )(?:modernity|modern|innovation|the new|contemporary|the future|the present|progress|today)",
    "(?:where|as) (?:tradition|ancient|history|old|the past|heritage)(?: \\p{L}+){0,3} (?:meets?|embraces?|blends?|collides?|dances?|marries|mingles?) (?:with )?(?:the )?(?:modern|innovation|new|contemporary|future|present)",
    "(?:old|ancient) (?:meets|and) new",
    "(?:honou?rs|honou?ring|respects|respecting|embraces|embracing|celebrates) (?:tradition|heritage|the past|its roots)(?: while| whilst| and| yet|,)? (?:embracing|looking|moving|pushing|reaching|welcoming|stepping|celebrating|honou?ring|adding|bringing) (?:\\p{L}+ ){0,2}(?:modern|innovation|future|new|contemporary|forward|today|progress)",
    "rooted in tradition",
    "timeless (?:yet|and) (?:modern|contemporary)",
    "modern twist",
    "contemporary twist",
    "fresh take"
   ]
  },
  {
   "key": "en_cy_hospitality",
   "label": "Hospitality and pace cliché (warm Cypriot hospitality, laid-back lifestyle)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?:warm|famed|legendary|renowned|traditional|genuine|proverbial|world-famous|famous|generous|heart-?warming|unrivalled|legendary|authentic) (?:cypriot |greek |mediterranean |island )?(?:hospitality|welcome|warmth|generosity|spirit|charm)",
    "(?:laid-back|relaxed|slow-paced|unhurried|leisurely|easy-going|easygoing|carefree|slow) (?:lifestyle|pace|way of life|atmosphere|vibe|rhythm|island|living)",
    "(?:island|mediterranean|cypriot|slow) (?:life|living|lifestyle|time|rhythm)",
    "(?:philoxenia|filoxenia)",
    "(?:charming|quaint|sleepy|picture-postcard|postcard-perfect|traditional|authentic|unspoilt|unspoiled) (?:village|villages|hamlet|hamlets|alleyways|taverna|tavernas|fishing village|harbour|harbor|mountain village)",
    "step (?:back )?(?:into|in) (?:time|the past|history)",
    "time (?:seems|appears|stands|has) (?:to )?(?:stand|stood|stopped|slowed|slow)",
    "frozen in time"
   ],
   "min": 2
  },
  {
   "key": "en_cy_offpath",
   "label": "Hidden-corner cliché (off the beaten track, best-kept secret, tucked away)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "off the beaten (?:path|track)",
    "hidden (?:corners?|treasures?|villages?|beaches|coves?|spots?|nooks?|jewels?|delights?|wonders?|oasis|paradise|sanctuary|haven|retreat|world|side|depths)",
    "(?:best-kept|well-kept|closely guarded|open) secrets?",
    "undiscovered",
    "local secrets?",
    "tucked away",
    "secret spots?",
    "insider(?:'|’)?s? (?:tip|guide|secret|favourite|favorite|view|knowledge)",
    "(?:away|far) from the (?:crowds|tourist trail|beaten track|madding crowd|tourist hordes|tourist crowds)",
    "(?:escape|retreat) (?:from|the) (?:the )?(?:hustle|crowds|daily|everyday|ordinary|noise|city|stress|bustle)",
    "hustle and bustle",
    "tourist trail",
    "under the radar"
   ]
  },
  {
   "key": "en_travel_immerse",
   "label": "Immersion and bucket-list cliché (immerse yourself, bucket list, lasting memories)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "immerse (?:yourself|yourselves|oneself)",
    "immersive (?:experience|journey|adventure|escape|stay|world)",
    "soak (?:up|in)",
    "bask in",
    "lose yourself in",
    "get lost in",
    "feast your eyes",
    "bucket[- ]list",
    "(?:memories|moments|experiences) (?:that )?(?:will )?last a lifetime",
    "(?:create|creating|make|making|build|building) (?:lasting|unforgettable|lifelong|lifetime|beautiful|cherished)? ?memories",
    "(?:a|an) (?:unforgettable|once-in-a-lifetime|magical|truly (?:special|unique|memorable)) (?:experience|journey|adventure|escape|getaway|stay|holiday|vacation|trip|time|evening|night|day)",
    "treat yourself",
    "(?:sure|bound) to (?:fall in love|be (?:impressed|charmed|delighted|captivated))",
    "fall in love with",
    "(?:spoilt|spoiled) for choice",
    "(?:tick|check) (?:all|every) (?:the )?box(?:es)?",
    "(?:something|a little something|a bit of something) for (?:everyone|everybody|all)",
    "there(?:'|’)s something for everyone",
    "cater(?:s|ing)? (?:to|for) (?:all|every|every taste|all tastes|all ages|everyone)",
    "for (?:all|every) (?:tastes|budgets|ages|palates|occasions)",
    "(?:haven|paradise|playground|mecca|magnet|dream) for (?:\\p{L}+ )?(?:lovers|enthusiasts|seekers|travell?ers|foodies|adventurers|families|divers|hikers|bird\\p{L}*|golfers|sailors|shoppers|walkers|cyclists|surfers)"
   ]
  },
  {
   "key": "en_you_hype",
   "label": "Second-person hype (awaits you, waiting to be discovered, invites you to)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:awaits|await) (?:you|visitors|guests|travell?ers|diners|those)",
    "waiting (?:for you|to be (?:discovered|explored|savou?red|enjoyed|uncovered|experienced|unwrapped|found))",
    "invit(?:e|es|ing) (?:you|visitors|guests|travell?ers|diners|readers|everyone) to",
    "indulge your",
    "(?:your|the) (?:senses|taste buds|inner (?:foodie|explorer|adventurer|child)|wanderlust|palate|soul)",
    "you(?:'|’)re (?:sure|bound) to",
    "(?:you(?:'|’)ll|you will) (?:be|feel) (?:spoilt|spoiled|transported|hooked|captivated|mesmeri[sz]ed|enchanted|charmed|delighted|swept)",
    "(?:transport(?:s|ed)?|takes?) you (?:to|back|straight)",
    "you(?:'|’)ll (?:fall in love|never want|want to stay|wish you)",
    "(?:let|allow) (?:yourself|your) (?:to )?(?:be )?(?:swept|carried|transported|lulled|seduced)"
   ]
  },
  {
   "key": "en_food_cliche",
   "label": "Food-writing cliché (mouth-watering, culinary journey, explosion of flavours)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "mouth-?watering",
    "delectable",
    "scrumptious",
    "tantali[sz](?:e|es|ing)",
    "lip-?smacking",
    "finger-?licking",
    "culinary (?:journey|delights?|adventure|odyssey|scene|landscape|experience|treasures?|heritage|tapestry|gem|artistry|mastery|prowess|excellence|offerings|wonders?|masterpieces?)",
    "gastronomic (?:journey|delights?|adventure|odyssey|experience|excellence|heritage|treasures?|offerings)",
    "taste ?buds",
    "(?:foodie|food lover|food-lover)s?(?:'|’)? (?:paradise|heaven|haven|dream|delight)",
    "farm-to-table",
    "fresh,? (?:local )?(?:and )?(?:seasonal )?ingredients",
    "(?:locally|locally-)sourced",
    "bursting with (?:flavou?r|taste|freshness|life)",
    "(?:explosion|burst|riot|symphony|medley|celebration|kaleidoscope|melody) of (?:flavou?rs?|tastes?|textures?|aromas|colou?rs|spices)",
    "dance on (?:your|the) (?:tongue|palate)",
    "melts? in (?:your|the) mouth",
    "(?:feast|treat) for (?:the )?(?:senses|palate|eyes|taste buds)",
    "(?:authentic|traditional|genuine|true) (?:cypriot|greek|mediterranean|island)(?: \\p{L}+)? (?:flavou?rs?|cuisine|taste|fare|cooking|recipes?)",
    "(?:comfort food|hearty fare|home-?style|home-?cooked) (?:at its best|favourites|favorites)",
    "elevated (?:dining|cuisine|comfort|classics|take|twist)",
    "(?:ever-changing|seasonal) menu"
   ]
  },
  {
   "key": "en_fashion_cliche",
   "label": "Fashion and design cliché (effortless chic, timeless elegance, statement piece, elevate)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "effortless(?:ly)? (?:chic|elegant|stylish|cool|glamour|style|sophistication|elegance|luxury|beauty)",
    "timeless (?:elegance|style|appeal|design|charm|beauty|sophistication|classic|silhouette|piece|craftsmanship)",
    "understated (?:elegance|luxury|glamour|style|chic)",
    "quiet luxury",
    "statement (?:piece|pieces|jewellery|jewelry|accessor(?:y|ies)|silhouette|look|making)",
    "wardrobe (?:staple|essential|must-have)",
    "sartorial",
    "must-haves?",
    "(?:elevated|elevate|elevating) (?:\\p{L}+ ){0,2}(?:wardrobe|look|style|style game|everyday|experience|dining|stay|space|living|your|the)",
    "(?:redefin(?:e|es|ed|ing)|reimagin(?:e|es|ed|ing)) (?:luxury|elegance|style|the way|what|how|modern|dining|hospitality|the concept|the idea|the art)",
    "(?:a )?(?:curated|carefully curated|handpicked|hand-picked) (?:selection|collection|edit|range|mix|line-up|lineup|list)",
    "(?:crafted|designed|made|created) with (?:care|passion|love|attention|precision)",
    "attention to detail",
    "(?:impeccable|exquisite|refined|discerning) (?:taste|craftsmanship|finish|detailing|tailoring|style|eye)",
    "(?:head-turning|show-stopping|showstopping|eye-catching|scene-stealing|jaw-dropping)",
    "(?:chic|stylish|sophisticated|elegant) (?:yet|and) (?:comfortable|casual|relaxed|understated|practical|laid-back|playful|timeless)",
    "(?:a )?touch of (?:glamour|elegance|luxury|class|sophistication|flair|magic|whimsy|drama)",
    "(?:exudes?|exuding|radiates?|radiating|oozes?|oozing) (?:charm|elegance|luxury|sophistication|glamour|style|class|confidence|warmth|personality)"
   ]
  },
  {
   "key": "en_review_cliche",
   "label": "Review and recommendation cliché (does not disappoint, not to be missed, worth every penny)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:a )?(?:must|real) (?:see|watch|listen|read|try|visit|have)",
    "(?:does not|doesn(?:'|’)t|did not|didn(?:'|’)t) disappoint",
    "(?:will|is sure to|is bound to|promises to|set to) (?:delight|impress|captivate|enchant|mesmeri[sz]e|appeal to|leave you|please|charm|dazzle|thrill|wow)",
    "leaves? (?:a )?(?:lasting )?(?:impression|you wanting more|you breathless|you speechless|you spellbound|you hungry|you craving)",
    "hits? all the right notes",
    "(?:a )?(?:triumph|tour de force|masterclass)",
    "(?:visual|sensory|culinary|musical|cultural|artistic) (?:feast|treat|spectacle|delight|extravaganza|journey|banquet|odyssey|experience)",
    "(?:truly|really) (?:shines|stands out|delivers|impresses|stands apart|excels|sets itself apart)",
    "(?:delivers?|deliver) on (?:its promise|every front|all fronts|all counts|its promises)",
    "(?:raises?|sets?) the bar",
    "worth every (?:penny|cent|euro|minute|moment|second|mile|bite|sip)",
    "(?:highly|wholeheartedly|heartily|warmly|strongly|unreservedly) recommend(?:ed)?",
    "(?:can(?:'|’)t|cannot) recommend (?:it|this|them) enough",
    "not to be missed",
    "(?:unmissable|can(?:'|’)t-miss|must-attend|must-read|must-watch|must-try|must-have|must-do)",
    "(?:be sure|make sure) to (?:book|check|visit|try|catch|stop|arrive|bring|reserve|order)",
    "(?:don(?:'|’)t|do not) miss (?:out )?(?:on|the)",
    "(?:five|four|three|5|4|3)(?:-| )stars?",
    "leaves? (?:a )?(?:lasting )?(?:impression|you wanting more)",
    "(?:a )?(?:feast|treat|joy|delight|pleasure|revelation|gem) (?:for|to) (?:the )?(?:senses|eyes|ears|palate|taste ?buds|watch|behold|visit|experience)",
    "(?:leaves?|left) (?:a )?(?:bad|sour|bitter|mixed) taste",
    "(?:ticks?|ticked) (?:all|every) (?:the )?box"
   ]
  },
  {
   "key": "en_events_cliche",
   "label": "Events-listing cliché (promises to be unforgettable, mark your calendars, something for all ages)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:promises?|promised) (?:to be )?(?:an? )?(?:unforgettable|memorable|spectacular|magical|extraordinary|exciting|evening|night|treat|feast|thrilling|dazzling|special)",
    "(?:an? )?(?:evening|night|day|weekend|event|festival|afternoon|season) (?:to remember|of (?:music|culture|food|wine|art|fun|fine|magic|celebration|laughter|joy|discovery))",
    "set to (?:captivate|delight|dazzle|enchant|thrill|take place|return|kick off|light up|take over|take centre stage)",
    "(?:bringing|brings) together (?:\\p{L}+ ){0,4}(?:from (?:across|around|all over)|of all ages|under one roof|from all walks)",
    "(?:something|fun|entertainment|activities) for (?:all ages|the whole family|everyone|the little ones|young and old)",
    "(?:young and old|all ages|all walks of life|the whole family)",
    "(?:join us|come and (?:join|enjoy|experience|celebrate|see)|come along)",
    "(?:mark|save) (?:your calendars?|the date)",
    "(?:calling all|calling)\\s+\\p{L}+",
    "(?:the )?(?:highly )?anticipated (?:event|return|festival|opening|show|concert|exhibition|edition|season)",
    "(?:celebrat(?:es|ing)|honou?rs|showcases?) (?:the )?(?:rich|vibrant|diverse|best|finest|spirit|unique|talent|creativity|culture|heritage)",
    "(?:kicks? off|kicking off|gets? underway|gearing up|buzz(?:es|ing)? with excitement|gets? under way|returns? (?:this|next) (?:year|month|summer|autumn|spring|winter))",
    "(?:line-?up|programme|program) (?:features|includes|boasts|promises|packed)",
    "(?:packed|jam-packed|action-packed|star-studded|fun-filled) (?:with|programme|program|line-?up|schedule|calendar|weekend|day|evening)"
   ]
  },
  {
   "key": "en_interview_cliche",
   "label": "Profile and interview cliché (sat down with, opens up about, humble beginnings, the man behind)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:in a )?candid(?:ly)?(?: (?:conversation|interview|chat|exchange|moment|reflection|discussion|talk))?",
    "(?:in an? )?(?:exclusive|intimate|wide-ranging|heartfelt|frank|revealing|rare|far-reaching) (?:interview|conversation|chat|sit-down|discussion|exchange|talk)",
    "(?:we )?sat down with",
    "opens? up (?:about|on|to)",
    "opened up (?:about|on|to)",
    "(?:reflects?|reflected|reflecting) on (?:his|her|their|the) (?:journey|career|path|experience|life|years|story|legacy|success)",
    "(?:journey|path|road|rise) (?:to|from) (?:success|stardom|prominence|fame|the top|obscurity|rags|humble)",
    "humble beginnings",
    "rose? to (?:prominence|fame|stardom|the top)",
    "rise to (?:fame|prominence|stardom|the top)",
    "household name",
    "trail-?blaz(?:er|ing)",
    "visionary",
    "thought leader",
    "true original",
    "industry veteran",
    "(?:the )?(?:man|woman|mind|force|face|hands|heart|brains|genius|talent|visionary|creative|voice|architect) behind",
    "passion project",
    "labou?r of love",
    "(?:fuelled|fueled|driven|powered|propelled|inspired) by (?:a )?(?:passion|love|desire|vision|commitment|curiosity|dream|belief|determination)",
    "(?:lifelong|burning|deep-seated|unwavering|boundless|insatiable|unshakeable|unshakable|abiding|deep) (?:passion|love|commitment|curiosity|dedication|dream|belief|determination|desire|devotion)",
    "wears? many hats",
    "needs? no introduction",
    "no stranger to",
    "(?:a )?(?:rising|shining) star",
    "(?:a )?force to be reckoned with",
    "(?:leaves?|left|made|make|makes) (?:his|her|their) mark",
    "(?:follow(?:ing|ed)?|pursu(?:e|ing|ed)) (?:his|her|their) (?:passion|dreams?|calling|heart|vision)",
    "(?:what|how) (?:drives|inspires|motivates|moves|fuels|keeps) (?:him|her|them)",
    "at the (?:forefront|helm) of",
    "(?:pioneer(?:ing)?|trailblazing|game-changing|ground-?breaking|award-winning|acclaimed|celebrated|renowned|esteemed|distinguished|seasoned|visionary|innovative)\\s+(?:chef|artist|designer|architect|photographer|sommelier|winemaker|musician|entrepreneur|founder|creator|curator|restaurateur|hotelier|developer|lawyer|philanthropist|maker|craftsman|craftswoman|couturier|gallerist|filmmaker|producer|director|painter|sculptor|ceramicist|potter|weaver)"
   ]
  }
 ],
 "banned": [
  "delve into",
  "nestled in the heart of",
  "tapestry",
  "a testament to",
  "plays a crucial role",
  "plays a pivotal role",
  "underscores",
  "highlights the importance of",
  "it is worth noting",
  "it’s important to note",
  "in today’s fast-paced world",
  "ever-evolving landscape",
  "navigate the complexities of",
  "a myriad of",
  "a plethora of",
  "seamless",
  "meticulous",
  "cutting-edge",
  "state-of-the-art",
  "boasts",
  "serves as",
  "stands as",
  "pivotal",
  "paramount",
  "indispensable",
  "multifaceted",
  "holistic",
  "intricate",
  "nuanced",
  "realm",
  "ecosystem",
  "synergy",
  "leverage",
  "foster",
  "garner",
  "bolster",
  "spearhead",
  "cornerstone",
  "beacon",
  "epitome",
  "quintessential",
  "iconic",
  "timeless",
  "curated",
  "game-changer",
  "paradigm shift",
  "unlock the potential",
  "elevate your",
  "embark on a journey",
  "look no further",
  "hidden gem",
  "jewel of the Mediterranean",
  "island of love",
  "sun-kissed",
  "golden sands",
  "azure waters",
  "crystal-clear waters",
  "rich tapestry",
  "melting pot",
  "blend of tradition and modernity",
  "where East meets West",
  "crossroads of civilisations",
  "steeped in history",
  "warm Cypriot hospitality",
  "laid-back lifestyle",
  "off the beaten track",
  "best-kept secret",
  "vibrant",
  "bustling",
  "breathtaking",
  "stunning",
  "picturesque",
  "unforgettable",
  "world-class",
  "unparalleled",
  "feast for the senses",
  "symphony of flavours",
  "culinary journey",
  "mouth-watering",
  "tantalising",
  "immerse yourself",
  "something for everyone",
  "bucket list",
  "creating lasting memories",
  "perfect blend of",
  "strategic location",
  "prime location",
  "ideal for investors",
  "a lucrative opportunity",
  "savvy investors",
  "thriving",
  "poised for growth",
  "turnkey",
  "luxury living",
  "commitment to excellence",
  "passionate about",
  "tailored solutions",
  "industry-leading",
  "delighted to announce",
  "going forward",
  "whether you’re",
  "not only … but also",
  "it’s not just … it’s",
  "more than just",
  "moreover",
  "furthermore",
  "additionally",
  "in addition",
  "notably",
  "importantly",
  "firstly … secondly",
  "key takeaways",
  "things to consider",
  "in terms of",
  "when it comes to",
  "in the world of",
  "at the end of the day",
  "that being said",
  "in conclusion",
  "in summary",
  "to sum up",
  "overall",
  "ultimately",
  "only time will tell",
  "the future looks bright",
  "remains to be seen",
  "watch this space",
  "here’s what you need to know",
  "let’s dive in",
  "in this guide",
  "read on",
  "experts say",
  "many believe",
  "it is widely believed",
  "studies show",
  "growing interest",
  "rising demand",
  "consult a qualified professional",
  "for informational purposes only",
  "it depends on a number of factors",
  "I hope this helps",
  "as an AI",
  "Certainly!",
  "Here is the revised"
 ],
 "closers": [
  "In conclusion,",
  "In summary,",
  "To sum up,",
  "To summarise,",
  "To conclude,",
  "In short,",
  "In essence,",
  "In the end,",
  "All in all,",
  "Overall,",
  "Ultimately,",
  "On balance,",
  "Taken together,",
  "Looking ahead,",
  "Looking forward,",
  "The bottom line is",
  "The key takeaway is",
  "What is clear is",
  "One thing is certain:",
  "At the end of the day,",
  "When all is said and done,",
  "As Cyprus continues to evolve,",
  "So whether you are",
  "Final thoughts",
  "Wrapping up",
  "There you have it:",
  "It remains to be seen",
  "Only time will tell",
  "The future looks bright for"
 ],
 "openers": [
  "Here is what you need to know",
  "Here’s everything you need to know",
  "Here’s the short version",
  "Let’s take a closer look",
  "Let’s dive into",
  "Let’s explore",
  "Welcome to",
  "Whether you are a … or a …,",
  "If you are looking for",
  "If you are planning",
  "Are you looking for",
  "Have you ever wondered",
  "Imagine waking up to",
  "Picture this:",
  "In today’s fast-paced world,",
  "In an era of",
  "When it comes to",
  "In the world of",
  "Nestled in the heart of",
  "Perched above the sea,",
  "Boasting a rich history,",
  "Cyprus, the jewel of the Mediterranean,",
  "It’s no secret that",
  "It goes without saying that",
  "In recent years,",
  "From … to …, Cyprus offers",
  "Few places capture … quite like",
  "In this guide, we will"
 ],
 "sheet": [
  "Open with the news itself: who did what, where and when, in the first sentence, in under 30 words. Context, colour and background come after the fact, never before it.",
  "In a news item the second paragraph answers the reader’s first question (so what? why now? how much?). Do not spend it on background or on a quote that restates the lead.",
  "In features, open on a single observed scene or a single hard fact (a price, a date, a number of seats, a temperature) rather than on a thesis about Cyprus or about life.",
  "Never begin with the weather, the sea, the light or the island’s reputation unless the story is literally about them. Cyprus is the setting, not the subject.",
  "Prefer a concrete verb to a noun phrase and a plain verb to a decorated one: “opened”, “sold”, “cut”, “fined”, “moved”, not “marked the launch of” or “underwent a transformation”.",
  "Use “is”, “has” and “was” without shame. Do not swap them for “serves as”, “stands as”, “boasts”, “features”, “represents” or “offers”. A hotel has 40 rooms; it does not “boast” them.",
  "Vary sentence length by intention. Let one idea take a short sentence, let a chain of events run long, and follow a long sentence with a short one. Never write three sentences of the same length and shape in a row.",
  "Vary paragraph length too: a one-sentence paragraph is allowed, a nine-line block is allowed. Never let four consecutive paragraphs run to the same length.",
  "Do not start consecutive sentences or paragraphs with the same word. Do not open paragraphs with sentence adverbs (“Notably,” “Importantly,” “Moreover,” “Additionally,”). Join paragraphs by logic and by the next fact, not by a connector.",
  "No participial tail clauses that comment on the sentence (“…, highlighting the importance of…”, “…, ensuring that…”, “…, reflecting a broader shift…”). If the point matters, give it its own sentence with a subject and a verb and a fact.",
  "No “not only X but also Y”, no “it’s not just X, it’s Y”, no “less about X than Y”. State what the thing is.",
  "Avoid the list of three as a reflex. Two items or four items are fine; three abstract nouns in a row (“innovation, creativity and tradition”) are not. Give one example instead of three labels.",
  "Never end a paragraph on a tidy aphorism. When the point has been made, stop.",
  "Attribute by name, title and date: “Andreas Mavrou, the Cyprus Hoteliers Association’s director-general, told the Cyprus Mail on Tuesday”. Never “experts say”, “many believe”, “it is widely thought”, “studies show”. If there is no named source, state the claim as the writer’s own observation or leave it out.",
  "Quote sparingly and exactly. Introduce a quotation with “said” or “told”, placed after the first clause. Quote the sentence that has a person in it, not the sentence that has a policy in it; paraphrase the policy.",
  "Never invent a quotation, a statistic, a price, an opening time or a name. When a figure is not in the material, cut the sentence; do not write “significant”, “substantial” or “growing” in its place.",
  "Give numbers their unit, date and source in the same sentence: “€1,450 a month for a one-bedroom flat in Strovolos, according to listings on Bazaraki in September”. Write figures as figures from 10 upward, words below ten, and always spell out a number that starts a sentence.",
  "Prefer one precise specific to three vague ones: the street, the dish, the grape, the clause number, the minute of the bus. A reader trusts the writer who knows the name of the lane.",
  "Use British spelling and punctuation: organisation, programme, licence (noun), centre, single quotation marks for speech in news copy, “the Republic of Cyprus”, “the Cyprus Mail” in italics where house style does so.",
  "Do not use em dashes or spaced en dashes. Use a comma, a colon, a full stop or a pair of brackets. Use an en dash only in ranges (9–11 June) and a hyphen only in compounds.",
  "Use straight or curly quotation marks consistently, never both in one piece. Use single quotes for speech and double inside them, or the house reverse, and hold it throughout.",
  "Use sentence case in headings and subheadings, never Title Case. A subheading is a statement of content (“The permit takes eleven weeks”), not a template label (“What it costs”, “Who can apply”, “Final thoughts”).",
  "Do not build an article from a fixed set of repeating H2s (What it is, Who it is for, What it costs, How to apply). Let the story dictate its headings, and use none in anything under 600 words.",
  "No bold-lead bullets (“**Location:** …”), no colon-led labels at the start of paragraphs, no emoji, no hashtags, no horizontal rules, no markdown tables unless the data is a genuine table and the desk asks for it.",
  "Write continuous prose in an article. Use a list only for items that are truly parallel (documents to bring, opening hours) and keep each item a full, specific line.",
  "Do not signpost the article (“in this guide”, “as we will see”, “let’s take a look”) and do not address the reader with “whether you are an investor or a family”. Tell the reader the facts; they will place themselves.",
  "End on the last concrete fact, a forward date, a line of dialogue or a small image, never on a summary, a moral, “the future looks bright”, “only time will tell” or “watch this space”. If you have a deadline or a vote date, that is your ending.",
  "Write hedges once and where they are earned. “Could” and “may” belong to genuine uncertainty, once per claim, never stacked (“may potentially help to some extent”). If the rule is clear, say so flatly; if it is unclear, say who disagrees.",
  "No legal or financial disclaimer boilerplate (“consult a qualified professional”). Where advice is needed, say which professional (a lawyer registered with the Cyprus Bar Association, a licensed estate agent, the Land Registry) and for what step.",
  "Replace every hype adjective with the fact behind it. Not “stunning views” but “you can see Troodos snow from the terrace in February”. Not “a vibrant food scene” but “eleven new openings on Ledra Street since January”.",
  "Do not rely on stock Cyprus phrases: jewel of the Mediterranean, sun-kissed, golden sands, azure waters, rich tapestry, melting pot, blend of tradition and modernity, where East meets West. If a sentence would fit Malta or Crete by swapping a name, rewrite it with something only true here.",
  "Register by desk: reported and neutral for news, dry and numerate for business and economy, exact and cautious for law, practical and second-hand-free for guides, sensory and opinionated for food, culture and reviews. Do not let the warm register of a lifestyle piece leak into a legal explainer.",
  "Keep the editor’s hand invisible: no “here is the revised version”, no notes on word count, no offer of further help, no statement that the text was written or checked by a tool. The article is the only thing in the output."
 ],
 "pairs": [
  {
   "bad": "Nestled in the heart of Limassol, this stunning marina development boasts breathtaking views and serves as a testament to the city’s vibrant transformation.",
   "good": "Limassol Marina has 650 berths, a row of restaurants along its quay and, since June, a waiting list for boats over 40 metres.",
   "why": "Replaces a participial opener, copula avoidance and four hype words with countable facts."
  },
  {
   "bad": "Moreover, the new legislation plays a crucial role in strengthening the property sector, highlighting the government’s commitment to transparency.",
   "good": "The law, passed on 3 July, gives buyers the right to a title deed within six months of completion. Developers who miss the deadline face a fine of up to €50,000.",
   "why": "Cuts the empty connector, the “crucial role” formula and the participial comment; states the rule, the date and the penalty."
  },
  {
   "bad": "Experts say that Cyprus is becoming an increasingly popular destination for digital nomads, with growing interest from around the world.",
   "good": "The interior ministry issued 1,118 digital nomad visas last year, up from 764 in 2023, and most went to applicants from the UK, Israel and India.",
   "why": "Anonymous experts and “growing interest” give way to a named source, a figure and a comparison."
  },
  {
   "bad": "It’s not just a restaurant; it’s a culinary journey that tantalises the taste buds with an explosion of authentic flavours.",
   "good": "The kitchen at Pyrgos does one thing well: lamb kleftiko, sealed in paper and left in a clay oven for six hours until it slumps off the bone.",
   "why": "Replaces the contrast formula and food clichés with a dish, a method and a sensory result."
  },
  {
   "bad": "Whether you are an investor, a family or a retiree, Cyprus offers an ideal blend of tradition and modernity in a strategic location.",
   "good": "A two-bedroom flat in Paphos costs about €240,000, roughly a third less than a comparable one in Limassol, and the airport is twenty minutes away.",
   "why": "Drops the “whether you are” address, the stock blend and the location puffery for a price, a comparison and a distance."
  },
  {
   "bad": "The festival promises to be an unforgettable evening of music and culture for all ages, so mark your calendars!",
   "good": "The festival opens at 8pm on Friday at the Kourion amphitheatre, with the Cyprus Symphony Orchestra playing Mahler’s fifth. Tickets are €25, and the last bus back to Limassol leaves at 11.15pm.",
   "why": "Events copy needs time, place, programme, price and logistics, not exclamations."
  },
  {
   "bad": "The minister underscored the importance of the reform, reflecting a broader shift toward sustainable growth and paving the way for a brighter future.",
   "good": "“We have one year to bring the water authority’s losses below 30 per cent,” the minister told parliament on Tuesday. They stand at 46 per cent.",
   "why": "Swaps three participial abstractions for a direct quotation and the figure it relates to."
  },
  {
   "bad": "In conclusion, Cyprus remains a thriving hub that offers something for everyone, and the future looks bright for those who choose to call it home.",
   "good": "The next date to note is 31 October, when the current tax-residency window closes. After that the application fee rises from €300 to €500.",
   "why": "Replaces a summary closer and a moral with a forward date and a consequence."
  },
  {
   "bad": "It is important to note that results may vary depending on a number of factors, and it is advisable to consult a qualified professional before making any decision.",
   "good": "Processing took eleven weeks for two of our three applicants and five months for the third, whose file was missing a certified translation. A lawyer who files these weekly can tell you which documents the district office will bounce.",
   "why": "Replaces a hedge and boilerplate disclaimer with observed variation and the specific cause."
  },
  {
   "bad": "The collection features timeless pieces that exude effortless elegance, elevating every wardrobe with a perfect blend of comfort and sophistication.",
   "good": "The linen blazer is cut slightly long, the trousers have a high, plain waist, and everything is in four colours: chalk, tobacco, olive and a washed navy. Nothing costs more than €280.",
   "why": "Describes cut, colour and price instead of asserting elegance."
  }
 ],
 "desks": {
  "news": "British news copy: the fact in the first sentence, attribution by name and role, dates and figures attached, no adjectives of mood. Quote the person, paraphrase the policy; end when the last fact is delivered, never on a moral or a “time will tell”. Avoid “amid growing concerns”, “sparked debate”, “landmark decision” unless the source says it.",
  "business": "Dry, numerate, sceptical. Lead with the number or the decision, give the comparison (year on year, versus the EU average, versus the budget), name the company officer and the filing or release. No press-release register (delighted to announce, commitment to excellence, leading provider) and no “poised for growth” without a forecast and its source.",
  "property_legal": "Exact and cautious. State the rule, its source (law number, Land Registry or Interior Ministry circular), the date it applies from, the fee or penalty, and the step the reader takes next. Never “ideal for investors” or “strategic location”. Give one named professional for one named step, not a generic disclaimer. Explain terms (title deed, memorandum of sale, specific performance) on first use in one clause.",
  "relocation_guide": "Practical and second-hand-free: write as someone who has stood in the queue. Give prices in euro with the date, timings in weeks, the office and the document by name, and what goes wrong. Avoid “whether you are a family or a retiree”, avoid dreamy openers about sun and sea, and keep headings as statements of content, in sentence case.",
  "economy": "Explain the mechanism before the adjective: who pays, who gains, by how much, since when. Use official series (Cystat, Eurostat, the Central Bank of Cyprus) by name and month, and compare to a baseline. Report uncertainty once and precisely, with who disagrees, not in stacked hedges. No “thriving” or “booming” without a rate.",
  "culture": "Look, then judge. Name the work, the maker, the room, the date, and what you saw or heard that someone else would miss. Place the thing in a lineage of two or three precise references, not “rich cultural heritage”. Opinion is welcome if it is earned by description. Avoid “a testament to”, “a feast for the senses” and every tapestry.",
  "food": "Sensory, exact and opinionated. Name the dish, the producer, the cut, the temperature, the sound of the room, and the bill. Judge plainly: say what was too salty. Avoid “mouth-watering”, “culinary journey”, “authentic flavours” and “farm-to-table”; if the tomatoes come from a named grower, name him.",
  "fashion_lifestyle": "Cool and particular: cut, cloth, colour, maker, price, where to see it on a body. Strong opinions in short sentences, no “effortless chic”, “timeless elegance” or “statement piece”. Treat luxury as craft and cost, not as adjective, and let a single odd detail do the work of the mood.",
  "travel": "Be a person in a place: the road number, the bus time, the smell of the stairwell, the price of the coffee. Give an itinerary only after a story. Replace “hidden gem”, “sun-kissed” and “off the beaten track” with a named village and how long it took to reach it. One honest drawback per piece.",
  "events": "Service journalism with a spine: what, where, when, how much, how to get there and back, and one sentence on why it is worth going. Dates in full, times in 12-hour format with am/pm, ticket price and booking route. No exclamation marks, no “mark your calendars”, no “something for all ages”.",
  "interview": "Scene first (where, light, what the subject was doing), then voice. Let the subject say the surprising thing in their own words, set within narration that moves between subjects. Verbatim quotes only, introduced with “said” or “told”. Avoid “opens up”, “candid”, “humble beginnings” and the “man behind the brand” framing. End on an image or the last good line, not a summary.",
  "review": "Give the verdict early or make the reader wait for it deliberately, but give it. Describe what the object, meal, play or room is like with specifics (what was on the plate, the second act, the thread count), set against price and alternatives. Praise and fault must both be concrete. Avoid “does not disappoint”, “worth every penny”, “highly recommended”.",
  "people": "Report the person, not the brand: a decision they made, a thing they got wrong, a date, a number, a rival who disagrees. Let others characterise them through short, attributed observations. No “visionary”, “trailblazer” or “rising star”; if they are remarkable, the facts will show it. End on the next thing they will actually do and when."
 }
};

export default data;
