// GENERATED by scripts/voice/build-data.mjs from the PL linguist source. Edit the source data and regenerate; do not hand-edit.
import type { LangVoiceData } from '@/lib/voice/types';

const data: LangVoiceData = {
 "lang": "pl",
 "tells": [
  {
   "key": "pl_x_assistant_voice",
   "label": "Assistant voice / chatbot self-reference",
   "severity": "high",
   "kind": "word",
   "alts": [
    "jako (?:asystent|duży model|model sztucznej inteligencji|AI)",
    "nie mam (?:dostępu do|możliwości (?:przeglądania|sprawdzenia))",
    "moja (?:wiedza|data odcięcia)",
    "według mojej (?:wiedzy|aktualnej wiedzy)",
    "na (?:dzień|moment) (?:mojej|ostatniej) aktualizacji",
    "mój ostatni trening",
    "nie jestem w stanie (?:zweryfikować|potwierdzić|sprawdzić)"
   ]
  },
  {
   "key": "pl_x_offer_help",
   "label": "Chatbot offers of further help",
   "severity": "high",
   "kind": "word",
   "alts": [
    "(?:daj|dajcie) (?:mi )?znać,? (?:czy|jeśli|jeżeli|gdyby)",
    "czy (?:chcesz|chciałbyś|chciałabyś),? (?:abym|żebym|bym)",
    "chętnie (?:pomogę|dostosuję|poprawię|rozwinę|przygotuję)",
    "w razie (?:dodatkowych |jakichkolwiek )?pytań,? (?:daj|proszę|śmiało)",
    "mam nadzieję,? że (?:ten|ta|to) (?:artykuł|tekst|przewodnik|wpis|zestawienie)",
    "jeśli potrzebujesz (?:dalszej|dodatkowej|więcej) (?:pomocy|informacji)",
    "proszę,? (?:daj|dajcie) (?:mi )?znać"
   ]
  },
  {
   "key": "pl_x_placeholder",
   "label": "Template placeholder or meta label left in text",
   "severity": "high",
   "kind": "word",
   "alts": [
    "\\[(?:imię|nazwisko|nazwa|wstaw|data|miasto|link|źródło|cytat|Twoje|Twoja)[^\\]\\n]{0,40}\\]",
    "\\{\\{[^}\\n]{1,40}\\}\\}",
    "lorem ipsum",
    "tutaj (?:wstaw|dodaj|umieść)"
   ]
  },
  {
   "key": "pl_x_meta_label",
   "label": "Meta label at paragraph start (Tytuł:, Wstęp:, Meta opis:)",
   "severity": "high",
   "kind": "start",
   "alts": [
    "(?:tytuł|nagłówek|podtytuł|wstęp|zakończenie|meta ?opis|słowa kluczowe|lead|artykuł|treść)\\s*:",
    "(?:wersja|propozycja) (?:artykułu|tekstu|nagłówka)\\s*:"
   ]
  },
  {
   "key": "pl_x_markdown",
   "label": "Markdown artefacts (headings, bold, bullets) in prose",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "#{1,4}(?=\\s)",
    "\\*\\*",
    "[-*•](?=\\s+\\p{L})",
    "\\d{1,2}[.)](?=\\s+\\*\\*)"
   ]
  },
  {
   "key": "pl_x_markdown_inline",
   "label": "Inline markdown bold/italic markers",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\*\\*[^*\\n]{2,80}\\*\\*",
    "__[^_\\n]{2,60}__"
   ]
  },
  {
   "key": "pl_x_start_oto",
   "label": "Paragraph opens with \"Oto…\" (here is what you need)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "oto (?:co|wszystko|kilka|pięć|siedem|dziesięć|najważniejsze|nasz|nasza|krótki|kompletny|przewodnik|lista|dlaczego|jak)"
   ]
  },
  {
   "key": "pl_x_need_to_know",
   "label": "\"Co musisz wiedzieć / wszystko, co warto wiedzieć\"",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:wszystko|to wszystko),? co (?:musisz|powinieneś|powinnaś|powinni(?:ście)?|warto) wiedzieć",
    "co musisz wiedzieć",
    "kompletny przewodnik",
    "ostateczny przewodnik",
    "przewodnik krok po kroku",
    "wszystko,? co musisz wiedzieć"
   ]
  },
  {
   "key": "pl_x_start_question",
   "label": "Opening rhetorical question to the reader",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "czy (?:kiedykolwiek|zastanawiał\\p{L}*|marzył\\p{L}*|myślał\\p{L}*|słyszał\\p{L}*)",
    "zastanawiasz się",
    "marzysz o",
    "szukasz",
    "planujesz",
    "chcesz (?:poznać|odkryć|dowiedzieć)",
    "wyobraź sobie",
    "wyobraźmy sobie",
    "czy wiesz,? że",
    "czy to (?:możliwe|prawda)"
   ]
  },
  {
   "key": "pl_x_start_warto",
   "label": "Paragraph opens with \"Warto…\" / \"Należy…\" / \"Trzeba…\"",
   "severity": "low",
   "kind": "start",
   "alts": [
    "warto",
    "należy",
    "trzeba (?:podkreślić|zaznaczyć|przyznać|zauważyć)",
    "nie sposób (?:nie wspomnieć|pominąć)",
    "nie można (?:zapomnieć|pominąć)"
   ]
  },
  {
   "key": "pl_x_worth_mention",
   "label": "\"Warto mieć na uwadze / zwrócić uwagę / odnotować\"",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "warto (?:mieć na uwadze|zwrócić uwagę|odnotować|zaznaczyć|nadmienić|przypomnieć|dodać,? że|pamiętać,? że|wiedzieć,? że)",
    "należy (?:mieć na uwadze|pamiętać,? że|wspomnieć|zaznaczyć|odnotować|zwrócić uwagę|dodać)",
    "nie bez znaczenia (?:jest|pozostaje)",
    "na uwagę zasługuje",
    "na szczególną uwagę zasługuje",
    "na marginesie warto"
   ]
  },
  {
   "key": "pl_x_cta_verbs",
   "label": "Second-person calls to action (Odwiedź, Sprawdź, Nie przegap)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "nie przegap\\p{L}*",
    "nie zapomnij",
    "koniecznie (?:odwiedź|spróbuj|zobacz|sprawdź|wybierz|zarezerwuj)",
    "zarezerwuj (?:już|swój|swoje|swoją)",
    "skontaktuj się z nami",
    "skorzystaj z",
    "sprawdź (?:ofertę|nasze|nasz|naszą)",
    "już dziś",
    "zapraszamy (?:do|na|serdecznie)",
    "serdecznie zapraszamy",
    "zadbaj o",
    "pamiętaj,? (?:aby|by|o|że)"
   ]
  },
  {
   "key": "pl_x_second_person",
   "label": "Second-person \"Ty/Twój\" address in editorial text",
   "severity": "low",
   "kind": "word",
   "alts": [
    "twój",
    "twoja",
    "twoje",
    "twoją",
    "twojego",
    "twojej",
    "twoim",
    "twoich",
    "twoimi",
    "ci się spodoba",
    "przekonasz się",
    "zobaczysz",
    "poczujesz",
    "odkryjesz",
    "zakochasz się"
   ],
   "min": 3
  },
  {
   "key": "pl_x_promise",
   "label": "Promise-to-the-reader framing (dowiesz się, w tym artykule)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "w (?:tym|niniejszym) (?:artykule|tekście|przewodniku|materiale|zestawieniu) (?:dowiesz się|znajdziesz|omówimy|przyjrzymy|przedstawimy|poznasz)",
    "dowiesz się,? (?:jak|co|dlaczego|gdzie|czy)",
    "przyjrzymy się (?:bliżej|temu|kluczowym)",
    "zajmiemy się",
    "omówimy (?:kluczowe|najważniejsze|podstawowe)",
    "poniżej (?:przedstawiamy|znajdziesz|prezentujemy|omawiamy)",
    "w dalszej części (?:artykułu|tekstu)"
   ]
  },
  {
   "key": "pl_x_connectors_start",
   "label": "Sentence-initial empty connectors piled up (Jednakże, Natomiast, Tym samym…)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?<=^|[.!?:…]\\s+|\\n\\s*)(?:jednakże|niemniej jednak|niemniej|natomiast|zarazem|tym samym|w związku z tym|co za tym idzie|co istotne|co ważne|co równie ważne|równie istotne|nie bez znaczenia|mało tego|z drugiej strony|w tym kontekście|w tym przypadku|w efekcie|w rezultacie|ponadto|dodatkowo|co więcej|z kolei|przy tym|przy okazji|warto także|należy też|poza tym)"
   ],
   "min": 3
  },
  {
   "key": "pl_x_jednak_start",
   "label": "Sentence-initial \"Jednak\" in nearly every paragraph",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?<=^|[.!?:…]\\s+|\\n\\s*)jednak(?=[\\s,])"
   ],
   "min": 3
  },
  {
   "key": "pl_x_enumeration",
   "label": "\"Po pierwsze… po drugie…\" scaffolding",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "po (?:pierwsze|drugie|trzecie|czwarte|piąte)",
    "w pierwszej kolejności",
    "w drugiej kolejności",
    "kolejnym (?:krokiem|punktem|aspektem|czynnikiem)",
    "pierwszym (?:krokiem|punktem|aspektem|czynnikiem)",
    "kolejn(?:y|ym) (?:ważn|istotn|kluczow)\\p{L}* (?:aspekt|punkt|czynnik|element|krok)"
   ],
   "min": 2
  },
  {
   "key": "pl_x_key_points",
   "label": "Key-points labels (\"Najważniejsze punkty\", \"Kluczowe wnioski\")",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "najważniejsze (?:punkty|wnioski|fakty|informacje)",
    "kluczowe (?:punkty|wnioski|fakty|informacje|aspekty|czynniki|kwestie)",
    "główne (?:wnioski|punkty|zalety)",
    "tl;?dr",
    "w skrócie",
    "w pigułce",
    "krok (?:pierwszy|drugi|trzeci|\\d)",
    "pierwszy krok",
    "zalety i wady",
    "plusy i minusy"
   ]
  },
  {
   "key": "pl_x_key_vocab",
   "label": "\"Kluczowy aspekt / czynnik / element\" abstraction",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "kluczow\\p{L}* (?:aspekt|czynnik|element|rol|punkt|wniosek|znaczeni|kwesti|rozwiązani|wyzwani|krok|zaleta|zalet)\\p{L}*",
    "istotn\\p{L}* (?:aspekt|czynnik|element|kwesti)\\p{L}*",
    "fundamentaln\\p{L}* (?:znaczeni|rol|aspekt|element)\\p{L}*",
    "nieodłączn\\p{L}* (?:element|część|aspekt)\\p{L}*",
    "integraln\\p{L}* (?:część|element)\\p{L}*"
   ],
   "min": 2
  },
  {
   "key": "pl_x_both_and",
   "label": "\"Zarówno… jak i…\" balance formula",
   "severity": "low",
   "kind": "word",
   "alts": [
    "zarówno[^.?!]{3,90}\\bjak (?:i|też|również)\\b"
   ],
   "min": 2
  },
  {
   "key": "pl_x_not_only_variants",
   "label": "\"Nie tylko… lecz też / ale i\" and \"to nie X, to Y\"",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "nie tylko\\b[^.?!]{3,90}\\b(?:ale i|lecz i|lecz też|lecz również|ale też|a także|a również)\\b",
    "to nie (?:tylko|jedynie|po prostu|zwykł\\p{L}*)\\b[^.?!]{3,70}[,;—–-]\\s*(?:to|lecz|ale)\\b",
    "nie (?:jest|był\\p{L}*) (?:to )?(?:po prostu|zwykł\\p{L}*|jedynie|tylko)\\b[^.?!]{3,70}[,;]\\s*(?:to|lecz|ale|jest)\\b"
   ]
  },
  {
   "key": "pl_x_from_through_to",
   "label": "\"Od… przez… po…\" tricolon range",
   "severity": "low",
   "kind": "word",
   "alts": [
    "od [^.?!,]{3,40},\\s+(?:przez|po)\\s+[^.?!]{3,40},?\\s+(?:aż )?(?:po|do)\\b",
    "od [^.?!,]{3,40} przez [^.?!,]{3,40} (?:aż )?(?:po|do)\\b"
   ],
   "min": 2
  },
  {
   "key": "pl_x_one_side_other",
   "label": "\"Z jednej strony… z drugiej strony…\" hedged balance",
   "severity": "low",
   "kind": "word",
   "alts": [
    "z jednej strony[^.?!]{3,200}z drugiej strony"
   ]
  },
  {
   "key": "pl_x_participle_tail",
   "label": "Imiesłów closer tacked on after a comma (…, podkreślając / zapewniając)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\p{L}+,\\s+(?:podkreślając|zapewniając|odzwierciedlając|świadcząc|ukazując|nadając|tworząc|oferując|pozwalając|umożliwiając|stanowiąc|wzmacniając|czyniąc|kreując|budując|wskazując|sygnalizując|potwierdzając|dając|przyczyniając się|co (?:podkreśla|świadczy|pokazuje|odzwierciedla|dowodzi|potwierdza|sygnalizuje|wzmacnia))"
   ],
   "min": 2
  },
  {
   "key": "pl_x_which_shows",
   "label": "\"co świadczy o / co pokazuje\" significance tail",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "co (?:świadczy|dowodzi|pokazuje|wskazuje|potwierdza|odzwierciedla|podkreśla|ilustruje|sygnalizuje) (?:o|, że|jak|rosnąc\\p{L}*|siłę|wagę|znaczeni\\p{L}*)",
    "świadczy o (?:rosnącym|wysokim|dużym|ogromnym|wyjątkowym|znaczeniu)",
    "jest dowodem na to,? że",
    "to dowód (?:na to,? )?że"
   ]
  },
  {
   "key": "pl_x_moral",
   "label": "Moral / forward-looking closer (\"Jedno jest pewne\", \"Czas pokaże\")",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "jedno jest (?:pewne|jasne|pewno)",
    "czas pokaże",
    "pozostaje (?:czekać|mieć nadzieję|do zobaczenia)",
    "przyszłość (?:rysuje się|zapowiada się|wygląda) (?:w jasnych|obiecująco|optymistycznie|ciekawie)",
    "w jasnych barwach",
    "otwiera (?:nowy rozdział|nowe możliwości|drzwi do|nowe horyzonty|przed [^.?!]{1,30} nowe)",
    "nowy rozdział",
    "kolejny rozdział",
    "droga przed",
    "przed nami (?:wiele|długa|jeszcze)",
    "patrząc w przyszłość",
    "spoglądając w przyszłość",
    "wyzwania i (?:szanse|możliwości)",
    "szanse i (?:wyzwania|zagrożenia)"
   ]
  },
  {
   "key": "pl_x_closers_extra",
   "label": "Summary starters beyond Podsumowując (Na zakończenie, Tak więc, Zatem…)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "na zakończenie",
    "na samym końcu",
    "konkludując",
    "reasumując",
    "tak więc",
    "zatem",
    "w świetle (?:powyższego|powyższych)",
    "mając to wszystko na uwadze",
    "biorąc to wszystko pod uwagę",
    "wszystko to sprawia,? że",
    "wniosek (?:jest|nasuwa się)",
    "wnioski są",
    "jak widać",
    "jak (?:pokazuje|widzimy|wynika)",
    "podsumowując",
    "w podsumowaniu",
    "ostatecznie"
   ]
  },
  {
   "key": "pl_x_end_of_day",
   "label": "English calque \"pod koniec dnia / na koniec dnia\"",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:pod|na) koniec dnia",
    "na końcu dnia",
    "w ostatecznym rozrachunku",
    "biorąc wszystko pod uwagę",
    "w dłuższej perspektywie czasowej"
   ]
  },
  {
   "key": "pl_x_copula",
   "label": "Copula inflation (charakteryzuje się, posiada, stanowi, pełni rolę)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "charakteryzuj\\p{L}* się",
    "posiada\\p{L}*",
    "stanowi\\p{L}*",
    "pełni\\p{L}* (?:funkcję|rolę|funkcje)",
    "szczyci się",
    "może poszczycić się",
    "cieszy się (?:dużą|ogromną|rosnącą|niesłabnącą|ogromnym|dużym) (?:popularnością|zainteresowaniem|uznaniem)",
    "zyskuje na popularności",
    "wyróżnia się (?:na tle|spośród|wśród)",
    "jest (?:postrzegan|uznawan|określan)\\p{L}* (?:za|jako|mianem)"
   ],
   "min": 2
  },
  {
   "key": "pl_x_offers_gives",
   "label": "\"Oferuje gościom / zapewnia / umożliwia\" brochure verbs",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "oferuj\\p{L}* (?:gościom|odwiedzającym|mieszkańcom|inwestorom|klientom|szeroki|szeroką|bogat\\p{L}*|wyjątkow\\p{L}*|niezapomnian\\p{L}*|wiele)",
    "zapewnia\\p{L}* (?:gościom|odwiedzającym|mieszkańcom|niezapomnian\\p{L}*|wyjątkow\\p{L}*|wspaniał\\p{L}*|płynn\\p{L}*|komfort|dostęp)",
    "umożliwia\\p{L}* (?:odkrycie|poznanie|doświadczenie|zanurzenie|poczucie)",
    "pozwala\\p{L}* (?:odkryć|poczuć|doświadczyć|zanurzyć się|cieszyć się|w pełni)",
    "daje\\p{L}* (?:możliwość|szansę|okazję) (?:odkrycia|poznania|doświadczenia|zanurzenia)",
    "gwarantuj\\p{L}* (?:niezapomnian\\p{L}*|wyjątkow\\p{L}*|wysok\\p{L}*|stabiln\\p{L}*|komfort|spokój|relaks)"
   ],
   "min": 2
  },
  {
   "key": "pl_x_nominal",
   "label": "Nominal bureaucratic style (w celu, w oparciu o, w zakresie, poprzez)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "w celu\\b",
    "w oparciu o",
    "w zakresie\\b",
    "w obrębie",
    "w kontekście",
    "na przestrzeni (?:lat|wieków|ostatnich|dziesięcioleci)",
    "w odniesieniu do",
    "z uwagi na fakt",
    "biorąc pod uwagę (?:fakt|to)",
    "mając na uwadze",
    "pod względem",
    "na rzecz",
    "w chwili obecnej",
    "w dniu dzisiejszym",
    "w związku z (?:czym|powyższym|tym)",
    "w ramach",
    "poprzez\\b",
    "ma na celu",
    "ma miejsce",
    "jest w stanie",
    "fakt,? że"
   ],
   "min": 3
  },
  {
   "key": "pl_x_light_verb",
   "label": "Light-verb nominalisation (dokonać analizy, przeprowadzić weryfikację)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "dokon\\p{L}* (?:\\p{L}+ )?(?:oceny|analizy|zmian\\p{L}*|weryfikacji|aktualizacji|płatności|rejestracji|transakcji|wpłaty|przeglądu|przelewu|zamknięcia|sprzedaży|zakupu|wyboru|rezerwacji)",
    "przeprowadz\\p{L}* (?:\\p{L}+ )?(?:analiz\\p{L}*|weryfikacj\\p{L}*|proces\\p{L}*|ocen\\p{L}*|konsultacj\\p{L}*)",
    "podejm\\p{L}* (?:\\p{L}+ )?(?:kroki|działania|starania)",
    "udziel\\p{L}* (?:\\p{L}+ )?(?:informacji|odpowiedzi|wsparcia|porady)",
    "wyraz\\p{L}* (?:\\p{L}+ )?(?:zgodę|opinię|zainteresowanie)"
   ]
  },
  {
   "key": "pl_x_trend",
   "label": "Stock trend padding (w ostatnich latach, coraz więcej, rosnąca popularność)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "w ostatnich latach",
    "w ostatnim czasie",
    "w ostatnich miesiącach",
    "coraz (?:więcej|większ\\p{L}*|popularn\\p{L}*|częściej|bardziej)",
    "rosnąc\\p{L}* (?:popularnoś\\p{L}*|zainteresowani\\p{L}*|liczb\\p{L}*|trend\\p{L}*|znaczeni\\p{L}*)",
    "stale rosnąc\\p{L}*",
    "dynamicznie rozwijając\\p{L}*",
    "dynamiczn\\p{L}* (?:rozwój|wzrost|rozwoj\\p{L}*|rynek|rynku)",
    "prężnie"
   ],
   "min": 2
  },
  {
   "key": "pl_x_there_are_many",
   "label": "\"Istnieje wiele / jest kilka powodów\" empty existentials",
   "severity": "low",
   "kind": "word",
   "alts": [
    "istnieje (?:wiele|kilka|szereg|szerok\\p{L}*|mnóstwo)",
    "jest (?:wiele|kilka|szereg|mnóstwo) (?:powodów|czynników|opcji|sposobów|rzeczy|aspektów)",
    "kilka (?:powodów|czynników|kluczowych|ważnych)",
    "szereg (?:czynników|powodów|korzyści|zalet|działań)",
    "wiele (?:czynników|aspektów|korzyści)",
    "różnorodn\\p{L}* (?:oferta|ofert\\p{L}*|opcj\\p{L}*|możliwoś\\p{L}*|atrakcj\\p{L}*)"
   ],
   "min": 2
  },
  {
   "key": "pl_x_passive_support",
   "label": "Passive \"z myślą o / został zaprojektowany tak, aby\"",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?:zaprojektowan|stworzon|pomyślan|przygotowan)\\p{L}* z myślą o",
    "z myślą o (?:tych|osobach|gościach|klientach|inwestorach|rodzinach|najbardziej)",
    "został\\p{L}* zaprojektowan\\p{L}* (?:tak|w taki sposób),? (?:aby|by|żeby)",
    "dedykowan\\p{L}* (?:zespół|zespołu|zespołem|oferta|oferty|usługi|przestrzeń|rozwiązani\\p{L}*)",
    "kompleksow\\p{L}* (?:oferta|obsług\\p{L}*|rozwiązani\\p{L}*|podejści\\p{L}*|usług\\p{L}*)",
    "holistyczn\\p{L}*",
    "wieloaspektow\\p{L}*",
    "synerg\\p{L}*",
    "ekosystem\\p{L}*"
   ],
   "min": 2
  },
  {
   "key": "pl_x_anglicisms",
   "label": "Business anglicisms / calques (adresować, implementacja, bazować, aplikować)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "adresowa\\p{L}* (?:problem|potrzeb|wyzwani|kwesti)\\p{L}*",
    "implementacj\\p{L}*",
    "implementowa\\p{L}*",
    "bazuj\\p{L}* na",
    "bazowa\\p{L}* na",
    "aplikowa\\p{L}* (?:o|do)",
    "realizowa\\p{L}* (?:cele|założenia|strategi\\p{L}*)",
    "nawigowa\\p{L}*",
    "nawigacj\\p{L}* (?:po|przez)",
    "poruszanie się po",
    "krajobraz (?:prawny|biznesowy|inwestycyjny|gospodarczy|regulacyjny|podatkowy|nieruchomości)",
    "złożon\\p{L}* (?:krajobraz|dynamik\\p{L}*|ekosystem\\p{L}*)",
    "dynamik\\p{L}* rynku",
    "wyznacza\\p{L}* (?:nowe )?(?:standardy|trendy)",
    "podnosi\\p{L}* poprzeczkę",
    "game[- ]?changer",
    "win[- ]win",
    "must[- ](?:see|have|visit|try)"
   ],
   "min": 2
  },
  {
   "key": "pl_x_calque_experience",
   "label": "Calque \"doświadczenie, którego nie zapomnisz\" / \"doświadczyć\"",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "doświadczeni\\p{L}*,? (?:którego|które|które) (?:nie zapomni\\p{L}*|na długo|zapadnie)",
    "na długo zapadn\\p{L}* w pamięć",
    "zapadn\\p{L}* w pamięć",
    "doświadcz\\p{L}* (?:prawdziwego|autentycznego|magii|piękna|luksusu|gościnności|wyjątkowego)",
    "zabierze\\p{L}* (?:cię|cię|Cię|nas|was|Państwa) w (?:podróż|świat|niezapomnian\\p{L}*)",
    "zabierz\\p{L}* (?:się|siebie|nas|go) w podróż",
    "robi\\p{L}* (?:wielką )?różnicę",
    "wynosi\\p{L}* (?:na|to na) (?:wyższy|nowy) poziom",
    "na (?:wyższy|nowy) poziom",
    "zabierz swoją"
   ]
  },
  {
   "key": "pl_x_mix_calque",
   "label": "Calque \"mieszanka / miks / połączenie tradycji i nowoczesności\"",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:mieszank\\p{L}*|miks\\p{L}*|połączeni\\p{L}*|fuzj\\p{L}*|splot\\p{L}*|harmoni\\p{L}*) (?:tradycji|nowoczesności|kultur|stylów|historii|smaków|epok|wpływów|starego|przeszłości|luksusu|elegancji|natury)",
    "łączy w sobie",
    "łączy[^.?!]{2,40} z nowoczesn\\p{L}*",
    "tradycj\\p{L}* spotyka (?:się )?z nowoczesnoś\\p{L}*",
    "stare spotyka (?:się )?z nowym",
    "wschód spotyka zachód",
    "to, co czyni",
    "co czyni (?:to miejsce|go|ją|je|tę)",
    "sprawia,? że (?:to miejsce|każd\\p{L}*|wyspa|ten)"
   ]
  },
  {
   "key": "pl_x_perfect_place",
   "label": "Brochure \"idealne miejsce / doskonały wybór / coś dla każdego\"",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "idealn\\p{L}* (?:miejsce|miejsca|miejscem|wybór|wyboru|wyborem|cel|kierunek|kierunku|punkt wyjścia|połączeni\\p{L}*|propozycj\\p{L}*|dla)",
    "doskonał\\p{L}* (?:wybór|wyboru|miejsce|propozycj\\p{L}*|okazj\\p{L}*|inwestycj\\p{L}*|baz\\p{L}*)",
    "coś dla każdego",
    "dla każdego coś",
    "każdy znajdzie (?:tu|tutaj|coś)",
    "bez względu na (?:wiek|budżet|gust|upodobania)",
    "zadowoli (?:każdego|nawet najbardziej)",
    "spełni (?:oczekiwania|marzenia) (?:nawet )?najbardziej",
    "na każdą kieszeń",
    "dla (?:całej )?rodziny i dla",
    "dla (?:młodych|dużych) i (?:starszych|małych)"
   ]
  },
  {
   "key": "pl_x_walk_in_the_park",
   "label": "Reader-coddling hooks (\"na wyciągnięcie ręki\", \"w zasięgu ręki\")",
   "severity": "low",
   "kind": "word",
   "alts": [
    "na wyciągnięcie ręki",
    "w zasięgu ręki",
    "zaledwie (?:kilka|parę) minut (?:od|drogi|spacerem|jazdy)",
    "rzut beretem",
    "rzut kamieniem",
    "tuż za (?:rogiem|progiem)",
    "w samym centrum wydarzeń",
    "w samym sercu",
    "serce (?:wyspy|miasta|Cypru|Limassol|Nikozji|Pafos|Larnaki)",
    "w sercu (?:wyspy|miasta|Cypru|Limassol|Nikozji|Pafos|Larnaki)"
   ]
  },
  {
   "key": "pl_x_hype_awe",
   "label": "Awe adjectives (oszałamiający, zapierający dech, bajeczny)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "oszałamiając\\p{L}*",
    "zapierając\\p{L}* dech",
    "zapiera dech",
    "imponując\\p{L}*",
    "olśniewając\\p{L}*",
    "zachwycając\\p{L}*",
    "wspaniał\\p{L}*",
    "niesamowit\\p{L}*",
    "nieziemsk\\p{L}*",
    "bajeczn\\p{L}*",
    "bajkow\\p{L}*",
    "rajsk\\p{L}*",
    "cudown\\p{L}*",
    "pierwszorzędn\\p{L}*",
    "perfekcyjn\\p{L}*",
    "bezbłędn\\p{L}*",
    "nieskazitelnie",
    "wymarzon\\p{L}*",
    "zjawiskow\\p{L}*",
    "bezkonkurencyjn\\p{L}*",
    "unikaln\\p{L}*",
    "autentyczn\\p{L}*"
   ],
   "min": 2
  },
  {
   "key": "pl_x_hype_premium",
   "label": "Estate-agent premium words (ekskluzywny, prestiżowy, luksusowy)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "ekskluzywn\\p{L}*",
    "prestiżow\\p{L}*",
    "luksusow\\p{L}*",
    "wysmakowan\\p{L}*",
    "wyrafinowan\\p{L}*",
    "ponadczasow\\p{L}*",
    "światowej klasy",
    "najwyższej (?:klasy|jakości|próby)",
    "topow\\p{L}*",
    "flagow\\p{L}*",
    "przełomow\\p{L}*",
    "innowacyjn\\p{L}*",
    "rewolucyjn\\p{L}*",
    "pionierski\\p{L}*",
    "wizjonersk\\p{L}*",
    "komfortow\\p{L}*",
    "przestronn\\p{L}*"
   ],
   "min": 3
  },
  {
   "key": "pl_x_estate_agent",
   "label": "Estate-agent clichés (dom marzeń, okazja inwestycyjna, idealna lokalizacja)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "dom(?:u|em|owi)? marzeń",
    "inwestycj\\p{L}* marzeń",
    "okazj\\p{L}* inwestycyjn\\p{L}*",
    "niepowtarzaln\\p{L}* okazj\\p{L}*",
    "wyjątkow\\p{L}* okazj\\p{L}*",
    "gratk\\p{L}* (?:dla|inwestycyjn)",
    "(?:idealn|doskonał|prestiżow|strategiczn|świetn|znakomit)\\p{L}* (?:lokalizacj|położeni)\\p{L}*",
    "lokalizacj\\p{L}* (?:gwarantuj|zapewnia)\\p{L}*",
    "lukratywn\\p{L}*",
    "pasywn\\p{L}* dochod\\p{L}*",
    "dla (?:najbardziej )?wymagając\\p{L}* (?:klient|inwestor|gości|podróżnik|miłośnik)\\p{L}*",
    "dbałoś\\p{L}* o (?:każdy )?(?:szczegół|detal)\\p{L}*",
    "z (?:widokiem|panoramą) na (?:morze|Morze Śródziemne)"
   ]
  },
  {
   "key": "pl_x_press_release",
   "label": "Press-release phrases (z dumą ogłasza, wyznacza nowe standardy)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "z (?:dumą|radością|przyjemnością|satysfakcją) (?:ogłasza|informuje|zapowiada|prezentuje|zaprasza|zapraszamy|ogłaszamy|informujemy)",
    "jest dumn\\p{L}*",
    "kamień milowy",
    "kamieniem milowym",
    "historyczn\\p{L}* (?:moment|chwila|krok|wydarzeni\\p{L}*)",
    "przełomow\\p{L}* (?:moment|chwila|krok)",
    "nowy etap",
    "wprowadza na rynek",
    "nowe standardy",
    "zaangażowan\\p{L}* w (?:rozwój|budowanie|tworzenie|wspieranie)",
    "misj\\p{L}* (?:firmy|spółki|marki)",
    "wizj\\p{L}* (?:firmy|spółki|marki)",
    "z pasją",
    "pasj\\p{L}* do (?:detalu|szczegółów|jakości)",
    "zobowiązan\\p{L}* do"
   ]
  },
  {
   "key": "pl_x_vague_experts",
   "label": "Vague attribution (eksperci twierdzą, według analityków)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:eksperci|analitycy|specjaliści|znawcy|obserwatorzy|komentatorzy|inwestorzy|branżowi eksperci|lokalni eksperci|badacze|naukowcy|prawnicy)\\s+(?:twierdzą|wskazują|zgodnie|uważają|przewidują|podkreślają|zauważają|są zgodni|sugerują|ostrzegają|przekonują|szacują|oceniają)",
    "według (?:ekspertów|specjalistów|analityków|obserwatorów|niektórych|wielu|branżowych|lokalnych|badań|raportów|szacunków)",
    "wielu (?:ekspertów|specjalistów|inwestorów|analityków|mieszkańców|turystów|podróżnych)",
    "badania (?:pokazują|wskazują|dowodzą|sugerują|potwierdzają)",
    "jak wynika z (?:badań|analiz|raportów|danych|szacunków)",
    "powszechnie (?:uważa|wiadomo|przyjmuje się|sądzi)",
    "(?:mówi|uważa|przyjmuje|twierdzi) się,? (?:że)?",
    "niektórzy (?:twierdzą|uważają|sądzą|wskazują)",
    "często (?:mówi|słyszy|słychać) się",
    "dane (?:pokazują|wskazują|dowodzą|sugerują)"
   ]
  },
  {
   "key": "pl_x_cyprus_cliche",
   "label": "Cyprus clichés (wyspa Afrodyty, turkusowa woda, strategiczne położenie)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "wysp\\p{L}* (?:Afrodyty|miłości|bogini|słońca|świętych|kontrastów)",
    "kolebk\\p{L}* (?:Afrodyty|cywilizacji|kultury|bogini)",
    "turkusow\\p{L}* (?:wod\\p{L}*|wód|morz\\p{L}*|lazur\\p{L}*|zatok\\p{L}*)",
    "lazurow\\p{L}*",
    "szmaragdow\\p{L}*",
    "kryształowo (?:czyst\\p{L}*|przejrzyst\\p{L}*)",
    "złot\\p{L}* (?:plaż\\p{L}*|piask\\p{L}*)",
    "złocist\\p{L}* (?:plaż\\p{L}*|piask\\p{L}*)",
    "piaszczyst\\p{L}* plaż\\p{L}* (?:otoczon|pełn)",
    "strategiczn\\p{L}* (?:położeni\\p{L}*|lokalizacj\\p{L}*|poło\\p{L}*)",
    "skrzyżowani\\p{L}* (?:Europy|trzech kontynentów|kultur|szlaków|cywilizacji)",
    "brama do (?:Europy|Azji|Bliskiego Wschodu|Afryki)",
    "pomost (?:między|pomiędzy)",
    "most (?:między|pomiędzy) (?:Wschodem|Europą|Zachodem)",
    "słoneczn\\p{L}* wysp\\p{L}*",
    "(?:ponad|przeszło) 300 (?:słonecznych )?dni",
    "śródziemnomorsk\\p{L}* (?:klimat|styl życia|rytm|urok|kuchni\\p{L}*|słońc\\p{L}*)",
    "gościnność Cypryjczyków",
    "cypryjsk\\p{L}* gościnność",
    "przystań dla",
    "rajsk\\p{L}* (?:plaż|wysp|zakątk)\\p{L}*",
    "zakątk\\p{L}* (?:raju|świata|Morza Śródziemnego)"
   ]
  },
  {
   "key": "pl_x_lifestyle",
   "label": "Empty lifestyle words (styl życia, jakość życia, komfort życia) in bulk",
   "severity": "low",
   "kind": "word",
   "alts": [
    "styl\\p{L}* życia",
    "jakoś\\p{L}* życia",
    "komfort\\p{L}* życia",
    "na luzie",
    "relaks\\p{L}*",
    "odpoczynek od codzienności",
    "ucieczk\\p{L}* od (?:codzienności|zgiełku|rutyny)",
    "z dala od zgiełku",
    "od zgiełku miasta",
    "spokój i (?:cisza|relaks|wytchnienie)",
    "wytchnieni\\p{L}*",
    "oddech od"
   ],
   "min": 3
  },
  {
   "key": "pl_x_senses",
   "label": "Sensory purple prose (pobudza zmysły, rozpieszcza podniebienie, eksplozja smaków)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:pobudza|rozpieszcza|kusi|ucieszy|połechta|rozkosz\\p{L}*) (?:zmysły|podniebienie|oko|nos|kubki smakowe)",
    "eksplozj\\p{L}* (?:smaków|kolorów|barw|aromatów|emocji)",
    "taniec (?:smaków|aromatów|kolorów)",
    "tańczą? (?:na|w) (?:języku|podniebieniu)",
    "rozpływa się w ustach",
    "rozkosz\\p{L}* dla (?:podniebienia|zmysłów)",
    "kulinarn\\p{L}* (?:podróż|przygod|odyseja|odyseję|wędrówk|dziedzictw|arcydzieł|wyzwani)\\p{L}*",
    "kompozycj\\p{L}* (?:smaków|aromatów|barw)",
    "bukiet (?:smaków|aromatów)",
    "dla (?:smakoszy|koneserów|miłośników dobrej kuchni)",
    "wyśmienit\\p{L}*",
    "przepyszn\\p{L}*",
    "delektowa\\p{L}* się",
    "delektuj\\p{L}* się",
    "gra (?:smaków|kolorów|świateł)"
   ]
  },
  {
   "key": "pl_x_fashion_fluff",
   "label": "Fashion/lifestyle fluff (dodaje szyku, nuta elegancji, must-have)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "doda\\p{L}* (?:\\p{L}+ )?(?:szyku|elegancji|uroku|charakteru|klasy|lekkości|blasku)",
    "nut\\p{L}* (?:elegancji|luksusu|szyku|egzotyki|romantyzmu|nostalgii|tajemniczości)",
    "odrobin\\p{L}* (?:luksusu|elegancji|magii|szaleństwa|szyku|romantyzmu)",
    "podkreśl\\p{L}* (?:sylwetk|kobiecość|indywidualność|charakter|osobowość)\\p{L}*",
    "garderob\\p{L}* (?:każdej|każdego|każdej kobiety)",
    "stylizacj\\p{L}* (?:na każdą|na każdą okazję)",
    "na każdą okazję",
    "niezbędn\\p{L}* (?:w każdej|w garderobie|element garderoby)",
    "must[- ]have"
   ]
  },
  {
   "key": "pl_x_event_fluff",
   "label": "Event-announcement fluff (nie zabraknie, bogaty program, będą mieli okazję)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "nie (?:zabraknie|może zabraknąć)",
    "atrakcji nie zabraknie",
    "bogat\\p{L}* program\\p{L}*",
    "pełn\\p{L}* (?:atrakcji|wrażeń|niespodzianek|emocji|energii|życia|uroku|kontrastów)",
    "przepełnion\\p{L}* (?:emocjami|atmosferą|energią)",
    "obfituj\\p{L}* w",
    "zapowiada się (?:wyjątkow\\p{L}*|niezapomnian\\p{L}*|fascynując\\p{L}*|wspaniał\\p{L}*|pasjonując\\p{L}*|ekscytując\\p{L}*)",
    "uczestnicy będą mieli okazję",
    "(?:będą|będziecie|będzie) (?:mieli|miał|miała|mieć) okazję",
    "okazj\\p{L}* do (?:networkingu|wymiany|nawiązania|poznania|spotkania)",
    "networking",
    "wymian\\p{L}* doświadczeń",
    "w gronie (?:ekspertów|znakomitych|wybitnych|gwiazd)",
    "gwiazd\\p{L}* wieczoru",
    "wydarzeni\\p{L}* roku"
   ]
  },
  {
   "key": "pl_x_cta_worth",
   "label": "\"Warto odwiedzić / spróbować / zobaczyć\" recommendation tic",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "warto (?:się )?(?:odwiedzić|spróbować|zobaczyć|zajrzeć|wybrać|sprawdzić|zarezerwować|skorzystać|rozważyć|zwiedzić|wypróbować|poświęcić|przyjrzeć|zaplanować|rozejrzeć)",
    "wart\\p{L}* (?:uwagi|polecenia|odwiedzenia|zobaczenia|grzechu|poznania)",
    "gorąco polecam\\p{L}*",
    "z czystym sumieniem polec\\p{L}*",
    "bez wahania polec\\p{L}*",
    "polecam\\p{L}* każdemu"
   ],
   "min": 2
  },
  {
   "key": "pl_x_interview_filler",
   "label": "Interview filler (podzielił się przemyśleniami, z uśmiechem na twarzy)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:podzielił|podzieliła|dzieli|podzielili)\\p{L}* się (?:z nami )?(?:swoimi |swoją |swoje )?(?:przemyśleni\\p{L}*|spostrzeżeni\\p{L}*|doświadczeni\\p{L}*|refleksj\\p{L}*|wiedz\\p{L}*|historią|opiniami|uwagami|wizją)",
    "w rozmowie z nami",
    "w szczerej rozmowie",
    "szczerze (?:przyznaje|opowiada|mówi)",
    "otwarcie (?:mówi|opowiada|przyznaje)",
    "z (?:entuzjazmem|zaangażowaniem|pasją|błyskiem w oku|uśmiechem na twarzy) (?:opowiada|mówi|wspomina|dzieli)",
    "ze szczerym uśmiechem",
    "z błyskiem w oku",
    "inspirując\\p{L}* (?:historia|droga|podróż|przykład|osobowość)",
    "historia sukcesu",
    "wizjoner\\p{L}*",
    "jego (?:droga|podróż) (?:do|na szczyt)",
    "jej (?:droga|podróż) (?:do|na szczyt)"
   ]
  },
  {
   "key": "pl_x_attrib_monotone",
   "label": "Monotone attribution verbs (podkreślił / zaznaczył / dodał repeated)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "podkreśl(?:a|ił|iła|ają|ili|ały)",
    "zaznacz(?:a|ył|yła|ają|yli)",
    "zauważ(?:a|ył|yła|ają|yli)",
    "doda(?:je|ł|ła|ją|li)",
    "wskaz(?:uje|ał|ała|ują|ali)",
    "stwierdz(?:a|ił|iła|ają|ili)"
   ],
   "min": 5
  },
  {
   "key": "pl_x_legal_disclaimer",
   "label": "Generic legal disclaimer filler (zaleca się konsultację, każdy przypadek jest inny)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "zaleca się (?:konsultację|skonsultowanie|kontakt|zasięgnięcie)",
    "zawsze (?:warto|należy|zaleca się) (?:skonsultować|zasięgnąć|sprawdzić)",
    "każd\\p{L}* (?:przypadek|sytuacja|sprawa) (?:jest|bywa) (?:inn|indywidualn)\\p{L}*",
    "zasięgn\\p{L}* (?:porady|opinii) (?:prawnika|specjalisty|eksperta|doradcy)",
    "nie stanowi (?:porady|doradztwa|wiążącej)",
    "ma charakter (?:wyłącznie )?(?:informacyjny|ogólny|orientacyjny)",
    "niniejsz\\p{L}* (?:artykuł|tekst|materiał|publikacj\\p{L}*)",
    "w zależności od (?:indywidualnej|konkretnej) sytuacji"
   ]
  },
  {
   "key": "pl_x_quotes_english",
   "label": "English curly or straight quotes instead of Polish „…”",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "“[^”\\n]{2,160}”",
    "\"[^\"\\n]{2,160}\"",
    "‘[^’\\n]{2,80}’"
   ]
  },
  {
   "key": "pl_x_quotes_guillemets",
   "label": "French «…» guillemets (Polish uses „…” and ‚…’ inside, »…« only for nested)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "«[^»\\n]{2,160}»"
   ]
  },
  {
   "key": "pl_x_emdash_nospace",
   "label": "English-style unspaced em dash (słowo—słowo)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\p{L}+—\\p{L}+",
    "\\p{L}+ —\\p{L}+",
    "\\p{L}+— \\p{L}+",
    "\\p{L}+--\\p{L}+",
    "\\p{L}+ -- \\p{L}+"
   ]
  },
  {
   "key": "pl_x_dash_density",
   "label": "Dash overuse (pauza ― as a rhythm crutch)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?<=\\s)[—–](?=\\s)"
   ],
   "min": 6
  },
  {
   "key": "pl_x_hyphen_dash",
   "label": "Hyphen used as a dash in running text ( - )",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?<=\\s)-(?=\\s\\p{L})"
   ],
   "min": 2
  },
  {
   "key": "pl_x_thousands",
   "label": "English/German thousands separators (1,200 / 1.200.000) instead of 1 200",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\d{1,3}(?:,\\d{3})+(?![\\d])",
    "\\d{1,3}(?:\\.\\d{3}){2,}(?![\\d])",
    "\\d{1,3}\\.\\d{3}(?=\\s?(?:euro|EUR|€|zł|USD|dolarów|metrów))"
   ]
  },
  {
   "key": "pl_x_decimal_point",
   "label": "Decimal point instead of decimal comma (2.5 mln, 3.5%)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\d+\\.\\d{1,2}\\s?(?:%|proc|mln|mld|tys|euro|EUR|€|m2|m²|km|ha|stopni|°)"
   ]
  },
  {
   "key": "pl_x_currency_symbol",
   "label": "Currency symbol before the figure (€250,000, $) instead of \"250 000 euro\"",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "[€$£]\\s?\\d+",
    "(?:EUR|USD|GBP)\\s?\\d+",
    "\\d(?:\\s?)(?:EUR|USD|GBP)(?![\\p{L}])"
   ]
  },
  {
   "key": "pl_x_date_format",
   "label": "Non-Polish date style (October 5, 5/10/2026, 5th)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\d{1,2}/\\d{1,2}/\\d{2,4}",
    "\\d{1,2}(?:st|nd|rd|th)\\b",
    "(?:październik|wrzesień|listopad|grudzień|styczeń|luty|marzec|kwiecień|maj|czerwiec|lipiec|sierpień)\\s+\\d{1,2},\\s+\\d{4}",
    "\\d{1,2}-go\\s+(?:stycznia|lutego|marca|kwietnia|maja|czerwca|lipca|sierpnia|września|października|listopada|grudnia)",
    "w dniu \\d{1,2}\\s+(?:stycznia|lutego|marca|kwietnia|maja|czerwca|lipca|sierpnia|września|października|listopada|grudnia)"
   ]
  },
  {
   "key": "pl_x_clock_ampm",
   "label": "12-hour clock (5 pm) in Polish text",
   "severity": "low",
   "kind": "word",
   "alts": [
    "\\d{1,2}(?::\\d{2})?\\s?(?:a\\.m\\.|p\\.m\\.|am|pm)"
   ]
  },
  {
   "key": "pl_x_emoji",
   "label": "Emoji / pictograms in editorial text",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "[\\u{1F300}-\\u{1FAFF}\\u{2600}-\\u{27BF}\\u{2B50}\\u{2705}\\u{274C}\\u{2B06}\\u{FE0F}]"
   ]
  },
  {
   "key": "pl_x_ellipsis_arrow",
   "label": "Arrows and symbols used as connectors (→, ⇒, •)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "[→⇒➜➡•▪✔✓]"
   ]
  },
  {
   "key": "pl_x_exclaim_cta",
   "label": "Exclamation-led hype sentences",
   "severity": "low",
   "kind": "word",
   "alts": [
    "[\\p{L}]{3,}!(?=\\s+\\p{L})"
   ],
   "min": 2
  }
 ],
 "banned": [
  "odgrywa kluczową rolę",
  "odgrywa istotną rolę",
  "ma kluczowe znaczenie",
  "podkreśla znaczenie",
  "podkreśla wagę",
  "stanowi świadectwo",
  "jest świadectwem",
  "rzuca światło na",
  "szeroka gama",
  "szeroki wachlarz",
  "bogaty gobelin",
  "harmonijnie łączy",
  "złożony krajobraz",
  "unikalny",
  "autentyczny",
  "wyjątkowy",
  "niepowtarzalny",
  "niezapomniany",
  "oszałamiający",
  "zapierający dech w piersiach",
  "malowniczy",
  "urzekający",
  "tętniący życiem",
  "ekskluzywny",
  "prestiżowy",
  "luksusowy",
  "bezkonkurencyjny",
  "warto zauważyć",
  "warto podkreślić",
  "należy zaznaczyć",
  "należy pamiętać, że",
  "oto co musisz wiedzieć",
  "wszystko, co musisz wiedzieć",
  "w dzisiejszym szybko zmieniającym się świecie",
  "coraz więcej",
  "jednakże",
  "niemniej jednak",
  "natomiast",
  "ponadto",
  "co więcej",
  "po pierwsze… po drugie",
  "z jednej strony… z drugiej strony",
  "zarówno… jak i",
  "nie tylko… ale także",
  "podsumowując",
  "reasumując",
  "krótko mówiąc",
  "w skrócie",
  "w ostatecznym rozrachunku",
  "jedno jest pewne",
  "otwiera nowe możliwości",
  "pod koniec dnia",
  "w celu",
  "w ramach",
  "w oparciu o",
  "w zakresie",
  "dokonać zakupu",
  "dokonać wyboru",
  "przeprowadzić analizę",
  "posiada",
  "charakteryzuje się",
  "stanowi",
  "jest oferowany",
  "zagłębić się w",
  "zanurzyć się w",
  "doświadcz",
  "wyspa Afrodyty",
  "turkusowa woda",
  "kryształowo czyste wody",
  "złote plaże",
  "strategiczne położenie",
  "strategiczna lokalizacja",
  "skrzyżowanie trzech kontynentów",
  "brama do Europy",
  "śródziemnomorski styl życia",
  "ukryta perła",
  "ukryty klejnot",
  "uczta dla zmysłów",
  "symfonia smaków",
  "eksplozja smaków",
  "mieszanka tradycji i nowoczesności",
  "tradycja spotyka nowoczesność",
  "idealne miejsce",
  "doskonały wybór",
  "coś dla każdego",
  "doświadczenie, którego nie zapomnisz",
  "w samym sercu",
  "dom marzeń",
  "dla najbardziej wymagających",
  "obowiązkowy punkt programu",
  "eksperci twierdzą",
  "eksperci wskazują",
  "według ekspertów",
  "badania pokazują",
  "powszechnie uważa się",
  "mówi się, że",
  "mam nadzieję, że to pomoże",
  "oto"
 ],
 "closers": [
  "Podsumowując,",
  "Reasumując,",
  "Konkludując,",
  "Krótko mówiąc,",
  "W skrócie,",
  "Jednym słowem,",
  "Na koniec",
  "Na zakończenie",
  "Na zakończenie warto dodać",
  "W ostatecznym rozrachunku",
  "Ostatecznie",
  "Finalnie",
  "Tak więc",
  "Zatem",
  "Jak widać,",
  "Jak pokazuje powyższe zestawienie,",
  "Wniosek jest prosty:",
  "Wnioski są jasne:",
  "W świetle powyższego",
  "Mając to wszystko na uwadze,",
  "Biorąc to wszystko pod uwagę,",
  "Wszystko to sprawia, że",
  "Jedno jest pewne:",
  "Czas pokaże,",
  "Patrząc w przyszłość,",
  "Spoglądając w przyszłość,",
  "Podsumowanie",
  "Najważniejsze wnioski"
 ],
 "openers": [
  "Warto zauważyć, że",
  "Warto podkreślić, że",
  "Warto wspomnieć, że",
  "Warto mieć na uwadze, że",
  "Należy zaznaczyć, że",
  "Należy podkreślić, że",
  "Należy pamiętać, że",
  "Nie sposób nie wspomnieć o",
  "Oto co musisz wiedzieć",
  "Oto wszystko, co warto wiedzieć",
  "Oto kilka powodów, dla których",
  "Oto przewodnik po",
  "Czy kiedykolwiek zastanawiałeś się, jak",
  "Zastanawiasz się, jak",
  "Marzysz o",
  "Szukasz idealnego miejsca",
  "Wyobraź sobie",
  "Niezależnie od tego, czy",
  "W dzisiejszym szybko zmieniającym się świecie",
  "W erze cyfrowej",
  "W ostatnich latach coraz więcej",
  "Wyspa Afrodyty od wieków",
  "Cypr, wyspa położona na skrzyżowaniu",
  "W niniejszym artykule",
  "W tym przewodniku dowiesz się",
  "Odkryj",
  "Zanurz się w"
 ],
 "sheet": [
  "Open news with the fact, not the setting: who did what, where, when, and the number that matters, in the first sentence; a Polish lead is one sentence of 20 to 30 words and does not begin with a date, a weather note or a generalisation about Cyprus.",
  "Give the second sentence a new fact or the source of the first; never restate the lead in softer words.",
  "Prefer a concrete finite verb to a noun phrase: „otworzył” not „dokonał otwarcia”, „kupił” not „dokonał zakupu”, „zdecydowano” not „podjęto decyzję o”; ban w celu, w ramach, w oparciu o, w zakresie, poprzez as default connectors.",
  "Use aspect with intention: perfective („zdecydował”, „otworzył”, „przyjęto”) for events that happened, imperfective („trwa”, „rośnie”, „obowiązuje”) for states and processes; do not narrate a news event in the imperfective.",
  "Use active voice and a human or institutional subject; replace „jest oferowany”, „zostaje zrealizowany” with „oferuje”, „zrealizowała”, or restructure with an impersonal „zbudowano”.",
  "Write „jest”, „ma”, „leży”, „stoi”, „mieści się” instead of „stanowi”, „posiada”, „charakteryzuje się”, „pełni funkcję”; keep „stanowić” only for literal proportions („stanowią 18 proc. rynku”).",
  "Allow at most one imiesłów przysłówkowy (-ąc) per sentence, never as a trailing comment that interprets the previous clause („…, podkreślając znaczenie…”); turn the second action into a new sentence or into „i” plus a finite verb.",
  "Do not begin consecutive sentences or paragraphs with Ponadto, Dodatkowo, Co więcej, Jednakże, Natomiast, Tym samym; most links belong inside the sentence („a”, „ale”, „bo”, „więc”, „choć”) or nowhere, and a paragraph should hold together by its logic.",
  "Sentence-initial „Jednak” is permitted once or twice per article, not per paragraph; prefer „Ale” after a full stop for a harder turn and „choć/chociaż” inside the sentence for a softer one.",
  "Never write „Warto zauważyć”, „Warto podkreślić”, „Należy zaznaczyć”, „Nie sposób nie wspomnieć”; state the point itself. If something deserves emphasis, give it a number, a name or a position at the end of the sentence.",
  "Do not promise the reader what the article will cover („W tym artykule dowiesz się”, „Oto co musisz wiedzieć”); a quality magazine just starts and the structure is visible from the subheads.",
  "Address the reader as „Państwo” only in service pieces and relocation guides, in the third person („inwestor”, „kupujący”, „rodzina”) elsewhere; avoid „Ty/Twój” and imperative calls to action („Nie przegap!”, „Odkryj”, „Zarezerwuj już dziś”).",
  "Never end with a moral, a forward-looking flourish or a summary („Podsumowując”, „Jedno jest pewne”, „Czas pokaże”, „otwiera nowy rozdział”); end on the last fact, a quote, a date of the next step or a concrete image.",
  "Avoid „Po pierwsze… po drugie… po trzecie” scaffolding and labelled blocks („Najważniejsze punkty”, „Kluczowe wnioski”) in running prose; if steps matter, use a real numbered list in a service box, with each item carrying a concrete detail.",
  "Replace „nie tylko… ale także” and „to coś więcej niż…” with one plain claim and a number; if a real contrast exists, state both halves as facts („Hotel ma 40 pokoi, ale tylko dwa z widokiem na port.”).",
  "Do not default to triplets; vary list length (two, four, one) and prefer a single exact example to „A, B i C”; avoid „od X, przez Y, po Z” as a way to sound wide.",
  "Attribute with named, dated sources: „Według raportu Cyprus Land Registry z września…”, „powiedziała prof. Maria Hadjiioannou z Uniwersytetu Cypryjskiego”; never „eksperci twierdzą”, „badania pokazują”, „powszechnie uważa się”.",
  "Rotate attribution verbs naturally: „powiedział”, „wyjaśnił”, „przyznał”, „zauważył”, „dodał”, „odparł”, „zastrzegł”, „ocenił”, „wskazał”, „przypomniał”; „podkreślił” at most once per article and put the verb after the quote or in the middle of it.",
  "Quote in Polish typography: „cudzysłów dolny i górny”, nested ‚pojedyncze’ (or »…« if the house style says so), full stop after the closing quote when the quote is not a full sentence; never English “curly” or \"straight\" quotes and not «guillemets».",
  "In running prose use the spaced pauza: „Miasto – jak mówią mieszkańcy – nie śpi.” Do not write unspaced em dashes in the English manner; reserve the dialogue dash (– Tak) for the start of a quoted line in an interview or reportage.",
  "Limit pauzy to one or two per paragraph; where an English-trained draft uses a dash for emphasis, use a full stop, a colon or a bracket.",
  "Write numbers Polish-style: a decimal comma („2,5 mln euro”, „3,4 proc.”), a non-breaking space as the thousands separator from five digits up („12 500 euro”, four-digit numbers may stay compact but must be consistent), and the currency after the figure („250 000 euro”, „1,2 mld euro”), never €250,000.",
  "Write „proc.” in running prose and the % sign with no space in tables and headlines; write „mln” and „mld” after the number with a space and without a full stop.",
  "Write dates as „5 października 2026” (no „roku” needed unless it clarifies), months in lower case and in the genitive, weekdays in lower case; times as „18.30” or „godz. 18.30”, 24-hour clock, never „6 pm”.",
  "Set headlines and subheads in sentence case with no final full stop: only the first word and proper names are capitalised; never English Title Case, and no colon-subtitle formula of „Nazwa: wyjaśnienie”.",
  "Decline foreign and Greek names and use Polish exonyms: Cypr, Nikozja, Limassol, Larnaka, Pafos, Famagusta, Kirenia; „w Limassol”, „w Larnace”, „z Pafos”; give the Greek or English proper name once in brackets only when the reader may need to search for it.",
  "Vary sentence length on purpose: after two sentences of 20 words or more, put one of 4 to 10 words; a Polish magazine paragraph breathes through an occasional fragment, a question that is answered at once, a short dry aside.",
  "Use the Polish word order: put the new information at the end of the clause („Nowy terminal otworzy w kwietniu spółka Hermes”), not the English subject-verb-object default, and do not stack genitive chains („w celu zapewnienia poprawy jakości obsługi klienta”).",
  "Prefer the Polish idiom over the English calque: „w gruncie rzeczy” not „pod koniec dnia”, „jedyny w swoim rodzaju” not „unikalny”, „zwykle” not „typowo”, „kierować” not „adresować”, „opiera się na” not „bazuje na”, „w ostatnim czasie” only when no date is known.",
  "Keep stock Cyprus words out: wyspa Afrodyty, turkusowa woda, strategiczne położenie, skrzyżowanie trzech kontynentów, ukryta perła, śródziemnomorski styl życia; replace with the actual street, price, minute count, grape or year.",
  "Ban estate-agent and press-release register in editorial pieces: „idealna lokalizacja”, „dom marzeń”, „z dumą ogłasza”, „wyznacza nowe standardy”, „dla najbardziej wymagających”; give measurable facts (metraż, cena za m², odległość od morza, rok oddania).",
  "Do not use emoji, arrows, bullet symbols or Markdown markers in body text; no sign-off, no offer of further help, no „Oto” at the start.",
  "Avoid the intensifier layer („niezwykle”, „naprawdę”, „absolutnie”, „zdecydowanie”, „prawdziwy”) and the hype adjective layer („wyjątkowy”, „niepowtarzalny”, „magiczny”); one precise detail beats three adjectives.",
  "Let one idea of your own stand in each section: a figure the reader can verify, a named person, a place and date, a disagreement or a doubt; a Polish editor will cut a paragraph that could appear in any article on any island."
 ],
 "pairs": [
  {
   "bad": "Cypr, wyspa Afrodyty, od wieków przyciąga turystów swoimi turkusowymi wodami i bogatym dziedzictwem kulturowym.",
   "good": "W lipcu na Cypr przyleciało 389 tysięcy turystów, o 6 proc. więcej niż przed rokiem – wynika z danych urzędu statystycznego.",
   "why": "Replaces the stock Cyprus opener with a dated, sourced fact in a Polish lead."
  },
  {
   "bad": "Warto zauważyć, że nowa ustawa odgrywa kluczową rolę w kształtowaniu rynku nieruchomości.",
   "good": "Od 1 stycznia kupujący zapłaci za przeniesienie własności o połowę mniej: opłata spadnie z 8 do 4 proc. ceny nieruchomości.",
   "why": "Cuts the throat-clearing and the empty significance verb; the sentence now carries the actual change and number."
  },
  {
   "bad": "Hotel posiada 120 pokoi i charakteryzuje się nowoczesnym designem, podkreślając swoją pozycję na rynku luksusowym.",
   "good": "Hotel ma 120 pokoi, większość z balkonem od strony morza. Wnętrza urządziła pracownia z Bejrutu: dużo ciemnego drewna i żadnego złota.",
   "why": "Removes posiada and charakteryzuje się and the imiesłów closer; adds specific detail in two plain sentences."
  },
  {
   "bad": "Ponadto Limassol stanowi idealne miejsce zarówno dla inwestorów, jak i dla rodzin. Dodatkowo oferuje szeroką gamę atrakcji.",
   "good": "Limassol przyciąga inwestorów portem jachtowym i dwoma szpitalami prywatnymi, a rodziny – szkołami międzynarodowymi, których jest tu siedem.",
   "why": "One connector-free sentence with concrete reasons replaces two stacked connectors and empty praise."
  },
  {
   "bad": "Eksperci twierdzą, że rynek będzie nadal dynamicznie się rozwijał w nadchodzących latach.",
   "good": "Zdaniem Andreasa Christodoulou z Cyprus Real Estate Agents Association ceny wzrosną w przyszłym roku o 4 do 6 proc., o ile nie zmieni się polityka kredytowa banków.",
   "why": "Vague attribution replaced with a named source, a range and a condition."
  },
  {
   "bad": "To nie tylko restauracja, ale także doświadczenie, które na długo zapadnie w pamięć. Odkryj symfonię smaków!",
   "good": "Restauracja w Omodos serwuje cztery dania dziennie, każde z tego, co rano przyniesie sąsiad z gospodarstwa. Zamówiona w ostatniej chwili wersja z jagnięciną była najlepsza – mięso odchodziło od kości samo.",
   "why": "Replaces the contrast formula, calque experience phrase and the second-person call with observation and one tasting detail."
  },
  {
   "bad": "Podsumowując, można stwierdzić, że Cypr oferuje wiele możliwości dla każdego. Czas pokaże, co przyniesie przyszłość.",
   "good": "Kolejne wnioski o wizę cyfrową rozpatrzy ministerstwo do końca listopada; pierwsze decyzje mają zapaść w grudniu.",
   "why": "Ends on the next verifiable step instead of a summary and a moral."
  },
  {
   "bad": "Cena nieruchomości wynosi €250,000 i obejmuje 2.5% podatku. Termin: October 5, 2026.",
   "good": "Mieszkanie kosztuje 250 000 euro, a podatek wynosi 2,5 proc. Umowę trzeba podpisać do 5 października 2026.",
   "why": "Polish number, currency and date conventions: decimal comma, currency after the figure, genitive month."
  },
  {
   "bad": "Jak powiedział ekspert, “to bardzo ważna zmiana”. Dodał też, że “rynek zareaguje szybko” — co podkreśla jej znaczenie.",
   "good": "– To zmiana, której czekaliśmy od lat – powiedział Kostas Georgiou. – Rynek zareaguje w ciągu miesiąca.",
   "why": "Polish dialogue dash and quotation style, no imiesłów tail, no English quotes or unspaced em dash."
  },
  {
   "bad": "Dokonanie zakupu nieruchomości w celu uzyskania pasywnego dochodu stanowi popularne rozwiązanie w ostatnich latach.",
   "good": "Coraz więcej Polaków kupuje na Cyprze mieszkania pod wynajem: w ubiegłym roku było to 410 transakcji, trzy razy więcej niż w 2021.",
   "why": "Verb replaces nominalisation chain; the vague trend is turned into a figure and a comparison."
  }
 ],
 "desks": {
  "news": "Polish news starts with the hard fact in one sentence of 20 to 30 words, then source and context; no scene-setting, no adjectives, past tense for events, present tense for what continues. Attribute every claim to a named person or document and use „poinformował”, „oświadczył”, „zapowiedział” with variety; close on the next step, not a summary.",
  "business": "Gazeta Wyborcza and Rzeczpospolita business pages lead with the number and the company: kwota, spółka, termin, then the reason. Use „mln euro”, „proc.”, name the counterparty and the regulator, give one figure for comparison (year-on-year, versus competitor), and avoid buzzwords such as synergia, ekosystem, innowacyjny.",
  "property_legal": "Explainer register of Rzeczpospolita and Prawo.pl: precise, in the third person, with the statute (ustawa, artykuł, numer) and the date it takes effect, then who is affected and what they must do. Give costs in euro with a decimal comma, avoid agent hype and generic disclaimers, and show a worked example with real figures (cena, opłata, podatek).",
  "relocation_guide": "Service journalism in the manner of Polityka and Wyborcza Magazyn: step by step but never a listicle of generalities; each step carries an authority, a price, a deadline or a document name. Address the reader in the third person or the formal „Państwo”, mention the Polish-specific issue (podatek, ZUS, uznanie dyplomu, szkoła) and a pitfall from real experience.",
  "economy": "Economic reporting in the style of Rzeczpospolita and Polityka: data first (PKB, inflacja, bezrobocie, dług), the source and the period, then one interpretation attributed to a named economist, with a comparison to the EU average or to Poland. No „dynamiczny rozwój”; use verbs such as wzrosło, spadło, zwolniło and give percentage points exactly.",
  "culture": "Polityka and Wyborcza culture pages write with a position: a concrete work, a date and a place, then a judgement in the critic's own voice. Replace „unikalny”, „fascynujący”, „bogate dziedzictwo” with a precise description (technika, epoka, autor, materiał) and one comparison the educated reader will recognise.",
  "food": "Food writing in Kuchnia and Wyborcza's Wysokie Obcasy is specific and sensory without cliché: name the dish, the producer, the price, the season, the texture and the salt. Avoid „uczta dla zmysłów”, „symfonia smaków”, „kulinarna podróż”; use short sentences for taste and a longer one for a scene, and mention the table, not only the plate.",
  "fashion_lifestyle": "Vogue Polska and Forbes Life Polska favour cool, observant sentences: name the designer, the material, the cut, the price and the occasion; no „must-have”, „ponadczasowy”, „dodaje szyku”. Let the writer be a witness (what she saw at the show or in the atelier) and keep the tone confident, ironic at most, never gushing.",
  "travel": "Polish travel writing (National Geographic Traveler, Wysokie Obcasy) is built from a first-hand scene: a road, a smell, a timetable, a price in euro, a person who speaks. Give distance in kilometres and minutes, opening hours, how to get there without a car, and one honest downside; ban „ukryta perła”, „raj dla”, „turkusowa woda”, „obowiązkowy punkt”.",
  "events": "An event notice states what, where, when, who and how much in the first lines (nazwa, miejsce, data „5 października”, godzina „18.30”, cena „40 euro”); then a concrete programme line by line and the one thing that distinguishes it. No „nie zabraknie atrakcji”, no „serdecznie zapraszamy”; end with the practical details (rezerwacja, parking, link).",
  "interview": "Polish interviews run as questions and answers with the speaker's voice kept: the intro is a tight 80 to 120-word profile with a fact that explains why this person, then dialogue with em or en dash. Questions are short and real (not „Jak się Pan czuje jako wizjoner?”); keep the interviewee's hesitations and corners, and avoid „podzielił się z nami przemyśleniami”.",
  "review": "Polish criticism (Polityka, Newsweek, Wyborcza) gives a verdict in the lead or the first third, then justifies it with named dishes, scenes, rooms or passages and a fair counterpoint; a score or a stars line is optional but explained. No „gorąco polecamy”, no „idealne miejsce”; state who it is for and what it costs.",
  "people": "Portrait journalism in Newsweek Polska and Forbes Polska: a scene or a turning point first, then biography as a few dated, checkable facts, a line from the subject, a line from someone who knows them, and one doubt. Avoid „historia sukcesu”, „wizjoner”, „z pasją”; show the work (revenue, clients, hours, mistakes) rather than adjectives."
 }
};

export default data;
