// GENERATED by scripts/voice/build-data.mjs from the RO linguist source. Edit the source data and regenerate; do not hand-edit.
import type { LangVoiceData } from '@/lib/voice/types';

const data: LangVoiceData = {
 "lang": "ro",
 "tells": [
  {
   "key": "ro_leak_help",
   "label": "Chatbot sign-off / identity statement (Sper că v-a ajutat, ca asistent AI)",
   "severity": "high",
   "kind": "word",
   "alts": [
    "sper că (?:v-a|ți-a|te-a|vă|te) (?:ajut\\p{L}*|fi (?:de folos|util\\p{L}*))",
    "sper că (?:aceste|această|acest|aceasta) (?:informații|răspuns|articol|text|variantă|versiune|explicație)\\p{L}*",
    "în calitate de (?:model|asistent|inteligență)\\p{L}*(?: (?:de limbaj|virtual|AI|artificial\\p{L}*))?",
    "sunt (?:aici|la dispoziția dumneavoastră) să (?:te|vă) ajut",
    "ca (?:asistent|model) (?:AI|virtual|lingvistic|de inteligență artificială)",
    "sunt un (?:model|asistent) (?:de limbaj|AI|virtual)"
   ]
  },
  {
   "key": "ro_leak_offer",
   "label": "Chatbot follow-up offer (Spune-mi dacă vrei modificări)",
   "severity": "high",
   "kind": "word",
   "alts": [
    "(?:spune|spuneți|anunță|anunțați)(?:-mi| -mă|-mă) dacă",
    "dacă (?:ai|aveți) nevoie de (?:alte|mai multe|ajutor|modificări|clarificări|ajustări)",
    "dacă (?:dorești|doriți|vrei|vreți) (?:să (?:ajustez|modific|extind|rescriu|adaug|scurtez)|o (?:versiune|variantă))",
    "(?:nu ezita|nu ezitați) să (?:mă )?(?:contactezi|contactați|întrebi|întrebați|ceri|cereți)",
    "pot (?:să )?(?:adaptez|ajustez|extind|scurtez|rescriu) (?:textul|articolul|versiunea)"
   ]
  },
  {
   "key": "ro_leak_knowledge",
   "label": "Model knowledge-cutoff / no-access disclaimer",
   "severity": "high",
   "kind": "word",
   "alts": [
    "(?:până la|după) data (?:mea )?(?:limită|de antrenare|de actualizare)",
    "cunoștințele mele (?:se opresc|sunt limitate|nu includ)",
    "nu am acces (?:la|în timp real)",
    "nu pot (?:să )?(?:accesa|verifica|naviga|confirma) (?:în timp real|internetul|informații actuale|site-ul)",
    "informațiile (?:mele )?(?:sunt actualizate|nu sunt actualizate) (?:până|la)",
    "ultima mea actualizare"
   ]
  },
  {
   "key": "ro_leak_placeholder",
   "label": "Template placeholder or lorem ipsum left in text",
   "severity": "high",
   "kind": "word",
   "alts": [
    "\\[(?:inserați|introduceți|inserează|introdu|numele|nume|data|link|sursa|citat|adăugați|adaugă|URL)[^\\]\\n]{0,60}\\]",
    "lorem ipsum",
    "\\{\\{[^}\\n]{1,40}\\}\\}",
    "(?:link|URL|sursă) aici"
   ]
  },
  {
   "key": "ro_markdown_residue",
   "label": "Markdown residue (**bold**, ## heading, backticks, [text](url))",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\*\\*[^*\\n]{1,80}\\*\\*",
    "#{2,4}(?=\\s)",
    "`[^`\\n]{1,60}`",
    "\\[[^\\]\\n]{2,60}\\]\\(https?:[^)\\s]+\\)"
   ]
  },
  {
   "key": "ro_throat_start",
   "label": "Throat-clearing opener (Este esențial să înțelegem, Vom explora, În acest articol)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Este (?:esențial|crucial|util|necesar|bine|vital) să (?:înțelegem|înțelegeți|menționăm|reținem|rețineți|știm|știți|precizăm|clarificăm|avem în vedere)",
    "Este de (?:remarcat|subliniat|reținut|precizat|notat)",
    "Este demn de (?:remarcat|menționat|reținut|notat)",
    "Demn de (?:remarcat|menționat|reținut)",
    "De (?:menționat|remarcat|reținut|precizat|subliniat) că",
    "Trebuie (?:menționat|subliniat|precizat|reținut|remarcat|clarificat) (?:aici )?că",
    "Nu este un secret că",
    "Nu e un secret că",
    "Este bine cunoscut că",
    "Se știe că",
    "Este cunoscut faptul că",
    "În acest (?:articol|ghid|material)",
    "Acest (?:articol|ghid|material) (?:își propune|vă va|te va|explorează|analizează|prezintă)",
    "Vom (?:explora|analiza|examina|descoperi|investiga|discuta)",
    "Să (?:explorăm|analizăm|examinăm|începem|ne uităm|aruncăm o privire)",
    "Haideți să",
    "Hai să",
    "Înainte de a (?:intra|trece|începe|ne scufunda)",
    "Pentru a (?:înțelege|aprecia) (?:pe deplin|cu adevărat|mai bine)"
   ]
  },
  {
   "key": "ro_throat_mid",
   "label": "Throat-clearing inside paragraph (este important să reținem, de menționat că)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "este (?:important|esențial|crucial|util|necesar|vital) să (?:rețineți|reținem|înțelegem|înțelegeți|menționăm|precizăm|subliniem|clarificăm|notăm)",
    "trebuie (?:menționat|subliniat|precizat|reținut|remarcat|clarificat|notat) (?:aici )?că",
    "de (?:menționat|remarcat|reținut|precizat) că",
    "este (?:demn|de remarcat|de subliniat|de reținut)",
    "demn de (?:remarcat|menționat|reținut)",
    "ar trebui (?:menționat|subliniat|precizat) că"
   ]
  },
  {
   "key": "ro_transition_start",
   "label": "Paragraph-opening connective repeated (De asemenea, În plus, Totodată, Cu toate acestea)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "De asemenea",
    "În plus",
    "Mai mult(?: decât atât)?",
    "Totodată",
    "Pe de altă parte",
    "Cu toate acestea",
    "Nu în ultimul rând",
    "De altfel",
    "În același timp",
    "Prin urmare",
    "În consecință",
    "Astfel",
    "Drept urmare",
    "Pe lângă (?:aceasta|acestea|acest lucru)",
    "Pe de o parte"
   ],
   "min": 3
  },
  {
   "key": "ro_connective_density",
   "label": "Connective pile-up across the text (de asemenea, totodată, în plus, prin urmare)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "de asemenea",
    "în plus",
    "totodată",
    "mai mult decât atât",
    "cu toate acestea",
    "prin urmare",
    "în consecință",
    "de altfel",
    "în același timp",
    "pe de altă parte",
    "pe lângă (?:aceasta|acestea|acest lucru)",
    "drept urmare",
    "nu în ultimul rând"
   ],
   "min": 5
  },
  {
   "key": "ro_enum_scaffold",
   "label": "Enumeration scaffolding (în primul rând, în al doilea rând, aspecte cheie, după cum am menționat)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "în primul rând",
    "în al doilea rând",
    "în al treilea rând",
    "primul aspect",
    "al doilea aspect",
    "un alt aspect (?:important|esențial|cheie)?",
    "un alt factor (?:important|esențial|cheie)?",
    "(?:aspecte|puncte|factori|elemente|idei|concluzii) cheie",
    "după cum (?:am|s-a|vom) (?:menționat|văzut|arătat|vedea|precizat)",
    "așa cum (?:am|s-a) (?:menționat|văzut|arătat|precizat)",
    "în secțiunile (?:următoare|de mai jos)",
    "mai jos (?:sunt|găsiți|vom|vedem)",
    "în continuare vom"
   ],
   "min": 2
  },
  {
   "key": "ro_listicle_frame",
   "label": "Listicle/guide frame (ghid complet, tot ce trebuie să știți, o privire aprofundată)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:un|acest|ghidul|ghid) (?:ghid )?(?:complet|cuprinzător|definitiv|esențial|detaliat|practic)",
    "tot ce (?:trebuie|merită|ar trebui) să (?:știți|știi|aflați|afli|reții|rețineți)",
    "totul despre",
    "o privire (?:de ansamblu|aprofundată|detaliată|mai atentă|mai îndeaproape)",
    "o analiză (?:aprofundată|detaliată|cuprinzătoare|completă)",
    "analiză aprofundată",
    "iată (?:câteva|cele|principalele|primele|cinci|trei|șapte|zece|motivele|cum|de ce|ce)",
    "top (?:3|5|7|10|trei|cinci|zece)"
   ]
  },
  {
   "key": "ro_rhetorical_start",
   "label": "Rhetorical-question / imagine-this opener",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Imaginați-vă",
    "Imaginează-ți",
    "Închide(?:ți)? ochii",
    "V-ați (?:întrebat|gândit) vreodată",
    "Te-ai (?:întrebat|gândit) vreodată",
    "Ați (?:auzit|visat) vreodată",
    "Ai (?:auzit|visat) vreodată",
    "Gândiți-vă (?:la|că)",
    "Gândește-te (?:la|că)",
    "Luați în considerare",
    "Dar ce (?:înseamnă|face|aduce) (?:de fapt |cu adevărat )?(?:asta|toate acestea)",
    "Ce înseamnă (?:asta|toate acestea)",
    "Dar de ce (?:contează|este important|este atât de)",
    "Care este (?:adevărul|secretul|motivul) (?:din spatele|real)"
   ]
  },
  {
   "key": "ro_greeting_start",
   "label": "Blog-style greeting / address of readers",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Dragi cititori",
    "Dragă cititorule",
    "Stimați cititori",
    "Stimate cititor",
    "Bine ați venit",
    "Bun venit",
    "Salutare",
    "Bună ziua",
    "Bună dragilor",
    "Salut,? prieteni"
   ]
  },
  {
   "key": "ro_if_you_start",
   "label": "Second-person “Dacă plănuiți / Dacă ești în căutarea” opener",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Dacă (?:plănuiți|plănuiești|visați|visezi|vă gândiți|te gândești|ați visat|ai visat|vă doriți|îți dorești|căutați|cauți|sunteți în căutarea|ești în căutarea|sunteți pasionat\\p{L}*|ești pasionat\\p{L}*|sunteți un|ești un|sunteți o|ești o|iubiți|iubești|vă place|îți place)"
   ]
  },
  {
   "key": "ro_cold_open",
   "label": "Stock travel/estate cold open (Situată în inima…, Cuibărit între…, Cipru, cunoscut pentru…)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Situat\\p{L}* în (?:inima|sud-estul|estul|nordul|sudul|centrul|extremitatea)",
    "Cuibărit\\p{L}*",
    "Aflat\\p{L}* (?:în inima|la răscruce|la confluența|la poalele)",
    "Scăldat\\p{L}* (?:de|în) (?:soare|lumină|apele|valurile)",
    "(?:Insula )?Cipru,? (?:cunoscut\\p{L}*|renumit\\p{L}*|faimos\\p{L}*|binecunoscut\\p{L}*|insula)",
    "De secole",
    "De-a lungul (?:secolelor|timpului|istoriei|anilor)",
    "Pe parcursul istoriei",
    "În (?:peisajul|contextul) (?:actual|economic actual|global)",
    "În zilele noastre",
    "În lumea (?:modernă|de azi|de astăzi)",
    "Astăzi,? mai mult ca oricând",
    "Mai mult (?:ca|decât) oricând",
    "Odată cu (?:trecerea|apariția|dezvoltarea|creșterea)"
   ]
  },
  {
   "key": "ro_stance_open",
   "label": "Stance/assertion opener repeated (Evident, Desigur, Realitatea este că, Să fim sinceri)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Evident",
    "Desigur",
    "Bineînțeles",
    "Firește",
    "Într-adevăr",
    "Indiscutabil",
    "Incontestabil",
    "Fără îndoială",
    "Cert este că",
    "Este (?:clar|evident|cert|adevărat) că",
    "Realitatea este că",
    "Adevărul (?:este|e) că",
    "Să fim sinceri",
    "Să recunoaștem",
    "Trebuie să recunoaștem",
    "Nu încape îndoială"
   ],
   "min": 2
  },
  {
   "key": "ro_generic_heading",
   "label": "Generic section label (Introducere, Concluzii, Aspecte cheie, Întrebări frecvente)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "Introducere",
    "Concluzii",
    "Rezumat",
    "Sumar",
    "Cuprins",
    "Puncte cheie",
    "Aspecte cheie",
    "Idei principale",
    "Cele mai importante concluzii",
    "Ce trebuie să rețineți",
    "De reținut",
    "Întrebări frecvente",
    "FAQ",
    "TL;?DR",
    "Gânduri finale",
    "Cuvinte finale",
    "Ultimele cuvinte",
    "Rezumând"
   ]
  },
  {
   "key": "ro_label_lead",
   "label": "Label-style paragraph lead (Avantaje:, Dezavantaje:, Sfat util:, Notă importantă:)",
   "severity": "low",
   "kind": "start",
   "alts": [
    "Avantaje",
    "Dezavantaje",
    "Beneficii",
    "Sfat (?:util|pro|profesionist|de expert|de la|rapid)",
    "Pro tip",
    "Notă importantă",
    "Atenție",
    "Bonus",
    "Pontul zilei",
    "Verdict"
   ],
   "min": 2
  },
  {
   "key": "ro_closer_phrase",
   "label": "Stock closing line (rămâne de văzut, timpul va arăta, viitorul pare luminos)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "rămâne de văzut",
    "timpul (?:va|ne va) (?:arăta|spune|decide|dovedi)",
    "viitorul (?:este|pare|se anunță|arată|se prefigurează) (?:luminos|strălucit|promițător|plin de)",
    "un lucru (?:este|e|rămâne) (?:cert|sigur|clar)",
    "nu încape îndoială că",
    "mingea (?:este|e) (?:acum )?în terenul",
    "privind (?:spre|către|în) (?:viitor|perspectivă)",
    "pe măsură ce (?:Cipru|insula|piața|sectorul|țara|industria|orașul) (?:continuă|evoluează|se dezvoltă|se transformă|își)",
    "va continua să (?:joace|modeleze|atragă|prospere|evolueze|inspire|fascineze|se dezvolte|crească)",
    "merită (?:urmărit|ținut sub observație|urmărită)(?: îndeaproape| cu atenție)?",
    "calea (?:către|spre) (?:succes|viitor|prosperitate|reușită)",
    "în încheiere",
    "ultimul cuvânt nu a fost spus"
   ]
  },
  {
   "key": "ro_closing2",
   "label": "Conclusion-style paragraph opener (În încheiere, Putem spune că, Privind spre viitor)",
   "severity": "medium",
   "kind": "start",
   "alts": [
    "În încheiere",
    "Încheiem",
    "Ca (?:o )?(?:concluzie|încheiere)",
    "Putem (?:spune|concluziona|afirma) că",
    "Se poate (?:spune|concluziona|afirma) că",
    "Privind (?:spre|către|în) (?:viitor|perspectivă)",
    "Pe viitor",
    "În perspectivă",
    "Sintetizând",
    "În linii mari",
    "Într-un cuvânt",
    "Un lucru (?:este|e) (?:cert|clar|sigur)",
    "Rămâne de văzut",
    "Așa stând lucrurile",
    "Cu siguranță",
    "Viitorul",
    "Fără îndoială",
    "Toate acestea (?:arată|demonstrează|sugerează|confirmă)",
    "Într-un final"
   ]
  },
  {
   "key": "ro_empty_signif",
   "label": "Empty significance chain (acest lucru subliniază/reflectă, marchează o cotitură, un semnal clar)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:acest lucru|aceasta|acest fapt|toate acestea|această (?:evoluție|tendință|decizie|mișcare|schimbare)) (?:subliniază|evidențiază|demonstrează|reflectă|sugerează|indică|ilustrează|reiterează|reafirmă|confirmă|consolidează|întărește|semnalează|atestă)",
    "ceea ce (?:subliniază|evidențiază|demonstrează|reflectă|ilustrează|sugerează|reafirmă|confirmă|atestă)",
    "un (?:semnal|semn) (?:clar|puternic|că)",
    "marchează (?:un|o) (?:moment|pas|punct|capitol|etapă|nouă|schimbare|cotitură|piatră)\\p{L}*",
    "o piatră de hotar",
    "o cotitură (?:majoră|importantă|decisivă|istorică)",
    "un pas (?:important|major|semnificativ|decisiv|uriaș|înainte)",
    "ilustrează (?:modul|cum|faptul)",
    "reflectă (?:angajamentul|dorința|tendința|importanța|creșterea|interesul|ambiția|voința|dinamica)"
   ]
  },
  {
   "key": "ro_importance",
   "label": "Importance adjectives (rol esențial/cheie, importanță crucială, de maximă importanță)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "rol (?:crucial|esențial|cheie|central|major|vital|fundamental|decisiv|determinant|strategic)",
    "(?:importanța|rolul|semnificația|relevanța|valoarea) (?:crucială|esențială|vitală|deosebită|majoră|cheie|centrală|fundamentală|strategică|capitală)",
    "(?:de|o) importanță (?:crucială|majoră|capitală|vitală|strategică|deosebită|fundamentală|maximă)",
    "de maximă importanță",
    "extrem de important\\p{L}*",
    "factor (?:crucial|esențial|cheie|determinant|decisiv)",
    "element (?:crucial|esențial|cheie|central|fundamental)"
   ]
  },
  {
   "key": "ro_gerund_empty",
   "label": "Empty gerund tail (…, subliniind/evidențiind/reflectând/demonstrând)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    ",\\s*(?:subliniind|evidențiind|reflectând|demonstrând|ilustrând|reafirmând|consolidând|conturând|confirmând|reiterând|atestând|semnalând|punând în (?:lumină|valoare|evidență)|marcând|lăsând să se înțeleagă)"
   ],
   "min": 2
  },
  {
   "key": "ro_gerund_serve",
   "label": "Service gerund tail (…, asigurând/oferind/contribuind/facilitând)",
   "severity": "low",
   "kind": "word",
   "alts": [
    ",\\s*(?:asigurând|oferind|contribuind|facilitând|sporind|permițând|garantând|aducând|creând|întărind|stimulând|alimentând|îmbogățind|punând bazele)"
   ],
   "min": 3
  },
  {
   "key": "ro_copula_reprez",
   "label": "Copula inflation: reprezintă / constituie instead of este",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "reprezint[ăa]",
    "reprezentând",
    "constitui[ea]",
    "constituind",
    "reprezentat\\p{L}*",
    "constituit\\p{L}*"
   ],
   "min": 3
  },
  {
   "key": "ro_copula_dispune",
   "label": "Copula inflation: dispune de / se caracterizează prin / beneficiază de",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "dispun?e de",
    "se caracterizează prin",
    "se distinge prin",
    "beneficiază de",
    "se bucură de (?:o|un|numeroase|multe)",
    "se mândre(?:ște|sc) cu",
    "se laudă cu",
    "etalează",
    "etalând",
    "găzduiește (?:o|un|numeroase|multe)",
    "se întinde pe"
   ],
   "min": 2
  },
  {
   "key": "ro_ai_lexicon",
   "label": "AI abstract vocabulary density (crucial, esențial, semnificativ, robust, holistic, sinergie)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "crucial\\p{L}*",
    "esențial\\p{L}*",
    "vital\\p{L}*",
    "fundamental\\p{L}*",
    "primordial\\p{L}*",
    "semnificativ\\p{L}*",
    "substanțial\\p{L}*",
    "robust\\p{L}*",
    "dinamic\\p{L}*",
    "inovator\\p{L}*",
    "holistic\\p{L}*",
    "sinerg\\p{L}*",
    "paradigm\\p{L}*",
    "transformator\\p{L}*",
    "revoluționar\\p{L}*",
    "multifațet\\p{L}*",
    "multidimensional\\p{L}*",
    "cuprinzător\\p{L}*",
    "complex\\p{L}*",
    "optim\\p{L}*",
    "valorifica\\p{L}*",
    "facilita\\p{L}*",
    "cultiv\\p{L}*",
    "optimiz\\p{L}*",
    "consolid\\p{L}*",
    "crește\\p{L}* (?:gradul|nivelul)"
   ],
   "min": 3
  },
  {
   "key": "ro_ai_metaphor",
   "label": "AI stock metaphors (peisaj, ecosistem, piatră de temelie, catalizator, pilon, punte între)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "peisaj\\p{L}* (?:în schimbare|în continuă|economic|juridic|fiscal|imobiliar|cultural|gastronomic|financiar|digital|actual|competitiv)",
    "ecosistem\\p{L}*",
    "pia?tr[ăa] de temelie",
    "catalizator\\p{L}*",
    "pilon\\p{L}* (?:al|ai|ale|principal|central|esențial)",
    "far călăuzitor",
    "o punte (?:între|către|spre)",
    "motor\\p{L}* (?:al|de) (?:creșterii|dezvoltării|inovației|schimbării)",
    "trambulin[ăa]",
    "teren fertil",
    "jucători (?:cheie|majori)",
    "în centrul atenției",
    "deschide(?:re)? (?:ușa|porțile|calea|drumul) (?:către|spre|pentru)",
    "ușa către",
    "deblochea\\p{L}* (?:potențialul|oportunități|noi)",
    "dezlănțui\\p{L}*",
    "navigh?e\\p{L}* (?:prin )?(?:complexitățile|labirintul|peisajul|hățișul)",
    "tapiseri\\p{L}*",
    "țesătur[ăa] (?:bogată|complexă|culturală|socială)",
    "kaleidoscop\\p{L}*",
    "puls (?:al|vibrant)"
   ]
  },
  {
   "key": "ro_unique_claim",
   "label": "Uniqueness / superlative claims (unic, inegalabil, fără egal, ca nimic altceva)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "unic(?:ă|e|i)?",
    "unicat\\p{L}*",
    "inegalabil\\p{L}*",
    "fără egal",
    "nu are egal",
    "ca nimic altceva",
    "singular\\p{L}*",
    "incomparabil\\p{L}*",
    "de neegalat",
    "fără pereche",
    "fără rival"
   ],
   "min": 3
  },
  {
   "key": "ro_one_of_most",
   "label": "“Unul dintre cele mai …” superlative calque",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:unul|una) dintre (?:cele|cei|cel|cea) mai \\p{L}+"
   ],
   "min": 2
  },
  {
   "key": "ro_hype_extra",
   "label": "Luxury-brochure adjectives (rafinat, sofisticat, impecabil, spectaculos, remarcabil, autentic)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "rafinat\\p{L}*",
    "rafinament\\p{L}*",
    "sofisticat\\p{L}*",
    "impecabil\\p{L}*",
    "spectaculos\\p{L}*",
    "uimitor\\p{L}*",
    "remarcabil\\p{L}*",
    "excepțional\\p{L}*",
    "desăvârșit\\p{L}*",
    "superb\\p{L}*",
    "splendid\\p{L}*",
    "magnific\\p{L}*",
    "grandios\\p{L}*",
    "minunat\\p{L}*",
    "nemaipomenit\\p{L}*",
    "ireproșabil\\p{L}*",
    "irezistibil\\p{L}*",
    "îmbietor\\p{L}*",
    "seducător\\p{L}*",
    "fermecător\\p{L}*",
    "feeric\\p{L}*",
    "idilic\\p{L}*",
    "copleșitor\\p{L}*",
    "autentic\\p{L}*",
    "eleganță",
    "opulen\\p{L}*",
    "fastuos\\p{L}*",
    "lux(?:oas[ăe]|os|oși)",
    "exclusivist\\p{L}*",
    "prestigios\\p{L}*",
    "de excepție",
    "de top"
   ],
   "min": 3
  },
  {
   "key": "ro_sensory",
   "label": "Sensory padding (arome îmbietoare, explozie de gusturi, farmec aparte, atmosferă caldă)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:un )?adevărat(?:ă)? (?:festin|paradis|deliciu|rai|tezaur|regal|spectacol|univers|refugiu|triumf|dans)",
    "arome (?:îmbietoare|irezistibile|autentice|bogate|intense|rafinate)",
    "o explozie de (?:arome|culori|gusturi|savori|senzații|emoții)",
    "deliciu(?:ri)? culinar\\p{L}*",
    "răsfăț culinar",
    "papilele gustative",
    "gusturi (?:autentice|rafinate|bogate)",
    "farmec (?:aparte|deosebit|unic|special|inconfundabil|autentic|irezistibil)",
    "atmosferă (?:caldă|primitoare|relaxată|vibrantă|unică|specială|magică|intimă|elegantă|rafinată)",
    "aer de (?:sărbătoare|vacanță|poveste)",
    "îmbin[ăe] (?:perfect|armonios|magistral|subtil|elegant|rafinat)",
    "îmbinare[a]? (?:perfectă|armonioasă|fericită|desăvârșită|subtilă)",
    "întruchipe(?:ază|ază)",
    "ca (?:într-un|dintr-un) (?:vis|basm|poveste)",
    "direct (?:dintr-o|din) (?:carte poștală|poveste|basm)",
    "carte poștală"
   ]
  },
  {
   "key": "ro_flowery_verbs",
   "label": "Brochure verbs (încântă, fascinează, seduce, cucerește, prinde viață, invită la)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "încântă",
    "fascinează",
    "captivează",
    "seduce",
    "cucerește",
    "vrăjește",
    "răsfață",
    "îmbie",
    "abundă",
    "colcăie",
    "freamătă",
    "pulsează",
    "prinde(?:ți)? viață",
    "prind viață",
    "dă(?:uiește)? viață",
    "aduce la viață",
    "invită (?:la|să)",
    "te invită",
    "vă invită",
    "ne invită",
    "vă îndeamnă",
    "lasă(?:ți)?-(?:te|vă) (?:purtat|sedus|cucerit|vrăjit|răsfățat|surprins)\\p{L}*"
   ],
   "min": 2
  },
  {
   "key": "ro_in_mod",
   "label": "“în mod + adverb” / “într-un mod” padding (calque of English -ly adverbs)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "în mod (?:deosebit|special|particular|constant|semnificativ|eficient|continuu|activ|clar|evident|firesc|remarcabil|real|esențial|natural|substanțial|consecvent|sistematic)",
    "într-un mod (?:eficient|inovator|sustenabil|unic|armonios|autentic|rafinat|special|inedit|deosebit|creativ|elegant)",
    "într-o manieră \\p{L}+",
    "în manieră \\p{L}+"
   ],
   "min": 2
  },
  {
   "key": "ro_hedge_stack",
   "label": "Hedging pile-up (în general, de obicei, relativ, oarecum, într-o anumită măsură)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "în general",
    "de obicei",
    "de regulă",
    "adesea",
    "de multe ori",
    "în mare măsură",
    "într-o (?:anumită|oarecare) măsură",
    "relativ",
    "oarecum",
    "potențial\\p{L}*",
    "ar putea (?:să )?fi",
    "tinde să",
    "pare să",
    "se pare că",
    "este posibil ca"
   ],
   "min": 5
  },
  {
   "key": "ro_in_timp_ce",
   "label": "“în timp ce” overused as English “while”",
   "severity": "low",
   "kind": "word",
   "alts": [
    "în timp ce"
   ],
   "min": 3
  },
  {
   "key": "ro_growing",
   "label": "“din ce în ce mai / tot mai” trend filler",
   "severity": "low",
   "kind": "word",
   "alts": [
    "din ce în ce mai",
    "tot mai (?:popular\\p{L}*|important\\p{L}*|căutat\\p{L}*|atractiv\\p{L}*|apreciat\\p{L}*|mulți|multe|mare|des)",
    "în continuă (?:creștere|expansiune|dezvoltare)",
    "în plină (?:expansiune|ascensiune|dezvoltare|efervescență)"
   ],
   "min": 3
  },
  {
   "key": "ro_vague_quantity",
   "label": "Vague quantifiers instead of figures (creștere semnificativă, interes crescut, cerere în creștere)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "un număr (?:semnificativ|mare|considerabil|tot mai mare|crescut|din ce în ce mai mare|important) de",
    "o creștere (?:semnificativă|considerabilă|substanțială|notabilă|remarcabilă|constantă|accentuată|susținută|rapidă|impresionantă)",
    "o scădere (?:semnificativă|considerabilă|notabilă|accentuată)",
    "o parte (?:considerabilă|semnificativă|importantă) (?:din|a)",
    "interes (?:crescând|crescut|sporit|tot mai mare|în creștere|deosebit|major)",
    "cerere (?:crescândă|tot mai mare|în creștere|ridicată|puternică|robustă)",
    "(?:prețuri|tarife|costuri|oferte) (?:competitive|accesibile|atractive|rezonabile|avantajoase)",
    "randament(?:e|ul)? (?:atractiv\\p{L}*|competitiv\\p{L}*|ridicat\\p{L}*|excelent\\p{L}*|impresionant\\p{L}*)",
    "potențial (?:de|enorm|uriaș|ridicat|imens)"
   ],
   "min": 2
  },
  {
   "key": "ro_range",
   "label": "Range padding (o gamă largă, o varietate de, o paletă bogată, o serie de)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "o gamă (?:largă|variată|diversă|bogată|vastă|completă)",
    "o varietate de",
    "o multitudine de",
    "o paletă (?:largă|variată|bogată|diversă) de",
    "o mulțime de",
    "o serie de",
    "numeroase",
    "diverse",
    "variate",
    "o selecție (?:largă|bogată|variată|atent aleasă|curată)",
    "pentru toate gusturile",
    "pentru (?:orice|fiecare) (?:gust|buget|stil|ocazie|vârstă|categorie)",
    "ceva pentru (?:toată lumea|fiecare|oricine)",
    "și (?:multe|multe alte|alte) (?:altele|lucruri)",
    "și nu numai",
    "și așa mai departe"
   ],
   "min": 2
  },
  {
   "key": "ro_offers",
   "label": "Generic “oferă o perspectivă / un amestec / o experiență” verb",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "oferă (?:\\p{L}+ ){0,2}(?:o|un) (?:amestec|mix|combinație|gamă|selecție|varietate|experiență|perspectivă|privire|imagine|fereastră|ocazie|oportunitate|șansă|posibilitate)",
    "oferind (?:\\p{L}+ ){0,2}(?:o|un) (?:amestec|mix|combinație|gamă|selecție|varietate|experiență|perspectivă|privire|imagine)",
    "oferă (?:vizitatorilor|oaspeților|clienților|turiștilor|rezidenților|investitorilor|cititorilor|iubitorilor)"
   ],
   "min": 2
  },
  {
   "key": "ro_location_verbs",
   "label": "Stock location verbs (este situat, este amplasat, se poziționează)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?:este|sunt) (?:situat|situată|situate|situați|amplasat|amplasată|amplasate|poziționat|poziționată|poziționate|localizat|localizată|localizate)",
    "se poziționează",
    "își are locul",
    "se găsește (?:la|în|pe)"
   ],
   "min": 3
  },
  {
   "key": "ro_ceea_ce",
   "label": "“ceea ce …” relative tail (ceea ce înseamnă/permite/face)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "ceea ce (?:înseamnă|permite|asigură|contribuie|face|oferă|le permite|îl face|o face|duce la|conduce la)",
    "faptul că",
    "acest lucru se datorează",
    "aceasta se datorează",
    "se datorează faptului"
   ],
   "min": 2
  },
  {
   "key": "ro_no_surprise",
   "label": "“Nu este de mirare că / Nu întâmplător” explainer tic",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "nu (?:este|e) de mirare",
    "nu (?:este|e) (?:surprinzător|o surpriză)",
    "nu (?:este|e) greu de (?:înțeles|imaginat)",
    "(?:este|e) ușor de (?:înțeles|văzut) de ce",
    "nu întâmplător",
    "nu (?:este|e) o coincidență",
    "de ce nu ar fi"
   ]
  },
  {
   "key": "ro_calque_day",
   "label": "English idiom calque (la sfârșitul zilei, în afara cutiei, schimbă regulile jocului)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "la (?:sfârșitul|finalul|capătul) zilei",
    "în afara cutiei",
    "gândi\\p{L}* în afara cutiei",
    "schimbă regulile jocului",
    "schimbătorul? de joc",
    "jocul schimbător",
    "un pas înapoi",
    "ridic[ăa] ștacheta",
    "pe aceeași pagină",
    "la un (?:click|clic) distanță",
    "ultimul,? dar nu (?:cel mai puțin|și cel din urmă)",
    "cu o răsucire",
    "cu un twist",
    "tras(?:ă)? linie",
    "a lua pulsul",
    "ia pulsul",
    "pune (?:pe )?harta",
    "pe radar"
   ]
  },
  {
   "key": "ro_calque_experience",
   "label": "Experience / journey calque (o experiență de neuitat, o călătorie senzorială)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "o experiență (?:de neuitat|memorabilă|unică|autentică|captivantă|imersivă|inegalabilă|nemaipomenită|culinară|senzorială|transformatoare)",
    "experiență imersivă",
    "o călătorie (?:senzorială|culinară|fascinantă|captivantă|de descoperire|către|spre|prin)",
    "o aventură (?:culinară|senzorială|de neuitat)",
    "trăi(?:ți|ește)? (?:experiența|magia|farmecul|momentul)",
    "amintiri (?:de neuitat|care vor dăinui|prețioase)",
    "veți (?:rămâne|fi) (?:fără cuvinte|vrăjiți|cuceriți)"
   ]
  },
  {
   "key": "ro_calque_blend",
   "label": "Blend cliché (tradiție și modernitate, amestec de vechi și nou, unde trecutul întâlnește prezentul)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:un|o) (?:amestec|mix|îmbinare|combinație|fuziune|dans|mozaic|simbioză|împletire|cocktail|echilibru) (?:perfect[ăe]? |armonios |fericit[ăe] |unic[ăe]? |rafinat[ăe]? |subtil[ăe]? )?(?:de|între|dintre) (?:\\p{L}+ ){0,2}(?:tradi\\p{L}+|vech\\p{L}+|clasic\\p{L}*|istori\\p{L}+|trecut\\p{L}*|antic\\p{L}*|autentic\\p{L}*|rustic\\p{L}*|modern\\p{L}*|contemporan\\p{L}*)",
    "tradiți(?:e|a|ei) și modernitate(?:a)?",
    "tradiționalul și modernul",
    "vechiul și noul",
    "trecutul și prezentul",
    "anticul și modernul",
    "unde (?:\\p{L}+ ){1,2}(?:se )?întâln\\p{L}+ (?:cu )?(?:\\p{L}+ ){0,2}(?:modern\\p{L}*|prezent\\p{L}*|lux\\p{L}*|noul)"
   ]
  },
  {
   "key": "ro_hidden_gem",
   "label": "Hidden-gem family (secret bine păstrat, colț de rai, departe de agitație, pe drumuri bătătorite)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "o bijuterie",
    "bijuteria (?:coroanei|insulei|Mediteranei)",
    "secret bine păstrat",
    "o descoperire (?:rară|neașteptată)",
    "(?:încă )?nedescoperit\\p{L}*",
    "ocolit\\p{L}* de turiști",
    "ferit\\p{L}* de (?:agitație|mulțime|turismul de masă)",
    "departe de (?:agitația|forfota|mulțimea|zgomotul|aglomerația)",
    "refugiu (?:liniștit|ferit|de pace|ideal)",
    "(?:un )?col[țt](?:ișor)? de (?:rai|paradis)",
    "un petic de rai",
    "bucățic[ăa] de rai",
    "tărâm (?:al|de|magic|fermecat)",
    "(?:în afara|departe de) drumurilor bătătorite",
    "pe cărări mai puțin umblate"
   ]
  },
  {
   "key": "ro_estate_register",
   "label": "Estate-agent descriptors (proprietate de lux, locație privilegiată, finisaje premium, vedere panoramică)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "proprietate de lux",
    "locație (?:strategică|privilegiată|ideală|excelentă|de top|de neegalat|premium|centrală)",
    "oportunitate (?:unică|de aur|rară|de investiție|excepțională)",
    "investiți[ea] (?:sigură|profitabilă|inteligentă|de succes|solidă)",
    "stil de viață (?:de lux|exclusiv|mediteranean|relaxat|rafinat|sofisticat)",
    "la (?:un pas|câțiva pași|doar câțiva pași) de",
    "finisaje (?:de lux|premium|de înaltă calitate|elegante|rafinate|impecabile)",
    "design (?:modern|contemporan|elegant|rafinat|ultramodern)",
    "vedere panoramică (?:spre|la|asupra|către)",
    "ideal[ăe]? pentru (?:familii|investitori|cei care|cei ce|cupluri|pensionari)",
    "refugiu (?:de lux|exclusiv)",
    "locuință de vis",
    "casa (?:visurilor|de vis)",
    "spații (?:generoase|spațioase|luminoase|amplu)",
    "gata de mutare",
    "de înaltă (?:clasă|calitate|ținută)"
   ],
   "min": 2
  },
  {
   "key": "ro_cta",
   "label": "Marketing call-to-action in editorial copy (nu ratați, contactați-ne, bucurați-vă de)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "programați o vizionare",
    "solicitați o (?:vizionare|ofertă|consultație)",
    "contactați-ne",
    "contactează-ne",
    "nu (?:ratați|rata)",
    "cere(?:ți)? o ofertă",
    "rezervați (?:acum|din timp|astăzi|locul)",
    "vă recomandăm cu (?:căldură|încredere)",
    "recomandăm cu căldură",
    "bucurați-vă de",
    "bucură-te de",
    "răsfățați-vă",
    "răsfață-te",
    "faceți un pas",
    "vă (?:invităm|așteptăm) să",
    "te așteptăm",
    "ofertă (?:exclusivă|limitată|specială|irezistibilă)",
    "prețuri de la",
    "locuri limitate",
    "dacă nu ați fost încă"
   ]
  },
  {
   "key": "ro_pr_register",
   "label": "Press-release register (încântați să anunțăm, lider de piață, soluții inovatoare, valoare adăugată)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:este|sunt) (?:încântat|încântată|încântați|mândru|mândră|mândri) să",
    "cu (?:mândrie|deosebită plăcere) (?:anunț|prezent)\\p{L}*",
    "lansează oficial",
    "își extinde (?:prezența|portofoliul|oferta|operațiunile)",
    "angajament(?:ul)? (?:ferm )?(?:față de|pentru) (?:excelență|calitate|sustenabilitate|clienți|comunitate)",
    "ferm angajat",
    "viziune (?:strategică|clară|inovatoare|ambițioasă)",
    "lider(?:i)? (?:de piață|în domeniu|în industrie|global\\p{L}*|regional\\p{L}*)",
    "soluții (?:inovatoare|integrate|personalizate|la cheie|de ultimă generație|complete)",
    "de ultimă generație",
    "de talie (?:mondială|internațională)",
    "de clasă mondială",
    "portofoliu (?:diversificat|impresionant|variat|solid)",
    "valoare adăugată",
    "parteneriat(?:e|ul)? strategic\\p{L}*",
    "(?:vastă|bogată|îndelungată) experiență",
    "standarde (?:înalte|ridicate)",
    "excelență(?:a)? (?:operațională|în servicii|în ospitalitate)"
   ]
  },
  {
   "key": "ro_anglicism",
   "label": "Untranslated English luxury/business jargon (must-have, boutique, rooftop, insight, networking)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "must-?have",
    "must-?try",
    "trendy",
    "glamour\\p{L}*",
    "boutique",
    "rooftop",
    "networking",
    "insight\\p{L}*",
    "know-?how",
    "stakeholder\\p{L}*",
    "cutting-?edge",
    "state-of-the-art",
    "game-?changer",
    "best-?seller\\p{L}*",
    "top-?notch",
    "hot-?spot\\p{L}*",
    "bucket list",
    "instagramabil\\p{L}*",
    "foodie\\p{L}*",
    "premium",
    "exclusive",
    "chic",
    "curated",
    "seamless",
    "tailor-?made",
    "sustainable",
    "unwind"
   ],
   "min": 2
  },
  {
   "key": "ro_english_leak",
   "label": "Untranslated English function words inside Romanian text",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "the",
    "and",
    "with",
    "which",
    "your",
    "our",
    "this",
    "that",
    "from",
    "have",
    "will",
    "for the",
    "of the"
   ],
   "min": 4
  },
  {
   "key": "ro_vague_attr",
   "label": "Vague attribution (experții spun, specialiștii consideră, se spune că)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:experții|specialiștii|analiștii|cercetătorii|observatorii|comentatorii|economiștii|juriștii) (?:spun|afirmă|consideră|susțin|sunt de acord|estimează|avertizează|cred|apreciază|notează|subliniază|recomandă|sugerează)",
    "unii (?:experți|analiști|specialiști|economiști|observatori)",
    "mulți (?:oameni|experți|specialiști|investitori|locuitori|turiști|localnici|cumpărători|rezidenți|străini) (?:spun|cred|consideră|afirmă|apreciază|preferă|aleg|descoperă)",
    "se spune că",
    "se pare că",
    "se consideră (?:în general )?că",
    "este general (?:acceptat|cunoscut|recunoscut)",
    "după cum se știe",
    "toată lumea știe",
    "după unii"
   ]
  },
  {
   "key": "ro_vague_sources",
   "label": "Unsourced evidence (studiile arată, statisticile sugerează, conform unor surse)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:studiile|cercetările|statisticile|datele|sondajele|rapoartele|analizele|cifrele) (?:recente |disponibile |oficiale )?(?:arată|sugerează|demonstrează|indică|dezvăluie|confirmă|relevă|evidențiază)",
    "conform (?:unor|mai multor) (?:studii|surse|rapoarte|date|analize|estimări|specialiști)",
    "potrivit (?:unor|mai multor) (?:studii|surse|rapoarte|date|analize|estimări|specialiști|experți)",
    "potrivit (?:experților|specialiștilor|analiștilor|cercetătorilor|observatorilor)",
    "potrivit unor (?:informații|date)",
    "surse (?:din domeniu|apropiate|bine informate|din piață)"
   ]
  },
  {
   "key": "ro_bureau_passive",
   "label": "Bureaucratic passive (se realizează, a fost efectuată, urmează a fi, se desfășoară)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "se (?:realizează|efectuează|desfășoară|derulează|procedează|impune|constată|poate (?:observa|aprecia|menționa|concluziona))",
    "a fost efectuat[ăe]?",
    "au fost efectuate",
    "a fost realizat[ăe]?",
    "au fost realizat[ei]",
    "urmează a fi",
    "urmează să fie",
    "este necesar(?:ă)? a",
    "necesită a fi",
    "este de așteptat ca",
    "este de dorit",
    "prezintă (?:o|un) (?:importanță|interes|relevanță|avantaj|particularitate)",
    "în scopul",
    "în baza",
    "în temeiul"
   ],
   "min": 2
  },
  {
   "key": "ro_officialese",
   "label": "Officialese pile-up (de către, aferent, sus-menționat, în speță, prin intermediul)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "de către",
    "se impune",
    "aferent\\p{L}*",
    "în scopul",
    "în temeiul",
    "sus-?menționat\\p{L}*",
    "sus-?amintit\\p{L}*",
    "precitat\\p{L}*",
    "în speță",
    "se constată",
    "prin intermediul",
    "la nivelul",
    "la momentul actual",
    "în conformitate cu",
    "cu privire la",
    "pe parcursul",
    "precum și",
    "respectiv",
    "având în vedere (?:faptul )?că",
    "ținând cont de faptul"
   ],
   "min": 3
  },
  {
   "key": "ro_light_verb",
   "label": "Light-verb nominalisation (a efectua o plată, a realiza o analiză, a desfășura o activitate)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:efectu|realiz|desfășur|derul)\\p{L}* (?:o|un|plata|plăți|plățile|verificări|verificarea|achiziția|tranzacția|analiza|investiția|demersuri\\p{L}*|vizit\\p{L}*|inspecți\\p{L}*|control\\p{L}*|evaluar\\p{L}*|activități\\p{L}*|operațiuni\\p{L}*|procedura|procesul)",
    "(?:efectuarea|realizarea|desfășurarea|implementarea|derularea|punerea în aplicare) (?:unei|unui|unor|acestei|acestui|acestor|procesului|procedurii|activității|demersurilor)",
    "procesul de (?:implementare|dezvoltare|realizare|identificare|obținere|evaluare|analiză|achiziție|optimizare)",
    "activitatea de (?:promovare|monitorizare|evaluare|dezvoltare)"
   ],
   "min": 2
  },
  {
   "key": "ro_not_only_ext",
   "label": "Contrast frames beyond “nu doar … ci și” (nu se limitează la, dincolo de simplul, nu înseamnă doar)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "nu se (?:limitează|rezumă|reduce) (?:doar |numai )?la",
    "dincolo de (?:simplul|simpla|simplele|simplu)",
    "nu (?:înseamnă|este vorba|e vorba) (?:doar|numai)",
    "nu (?:este|e) (?:doar|numai) despre",
    "nu mai (?:este|e) (?:doar|numai)",
    "nu numai că[^.?!]{0,80}, ci",
    "mult mai mult decât",
    "mai mult decât (?:un|o) (?:loc|oraș|destinație|restaurant|hotel|proiect|investiție|cartier)"
   ]
  },
  {
   "key": "ro_nu_doar",
   "label": "“nu doar / nu numai” repeated",
   "severity": "low",
   "kind": "word",
   "alts": [
    "nu doar",
    "nu numai",
    "atât[^.?!]{3,60} cât și"
   ],
   "min": 2
  },
  {
   "key": "ro_tricolon_abstract",
   "label": "Abstract-noun tricolon (eleganță, confort și autenticitate)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:eleganț[ăa]|rafinament|confort|lux|autenticitate|tradiți[ea]|inovați[ea]|calitate|pasiune|creativitate|durabilitate|excelență|armonie|echilibru|măiestrie|rigoare|comunitate|cultură|istorie|natură|gastronomie|ospitalitate|siguranță|stabilitate|performanță|transparență|expertiză),? (?:eleganț[ăa]|rafinament|confort|lux|autenticitate|tradiți[ea]|inovați[ea]|calitate|pasiune|creativitate|durabilitate|excelență|armonie|echilibru|măiestrie|rigoare|comunitate|cultură|istorie|natură|gastronomie|ospitalitate|siguranță|stabilitate|performanță|transparență|expertiză),? (?:și|sau) (?:eleganț[ăa]|rafinament|confort|lux|autenticitate|tradiți[ea]|inovați[ea]|calitate|pasiune|creativitate|durabilitate|excelență|armonie|echilibru|măiestrie|rigoare|comunitate|cultură|istorie|natură|gastronomie|ospitalitate|siguranță|stabilitate|performanță|transparență|expertiză)"
   ]
  },
  {
   "key": "ro_tricolon_adj",
   "label": "Adjective tricolon repeated (X, Y și Z, three times in a text)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "\\p{L}{4,}, \\p{L}{4,} și \\p{L}{4,}"
   ],
   "min": 4
  },
  {
   "key": "ro_cyprus_water_sun",
   "label": "Cyprus cliché: ape cristaline, plaje de vis, 300 de zile de soare",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "insula (?:Afroditei|zeiței(?: iubirii)?|iubirii|soarelui)",
    "locul de naștere al (?:zeiței )?Afrodit\\p{L}*",
    "ape(?:le)? (?:cristaline|turcoaz|limpezi|azurii|smarald|de un albastru)",
    "plaje (?:de vis|imaculate|nemaipomenite|aurii|însorite|virgine|paradisiace|de poveste)",
    "(?:nisip|nisipuri) (?:auri\\p{L}*|fin\\p{L}*|alb\\p{L}*)",
    "(?:peste|mai mult de|aproape|circa) 300 de zile",
    "300 de zile (?:de soare|însorite)",
    "soare (?:generos|arzător|bogat|blând)",
    "clim[ăa] (?:mediteraneană )?(?:blândă|plăcută|ideală|perfectă|minunată|încântătoare)",
    "stil de viață mediteranean"
   ]
  },
  {
   "key": "ro_cyprus_crossroads",
   "label": "Cyprus cliché: perla Mediteranei, răscruce, destinație ideală, locație strategică",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "perla (?:Mediteranei|Mediteranei de Est|Orientului)",
    "răscrucea (?:dintre|între) (?:Europa|trei continente|Orient|Est|Asia)",
    "la răscruce de (?:drumuri|continente|civilizații|culturi)",
    "poarta (?:către|spre) (?:Orient|Europa|Orientul Mijlociu|Asia)",
    "destinați[ea] (?:ideală|perfectă|de vis|de top|preferată|râvnită|de excepție|numărul)",
    "locați[ea] strategică",
    "poziție strategică",
    "raiul (?:fiscal|pe pământ)",
    "topitoare de culturi",
    "creuzet de culturi",
    "mozaic cultural",
    "istori[ea] milenară",
    "moștenire (?:culturală )?bogată",
    "mii de ani de istorie"
   ]
  },
  {
   "key": "ro_cyprus_people",
   "label": "Cyprus cliché: oameni primitori, ospitalitate legendară",
   "severity": "low",
   "kind": "word",
   "alts": [
    "ospitalitate[a]? (?:caldă|legendară|cipriotă|proverbială|unică)",
    "oameni (?:primitori|calzi|ospitalieri|zâmbitori)",
    "localnici (?:primitori|calzi|ospitalieri|zâmbitori)",
    "zâmbetul (?:cipriot|localnicilor)",
    "ritm(?:ul)? (?:de viață )?(?:relaxat|lent|liniștit)",
    "viața decurge (?:mai )?(?:lent|în ritm)",
    "siesta"
   ]
  },
  {
   "key": "ro_spaced_hyphen",
   "label": "Spaced hyphen used as a dash (word - word)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "\\p{L}+ - \\p{L}+"
   ],
   "min": 2
  },
  {
   "key": "ro_quote_straight",
   "label": "Straight double quotes \"…\" instead of „…”",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\"[^\"\\n]{2,160}\""
   ]
  },
  {
   "key": "ro_quote_english",
   "label": "English curly quotes “…” instead of „…”",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "“[^”\\n]{2,160}”",
    "‘[^’\\n]{2,120}’"
   ]
  },
  {
   "key": "ro_quote_mixed",
   "label": "Mixed quote pair („… with a straight or wrong closer)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "„[^”\"“\\n]{2,160}\"",
    "„[^”\"“\\n]{2,160}“",
    "«[^»\\n]{2,160}\""
   ]
  },
  {
   "key": "ro_num_en_thousands",
   "label": "English thousands/decimal format (1,200 or 1,200.50)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "\\d{1,3}(?:,\\d{3})+(?:\\.\\d+)?",
    "\\d+\\.\\d{1,2} ?(?:%|milioane|miliarde|mii|mld|mil|km|ani|euro|lei|m²|mp|hectare)"
   ]
  },
  {
   "key": "ro_currency_prefix",
   "label": "Currency before the number (€1.200, EUR 1200, $) instead of 1.200 de euro / 1.200 €",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:€|\\$|£|EUR|USD|GBP) ?\\d[\\d.,]*\\d?",
    "\\d+ ?(?:k|K) (?:euro|EUR|€)"
   ]
  },
  {
   "key": "ro_euro_de",
   "label": "Missing “de” before euro/lei after numbers ≥ 20 (250 euro → 250 de euro)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "(?:\\d{1,3}\\.)*\\d*(?:[2-9]\\d|00) (?:euro|lei|dolari|lire)"
   ]
  },
  {
   "key": "ro_date_en",
   "label": "English-style date/time (October 12, 2026; 12th; 10/12/2026; 3 PM)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:ianuarie|februarie|martie|aprilie|mai|iunie|iulie|august|septembrie|octombrie|noiembrie|decembrie) \\d{1,2},? \\d{4}",
    "\\d{1,2}(?:st|nd|rd|th)",
    "\\d{1,2}/\\d{1,2}/\\d{2,4}",
    "\\d{4}-\\d{2}-\\d{2}",
    "\\d{1,2}(?::\\d{2})? ?(?:p\\.m\\.|a\\.m\\.|pm)"
   ]
  },
  {
   "key": "ro_no_diacritics",
   "label": "Romanian typed without diacritics (dupa, decat, pana, inca, ca sa)",
   "severity": "high",
   "kind": "word",
   "alts": [
    "dupa",
    "decat",
    "pana la",
    "inca",
    "catre",
    "fiindca",
    "cetatean\\p{L}*",
    "intr-un",
    "intr-o",
    "mentionat\\p{L}*",
    "romanesc\\p{L}*",
    "locuinta",
    "investitie",
    "situatie",
    "informatie",
    "functioneaza",
    "ca sa",
    "si (?:in|la|cu|de|pe|o|un|a)"
   ],
   "min": 2
  },
  {
   "key": "ro_old_orth",
   "label": "Pre-1993 î-in-the-middle spelling (sînt, cînd, romîn) or â at word edge",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "sînt\\p{L}*",
    "cînd",
    "gînd\\p{L}*",
    "pămînt\\p{L}*",
    "romîn\\p{L}*",
    "mîn\\p{L}*",
    "rîu\\p{L}*",
    "rînd\\p{L}*",
    "vîrst\\p{L}*",
    "hotărît\\p{L}*",
    "cuvînt\\p{L}*",
    "â\\p{L}*",
    "\\p{L}+â"
   ]
  },
  {
   "key": "ro_symbol_glyphs",
   "label": "Decorative glyphs / arrows / bullets in running prose",
   "severity": "low",
   "kind": "word",
   "alts": [
    "[\\u2B50\\u2B06\\u2B07\\u2B05\\u2B95\\u2190-\\u21FF\\u25A0-\\u25FF\\u2022\\u2605\\u2606\\u{1F000}-\\u{1F2FF}]"
   ]
  },
  {
   "key": "ro_tu_vous_mix",
   "label": "Mixed address registers (tu-forms and dumneavoastră-forms in one text)",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "(?:poți|ești|vei|îți|te-ai)[\\s\\S]{0,1500}?(?:puteți|sunteți|veți|vă|dumneavoastră)",
    "(?:puteți|sunteți|veți|dumneavoastră)[\\s\\S]{0,1500}?(?:poți|ești|vei|îți|te-ai)"
   ]
  },
  {
   "key": "ro_reader_address",
   "label": "Direct reader address pile-up (puteți, veți, vă, ești, poți)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "puteți",
    "veți",
    "vă",
    "sunteți",
    "doriți",
    "aveți",
    "dumneavoastră",
    "ești",
    "poți",
    "vei",
    "îți"
   ],
   "min": 5
  },
  {
   "key": "ro_disclaimer",
   "label": "Repeated boilerplate disclaimer (consultați un specialist, nu constituie sfat)",
   "severity": "low",
   "kind": "word",
   "alts": [
    "consultați (?:întotdeauna |mereu )?(?:un|o) (?:specialist|avocat|consilier|expert|contabil|jurist)",
    "vă recomandăm să consultați",
    "se recomandă consultarea",
    "nu constituie (?:sfat|consultanță|o recomandare)",
    "nu reprezintă (?:sfat|consultanță|o recomandare)",
    "acest (?:articol|material) (?:are|este scris|a fost scris) (?:caracter|în scop)(?: informativ)?",
    "doar în scop informativ"
   ],
   "min": 2
  },
  {
   "key": "ro_heart_of",
   "label": "“în inima / în sufletul / în miezul” spatial cliché",
   "severity": "medium",
   "kind": "word",
   "alts": [
    "în (?:inima|sufletul|miezul) (?:\\p{L}+ ){0,2}(?:Mediteranei|Ciprului|insulei|orașului|capitalei|Limassolului|Nicosiei|Paphosului|Larnacăi|culturii|istoriei|comunității|acțiunii|vechiului)"
   ],
   "min": 2
  }
 ],
 "banned": [
  "Merită menționat că",
  "Este important de menționat că",
  "Este esențial să înțelegem",
  "Trebuie subliniat că",
  "De menționat că",
  "Este de remarcat",
  "Nu este un secret că",
  "joacă un rol crucial",
  "joacă un rol esențial",
  "joacă un rol cheie",
  "are un rol esențial",
  "subliniază importanța",
  "evidențiază importanța",
  "pune în lumină",
  "scoate în evidență",
  "este o mărturie a",
  "reprezintă o dovadă",
  "constituie un exemplu",
  "un exemplu elocvent",
  "un exemplu strălucit",
  "reprezintă",
  "constituie",
  "dispune de",
  "se remarcă prin",
  "se caracterizează prin",
  "beneficiază de",
  "se bucură de",
  "o gamă largă de",
  "o gamă variată de",
  "o multitudine de",
  "o varietate de",
  "o paletă bogată de",
  "o serie de",
  "pentru toate gusturile",
  "și multe altele",
  "și nu numai",
  "în era digitală",
  "într-o lume în continuă schimbare",
  "în peisajul actual",
  "în contextul actual",
  "în zilele noastre",
  "mai mult ca oricând",
  "tot mai mulți",
  "din ce în ce mai",
  "fie că ești … fie că …",
  "fie că sunteți … fie că …",
  "descoperă",
  "scufundă-te în",
  "lasă-te purtat",
  "bucură-te de",
  "nu rata",
  "nu ratați",
  "vă invităm să",
  "te invităm să",
  "insula Afroditei",
  "perla Mediteranei",
  "ape cristaline",
  "plaje de vis",
  "nisip auriu",
  "peste 300 de zile de soare",
  "destinație ideală",
  "destinație de vis",
  "locație strategică",
  "răscrucea dintre trei continente",
  "poarta spre Orient",
  "ospitalitate legendară",
  "oameni primitori",
  "stil de viață mediteranean",
  "raiul fiscal",
  "mozaic cultural",
  "topitoare de culturi",
  "istorie milenară",
  "moștenire culturală bogată",
  "comoară ascunsă",
  "bijuterie ascunsă",
  "secret bine păstrat",
  "colț de rai",
  "festin pentru simțuri",
  "simfonie de arome",
  "explozie de arome",
  "o experiență de neuitat",
  "o călătorie senzorială",
  "un amestec de tradiție și modernitate",
  "unde trecutul întâlnește prezentul",
  "un adevărat paradis",
  "pitoresc",
  "vibrant",
  "fascinant",
  "captivant",
  "inedit",
  "spectaculos",
  "rafinat",
  "sofisticat",
  "impecabil",
  "de excepție",
  "de top",
  "de neuitat",
  "unic în felul său",
  "unul dintre cele mai",
  "nu doar … ci și",
  "nu numai … ci și",
  "nu se limitează la",
  "mai mult decât un simplu",
  "dincolo de simplul",
  "În concluzie",
  "Pe scurt",
  "În final",
  "În încheiere",
  "Rămâne de văzut",
  "timpul va arăta",
  "viitorul pare luminos",
  "un lucru este cert",
  "privind spre viitor",
  "subliniind",
  "evidențiind",
  "reflectând",
  "demonstrând",
  "asigurând",
  "contribuind",
  "oferind",
  "facilitând",
  "în cadrul",
  "în vederea",
  "în ceea ce privește",
  "datorită faptului că",
  "se realizează",
  "a fost efectuată",
  "urmează a fi",
  "prin intermediul",
  "la nivelul",
  "de către",
  "la sfârșitul zilei",
  "în afara cutiei",
  "schimbă regulile jocului",
  "peisajul juridic",
  "ecosistem",
  "piatră de temelie",
  "catalizator",
  "pilon",
  "o punte între",
  "experții spun",
  "specialiștii consideră",
  "studiile arată",
  "se spune că",
  "potrivit unor surse",
  "mulți investitori consideră",
  "proprietate de lux",
  "oportunitate unică",
  "investiție sigură",
  "finisaje premium",
  "vedere panoramică",
  "ideal pentru familii și investitori",
  "contactați-ne",
  "programați o vizionare",
  "este încântat să anunțe",
  "lider de piață",
  "soluții inovatoare",
  "de ultimă generație",
  "valoare adăugată",
  "angajament față de excelență",
  "Sper că acest lucru vă ajută",
  "Ca model de limbaj",
  "Desigur! Iată",
  "Spune-mi dacă vrei modificări"
 ],
 "closers": [
  "În concluzie",
  "În încheiere",
  "Pe scurt",
  "În final",
  "În definitiv",
  "În cele din urmă",
  "Așadar",
  "Per total",
  "În ansamblu",
  "În linii mari",
  "Putem spune că",
  "Se poate concluziona că",
  "Rezumând",
  "Sintetizând",
  "Privind spre viitor",
  "Pe viitor",
  "Rămâne de văzut",
  "Timpul va arăta",
  "Un lucru este cert",
  "Viitorul pare promițător",
  "Toate acestea arată că",
  "Cu alte cuvinte",
  "Concluzia este clară",
  "Într-un cuvânt",
  "Ca o concluzie",
  "Gânduri finale"
 ],
 "openers": [
  "Este important de menționat că",
  "Merită menționat că",
  "Este esențial să înțelegem",
  "Iată ce trebuie să știți",
  "Tot ce trebuie să știți despre",
  "Haideți să explorăm",
  "Să aruncăm o privire",
  "În acest articol vom",
  "Fie că sunteți",
  "Dacă plănuiți",
  "Dacă sunteți în căutarea",
  "Într-o lume în continuă schimbare",
  "În era digitală",
  "În peisajul actual",
  "În contextul actual",
  "În zilele noastre",
  "Mai mult ca oricând",
  "Imaginați-vă",
  "V-ați întrebat vreodată",
  "Nu este un secret că",
  "Situat în inima Mediteranei",
  "Cuibărit între",
  "Cipru, insula Afroditei,",
  "Odată cu trecerea timpului",
  "Dragi cititori",
  "De-a lungul istoriei"
 ],
 "sheet": [
  "Write as a working Romanian newspaper or magazine journalist (Adevărul, HotNews, G4Media, Forbes România), not as a translator: re-order and re-cut English sentences, keep the facts and drop the syntax.",
  "Open news with the fact in the perfect compound tense, subject first: “Guvernul a aprobat marți …”. Put the source in the same sentence or the next (“a anunțat ministerul”, “potrivit datelor Departamentului de Cadastru”), never in a throat-clearing lead.",
  "Name the who, what, how much and when inside the first two sentences: a figure, a date, a named institution or person. A paragraph with none of them gets one or is cut.",
  "Use plain Romanian verbs where AI uses copulas and nominalisations: “este”, “are”, “a deschis”, “a cumpărat”; not “reprezintă”, “constituie”, “dispune de”, “a efectuat o achiziție”, “se realizează”.",
  "Prefer active voice and finite verbs to “se + passive”, “a fost efectuată”, “urmează a fi”, “de către”, “în cadrul”, “în vederea”, “prin intermediul”, “la nivelul”, “în ceea ce privește”, “datorită faptului că”.",
  "Rotate attribution verbs and match them to the speech act: a declarat, a spus, a explicat, a precizat, a adăugat, a notat, a admis, a recunoscut, a insistat, a avertizat, a amintit, a transmis (statements), a susținut (contested claims). Never repeat the same verb in consecutive attributions.",
  "Attribute to a named person, institution or document with a role and a date. Replace “experții spun”, “studiile arată”, “se spune că” with the actual source or cut the claim.",
  "Vary sentence length on purpose: a six-word sentence next to a thirty-word one with a subordinate clause. Never three sentences in a row that open with the same word, and never three “Acesta/Aceasta” in a row.",
  "Drop redundant subject pronouns and demonstratives: Romanian carries the subject in the verb. Repeat the noun instead of chaining “acesta, aceasta, aceștia”.",
  "Do not start paragraphs with connectives. Cut “De asemenea”, “În plus”, “Mai mult”, “Totodată”, “Cu toate acestea”, “Prin urmare”, “Astfel”; let the logic sit in the sentence order, or use “Însă”, “Dar”, “Iar” inside the sentence.",
  "No gerund tails that comment on the previous clause (“…, subliniind importanța…”, “…, asigurând…”, “…, evidențiind…”). Finish the sentence and start a new one with a fact; use a gerund only for a real simultaneous action.",
  "No “nu doar … ci și”, “nu numai … ci”, “nu se limitează la”, “mai mult decât un simplu”. State what the thing is, then what else it does, in two plain clauses.",
  "Avoid tricolons by habit (“eleganță, confort și autenticitate”). Give two items or four, or one precise item; an abstract-noun triple is a machine signature.",
  "Cut significance inflation: “joacă un rol crucial”, “subliniază importanța”, “este o mărturie a”, “marchează o cotitură”. Say what changed, for whom and by how much.",
  "Never close with a moral, a summary or a forecast (“În concluzie”, “Pe scurt”, “Rămâne de văzut”, “Viitorul pare luminos”). End on the last concrete fact, the next date or deadline, a quote, or a sharp detail.",
  "Do not open with scene-setting or throat-clearing (“Este important de menționat”, “Într-o lume în continuă schimbare”, “Situat în inima Mediteranei”, “Fie că ești … fie că …”, “Iată ce trebuie să știți”). Start with the news or the image.",
  "Cyprus clichés are banned: insula Afroditei, ape cristaline, perla Mediteranei, 300 de zile de soare, destinație ideală, locație strategică, răscruce de trei continente, ospitalitate legendară. Replace each with a place name, a number or an observed detail.",
  "Kill English calques: “la sfârșitul zilei”, “o bijuterie ascunsă”, “o experiență de neuitat”, “un amestec de tradiție și modernitate”, “schimbă regulile jocului”, “unul dintre cele mai …”, “în timp ce” for every “while”. Rewrite the idea the way a Romanian would say it.",
  "Keep hype adjectives out (pitoresc, vibrant, fascinant, captivant, spectaculos, rafinat, autentic, unic, remarcabil). One concrete detail (material, price, year, name) replaces three adjectives.",
  "Estate-agent and press-release language is forbidden in editorial copy: “proprietate de lux”, “oportunitate unică”, “finisaje premium”, “soluții inovatoare”, “lider de piață”, “valoare adăugată”, “contactați-ne”. Describe the object and the deal in measurable terms.",
  "Use only comma-below ș and ț (never cedilla ş ţ), and ă, â, î correctly: î at the start and end of a word, â inside (cuvânt, sunt, într-o); never the pre-1993 spellings sînt, cînd, romîn. Never type Romanian without diacritics.",
  "Quotes are „…” (low-9 opening U+201E, closing U+201D), with «…» for a quote inside a quote. Never \"…\" straight or English “…”. Place the full stop after the closing mark unless the quote is a full sentence.",
  "No em or en dashes and no spaced hyphens as dashes. Use a comma, colon, full stop, parentheses or restructure; keep the hyphen only inside compounds and clitics (într-o, s-a, ex-ministru, sud-est).",
  "Numbers: dot as thousands separator and comma as decimal (1.200; 12,5%; 3,8 milioane). Years stay unseparated (2026). Spell out one to nine in running prose, figures from 10 up; always figures for money, percentages, areas and dates.",
  "Currency goes after the number, and amounts from 20 up take “de”: 1.200 de euro, 250 de lei, 45 de euro; but 2 euro, 15 euro, 105 euro. Do not write €1.200, EUR 1200 or 1,200 euro. The euro is invariable (două milioane de euro).",
  "Dates and times: “12 octombrie 2026”, “joi, 9 octombrie”, months and weekdays in lowercase, “ora 18.30” or “18:30”; never “October 12”, “12th”, “6 PM”, or slash dates. Areas as “120 m²” (non-breaking space) or “120 de metri pătrați”.",
  "Headings and titles use sentence case: capital only on the first word and proper nouns (“Cum se cumpără o proprietate în Limassol”), never English Title Case; no trailing full stop; no generic labels (Introducere, Concluzii, Aspecte cheie, Întrebări frecvente).",
  "Use Romanian exonyms and standard institution names: Cipru, Nicosia, Larnaca, Limassol, Paphos, Famagusta, Camera Reprezentanților, Banca Centrală a Ciprului, Departamentul de Cadastru și Topografie. Gloss a Greek or English acronym once, then use it.",
  "Keep one register per piece: third person, no “tu” and no “dumneavoastră” address in news, business and legal copy. Direct “dumneavoastră” is acceptable only in an interview question or a relocation checklist, and never mixed with tu-forms.",
  "Commas: none before “și” in a simple list, no comma between subject and predicate, a comma before dar, însă, iar, ci and after a fronted subordinate clause. Avoid piling “al/a/ai/ale” genitive chains; break them with a verb.",
  "Replace vague quantifiers (“o creștere semnificativă”, “interes crescut”, “cerere în creștere”) with the figure and its base: “+6,4% față de 2025”, “1.240 de tranzacții în primele opt luni”.",
  "Use anglicisms only when the Romanian press itself does (cash flow, hub, startup); translate the rest (“must-have”, “boutique”, “rooftop”, “insight”). Never leave a stray English function word in the text.",
  "Keep legal and tax disclaimers to one plain sentence at the end of the piece, never repeated; cite the instrument once by name, number and year, then explain its effect in one sentence a lay reader can use.",
  "Never output assistant language: no “Sper că v-a ajutat”, “Iată versiunea”, “Spune-mi dacă vrei modificări”, no placeholders, no markdown asterisks, hashes or backticks in body text."
 ],
 "pairs": [
  {
   "bad": "Cipru, insula Afroditei, reprezintă o destinație ideală pentru investitori, oferind o gamă largă de oportunități imobiliare într-o locație strategică.",
   "good": "Cumpărătorii străini au luat anul trecut aproape o treime din apartamentele noi vândute pe litoralul din Limassol, iar prețul mediu a urcat la peste 4.000 de euro pe metru pătrat.",
   "why": "Brochure cliché, copula inflation, “gamă largă” and “locație strategică” are replaced by a buyer group, a share and a price (figures illustrative)."
  },
  {
   "bad": "Ministerul a anunțat noile măsuri, subliniind importanța transparenței și asigurând un cadru stabil pentru investitori.",
   "good": "Ministerul a anunțat noile măsuri marți. Registrul proprietarilor efectivi devine public din ianuarie, iar firmele care nu raportează până atunci riscă amenzi de până la 20.000 de euro.",
   "why": "Gerund tails that comment (“subliniind”, “asigurând”) are replaced by two finite sentences with date and penalty."
  },
  {
   "bad": "Restaurantul nu este doar un loc unde se mănâncă, ci și o experiență culinară de neuitat.",
   "good": "La Kyma se mănâncă bine și se stă mult: caracatița la grătar costă 16 euro, iar pâinea vine caldă, din cuptorul de lângă bar.",
   "why": "“Nu doar … ci și” plus “experiență de neuitat” replaced by a price and a physical detail."
  },
  {
   "bad": "Proiectul reprezintă o dovadă a angajamentului dezvoltatorului față de excelență și constituie un reper în peisajul imobiliar local.",
   "good": "Dezvoltatorul a predat la timp primul bloc, cu 48 de apartamente, și a început turnarea fundației pentru al doilea.",
   "why": "“Reprezintă/constituie” and abstract praise give way to a verifiable action."
  },
  {
   "bad": "În cadrul procesului de achiziție, a fost efectuată o verificare a titlului de proprietate de către avocat, în vederea evitării eventualelor litigii.",
   "good": "Înainte de semnare, avocatul a verificat titlul de proprietate la Departamentul de Cadastru, ca să nu apară litigii mai târziu.",
   "why": "Bureaucratic chain (în cadrul, a fost efectuată, de către, în vederea) turned into an active sentence."
  },
  {
   "bad": "În concluzie, Cipru rămâne o destinație promițătoare, iar viitorul pare luminos pentru toți cei interesați.",
   "good": "Următorul termen este 30 iunie, când Camera Reprezentanților votează proiectul în a doua lectură.",
   "why": "Moral summary closer replaced by the next concrete date."
  },
  {
   "bad": "Experții spun că piața chiriilor va continua să crească, iar studiile arată un interes tot mai mare din partea străinilor.",
   "good": "Banca Centrală estimează o scumpire a chiriilor cu 6-8% în 2026; agenția Cyprus Rent Index a numărat cu 14% mai multe contracte semnate de cetățeni străini în primul semestru.",
   "why": "Vague attribution replaced by named sources and figures (illustrative)."
  },
  {
   "bad": "Chiriile au urcat la \"aproape €1,500\" pe lună – cu 12.5% mai mult decât în 2025.",
   "good": "Chiriile au urcat la aproape 1.500 de euro pe lună, cu 12,5% mai mult decât anul trecut.",
   "why": "Fixes straight quotes, currency before number, English thousands, en dash and decimal point."
  },
  {
   "bad": "O simfonie de arome vă încântă papilele gustative în această bijuterie ascunsă, unde tradiția întâlnește modernitatea.",
   "good": "Sufleul de brânză halloumi iese din cuptor cu o crustă subțire, iar sosul de smochine, făcut în casă, taie din sărăție. Bucătarul, Andreas Hadjis, gătește aici de unsprezece ani.",
   "why": "Sensory padding and calques replaced by what is on the plate and a named person."
  },
  {
   "bad": "Este important de menționat că, într-o lume în continuă schimbare, noul regim fiscal joacă un rol crucial pentru profesioniștii care se mută în Cipru.",
   "good": "Profesioniștii care se mută în Cipru plătesc, din ianuarie, 12,5% impozit pe profit și pot deduce până la 20% din venitul salarial în primii trei ani. Mutarea se decide acum, nu după Paște.",
   "why": "Throat-clearing and significance inflation replaced by the rule, the rate and the deadline (illustrative)."
  }
 ],
 "desks": {
  "news": "Lede in the perfect compound tense with the actor first, source in the same sentence or the next, figures and a date in the first two lines. Short paragraphs, no adjectives of praise, no closing moral. Headlines in present tense, sentence case, no full stop.",
  "business": "Forbes România and G4Media style: number, base and comparison first (+8,2% față de 2025), then the cause named by a person or document. Verbs of action over abstract nouns; no “dinamic”, “robust”, “sinergie”. End on the next report date or decision.",
  "property_legal": "Concrete and procedural: who signs what, at which office, within how many days, at what cost in euro. Cite the act once with number and year and say what it changes in plain words. No estate-agent adjectives, one single disclaimer sentence at most.",
  "relocation_guide": "Second-order service journalism in the third person or an impersonal imperative: steps with durations, fees in „x de euro”, the office and its name, the document list. State the catch or the delay a Romanian will actually hit. No “tot ce trebuie să știți”.",
  "economy": "Dry, precise, sourced: institution, indicator, period, comparison. Explain the mechanism in one sentence a lay reader can repeat. Avoid “peisaj economic”, “ecosistem”, “catalizator”; do not forecast beyond what the source says.",
  "culture": "Observation before opinion: name the work, the venue, the date, the people. Opinion rests on one specific detail, not on “fascinant” or “captivant”. Quotes from artists or curators, attributed with varied verbs. Close on a detail or a date, not a verdict.",
  "food": "Dish, ingredient, price, place, named cook; sensory words only when tied to a thing (crustă, fum, lămâie), never “explozie de arome” or “festin”. Cypriot terms (halloumi, souvla, meze, koupepia) kept with a short gloss at first use.",
  "fashion_lifestyle": "Vogue România register: precise nouns (croială, material, atelier, colecție), no “glamour”, “must-have”, “trendy”. Name the designer, the house and the price where known. Wit is welcome; brochure superlatives are not.",
  "travel": "One scene, one route, one price: road, time, ticket, season. Use what the writer saw, heard and paid, with place names in Romanian forms. No “bijuterie ascunsă”, “ape cristaline”, “de neuitat”; the sea is described by colour and temperature, not by cliché.",
  "events": "Service first: what, where, date and time (ora 19.30), price in euro, how to book, who performs. One sentence of context, then logistics; no “nu ratați”, “vă așteptăm”. Past events get a short report with one quote and a headcount.",
  "interview": "Short human lede (who, where, what struck you), then Q and A or a profile with direct quotes in „…” and rotated attribution verbs. Keep the interviewee’s register; address them consistently (dumneavoastră or tu, never mixed). Cut the “Mulțumim pentru interviu” closer.",
  "review": "A verdict backed by specifics: what was tried, what it cost, what failed. Balanced and sceptical, with concrete praise and concrete criticism; no “merită vizitat” without a reason. Give the price, the date visited and a practical caveat.",
  "people": "Portrait through a scene and facts: age, origin, path, the decision that changed things, with dates and figures. Quote them directly; avoid hagiography (“un om pasionat”, “o personalitate remarcabilă”). Let a detail, not an adjective, characterise."
 }
};

export default data;
